;;; mcpkit-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from mcpkit.el

(autoload 'mcpkit-register-service "mcpkit" "\
Register SERVICE in `mcpkit-registry' under NAME.
NAME defaults to the service's name symbol.

(fn SERVICE &optional NAME)")
(autoload 'mcpkit-define-service "mcpkit" "\
Define a new service NAME and register it in `mcpkit-registry'.

(fn NAME &key (PORT 8765) (DESCRIPTION \"\"))")
(autoload 'mcpkit-get-service "mcpkit" "\
Retrieve registered service by NAME (symbol or string).
Alternatively returns NAME-OR-SERVICE if already a SERVICE instance.

(fn NAME-OR-SERVICE)")
(autoload 'mcpkit-remove-service "mcpkit" "\
Remove service by NAME or instance from `mcpkit-registry'.

(fn NAME-OR-SERVICE)")
(autoload 'mcpkit-register-tool "mcpkit" "\
Register a tool NAME on SERVICE-OR-NAME with BODY.
DESCRIPTION is a human-readable docstring.
INPUT-SCHEMA is a JSON schema plist.
DECODE is a function to decode arguments.
ENCODE is a function to encode results.
ASYNC if non-nil means BODY handles calling DONE asynchronously.
BODY is the tool implementation, with ARGS (and DONE if ASYNC) bound.

(fn NAME SERVICE-OR-NAME &rest REST &key DESCRIPTION INPUT-SCHEMA DECODE ENCODE ASYNC &allow-other-keys)" nil t)
(function-put 'mcpkit-register-tool 'lisp-indent-function 2)
(function-put 'mcpkit-register-tool 'doc-string-elt 3)
(autoload 'mcpkit-start-service "mcpkit" "\
Start or merge SERVICE in `mcpkit--active-services'.
ON-COLLISION specifies how tool name collisions are handled:
\\='namespace (default) prefixes tools with `<service-name>__'.
\\='error signals `user-error' if an un-namespaced tool name collides.

(fn NAME-OR-SERVICE &key (ON-COLLISION \\='namespace) PORT)" t)
(autoload 'mcpkit-stop-service "mcpkit" "\
Stop SERVICE by removing it from `mcpkit--active-services'.
If no active services remain, close the underlying `ws-server' socket.

(fn NAME-OR-SERVICE)" t)
(autoload 'mcpkit-service-list-mode "mcpkit" "\
Major mode for browsing and managing MCP services.

\\{mcpkit-service-list-mode-map}

(fn)" t)
(autoload 'mcpkit-service-list-refresh "mcpkit" "\
Refresh the MCP service list buffer." t)
(autoload 'mcpkit-service-list-start-at-point "mcpkit" "\
Start the MCP service at point." t)
(autoload 'mcpkit-service-list-stop-at-point "mcpkit" "\
Stop the MCP service at point." t)
(autoload 'mcpkit-list-services "mcpkit" "\
Display a tabulated list of registered MCP services." t)
(register-definition-prefixes "mcpkit" '("mcpkit-"))


;;; Generated autoloads from mcpkit-ask.el

(autoload 'mcpkit-register-ask-tools "mcpkit-ask" "\
Register `agent-shell-ask` tools on dedicated `agent-shell-ask` service.")

;;; End of scraped data

(provide 'mcpkit-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; mcpkit-autoloads.el ends here
