;;; sprite-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from sprite.el

(autoload 'sprite-create "sprite" "\
Spawn a new sprite daemon with UNIQUE-NAME under the current instance.
The current instance's ID becomes the parent.
Returns the new sprite struct.

(fn UNIQUE-NAME)" t)
(autoload 'sprite-open-frame "sprite" "\
Open a new Emacs frame connected to SPRITE.
When called interactively, select from accessible sprites via
`annotated-completing-read' (when available), annotated with status and
uptime.

(fn SPRITE)" t)
(autoload 'sprite-get-next "sprite" "\
Return the struct of the next available sprite, or nil.
\"Available\" means running and not recently contacted.")
(autoload 'sprite-get-or-create-next "sprite" "\
Return the next available sprite, creating one if none are free.
Signals `user-error' if `sprite-max-count' would be exceeded.")
(defvar sprite-mode nil "\
Non-nil if Sprite mode is enabled.
See the `sprite-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `sprite-mode'.")
(custom-autoload 'sprite-mode "sprite" nil)
(autoload 'sprite-mode "sprite" "\
Global minor mode for managing sprite (subordinate Emacs daemon) state.

Enabling wires the registry into `savehist' persistence and scans the
filesystem for already-running sprites to populate the registry;
disabling removes the `savehist' hooks and variable registration.
See `sprite-mode-map' and `sprite-mode-command-map'.

This is a global minor mode.  If called interactively, toggle the
`Sprite mode' mode.  If the prefix argument is positive, enable the
mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='sprite-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

\\{sprite-mode-map}

(fn &optional ARG)" t)
(register-definition-prefixes "sprite" '("savehist-additional-variables" "sprite-"))


;;; Generated autoloads from sprite-direct.el

(register-definition-prefixes "sprite-direct" '("sprite-direct-"))


;;; Generated autoloads from sprite-fleet.el

(register-definition-prefixes "sprite-fleet" '("sprite-mapc"))


;;; Generated autoloads from sprite-future.el

(register-definition-prefixes "sprite-future" '("sprite-"))


;;; Generated autoloads from sprite-heartbeat.el

(register-definition-prefixes "sprite-heartbeat" '("sprite-"))


;;; Generated autoloads from sprite-list.el

(autoload 'sprite-list "sprite-list" "\
Open the sprite overview buffer." t)
(autoload 'sprite-list-menu "sprite-list" "\
Actions for the sprite overview buffer.

(fn)" t)
(register-definition-prefixes "sprite-list" '("sprite-"))


;;; Generated autoloads from sprite-session.el

(autoload 'sprite-session-add-on-idle "sprite-session" "\
Add FN to `sprite-session-idle-hook' and start the timer if needed.
Logs the registration and delegates to `sprite-session-sync-idle-timer'.

(fn FN)")
(autoload 'sprite-session-remove-on-idle "sprite-session" "\
Remove FN from `sprite-session-idle-hook' and stop the timer if the hook is empty.
Logs the deregistration and delegates to `sprite-session-sync-idle-timer'.

(fn FN)")
(register-definition-prefixes "sprite-session" '("sprite-session-"))

;;; End of scraped data

(provide 'sprite-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; sprite-autoloads.el ends here
