;;; mcpkit-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from mcpkit.el

(autoload 'mcpkit-register-service "mcpkit"
"Register SERVICE in `mcpkit-registry' under NAME.
NAME defaults to the service's name symbol.

(fn SERVICE &optional NAME)")
(autoload 'mcpkit-define-service "mcpkit"
"Define a new service NAME and register it in `mcpkit-registry'.

(fn NAME &key (PORT 8765) (DESCRIPTION \"\"))")
(autoload 'mcpkit-get-service "mcpkit"
"Retrieve registered service by NAME (symbol or string).
Alternatively returns NAME-OR-SERVICE if already a SERVICE instance.

(fn NAME-OR-SERVICE)")
(autoload 'mcpkit-remove-service "mcpkit"
"Remove service by NAME or instance from `mcpkit-registry'.

(fn NAME-OR-SERVICE)")
(autoload 'mcpkit-register-tool "mcpkit"
"Register a tool NAME on SERVICE-OR-NAME with BODY.
DESCRIPTION is a human-readable docstring.
INPUT-SCHEMA is a JSON schema plist.
DECODE is a function to decode arguments.
ENCODE is a function to encode results.
ASYNC if non-nil means BODY handles calling DONE asynchronously.
BODY is the tool implementation, with ARGS (and DONE if ASYNC) bound.

(fn NAME SERVICE-OR-NAME &rest REST &key DESCRIPTION INPUT-SCHEMA DECODE ENCODE ASYNC &allow-other-keys)" nil t)
(function-put 'mcpkit-register-tool 'doc-string-elt 3)
(autoload 'mcpkit-start-service "mcpkit"
"Start or merge SERVICE in `mcpkit--active-services'.
ON-COLLISION specifies how tool name collisions are handled:
\\='namespace (default) prefixes tools with `<service-name>__'.
\\='error signals `user-error' if an un-namespaced tool name collides.

(fn NAME-OR-SERVICE &key (ON-COLLISION \\='namespace) PORT)" t)
(autoload 'mcpkit-stop-service "mcpkit"
"Stop SERVICE by removing it from `mcpkit--active-services'.
If no active services remain, close the underlying `ws-server' socket.

(fn NAME-OR-SERVICE)" t)
(autoload 'mcpkit-service-list-mode "mcpkit"
"Major mode for browsing and managing MCP services.

\\{mcpkit-service-list-mode-map}

In addition to any hooks its parent mode `tabulated-list-mode' might
have run, this mode runs the hook `mcpkit-service-list-mode-hook', as
the final or penultimate step during initialization." t)
(autoload 'mcpkit-service-list-refresh "mcpkit"
"Refresh the MCP service list buffer." t)
(autoload 'mcpkit-service-list-start-at-point "mcpkit"
"Start the MCP service at point." t)
(autoload 'mcpkit-service-list-stop-at-point "mcpkit"
"Stop the MCP service at point." t)
(autoload 'mcpkit-list-services "mcpkit"
"Display a tabulated list of registered MCP services." t)
(register-definition-prefixes "mcpkit" '("mcpkit-"))


;;; Generated autoloads from mcpkit-editing.el

(register-definition-prefixes "mcpkit-editing" '("mcpkit-editing-"))


;;; Generated autoloads from mcpkit-emacs.el

(autoload 'mcpkit-emacs-register "mcpkit-emacs"
"Ensure `mcpkit-emacs-service' is registered in `mcpkit-registry' and return it.
Kept for backward compatibility." t)
(register-definition-prefixes "mcpkit-emacs" '("mcpkit-emacs-"))


;;; Generated autoloads from mcpkit-proxy.el

(autoload 'mcpkit-proxy-register-route "mcpkit-proxy"
"Register a routing rule mapping TARGET-ID to localhost:PORT.

(fn TARGET-ID PORT)")
(autoload 'mcpkit-proxy-unregister-route "mcpkit-proxy"
"Remove the routing rule for TARGET-ID.

(fn TARGET-ID)")
(autoload 'mcpkit-proxy-handler "mcpkit-proxy"
"HTTP request handler for the mcpkit-proxy gateway.
REQUEST is a `ws-request' instance.  Resolves a target-id from the
request's URI path (primary) or `X-Sprite-ID' header (secondary, opt-in
via `mcpkit-proxy-enable-header-routing'), then reverse-proxies the
request body to the registered backend and returns its response
verbatim.  Missing routing information or an unregistered target-id
produce structured JSON-RPC error responses instead of a crash.

(fn REQUEST)")
(autoload 'mcpkit-proxy-start "mcpkit-proxy"
"Start the mcpkit-proxy HTTP gateway on PORT (default `mcpkit-proxy-port').
Reuses the same `web-server.el' machinery `mcpkit-start-service' relies
on, rather than reinventing an HTTP layer.

(fn &optional PORT)" t)
(autoload 'mcpkit-proxy-stop "mcpkit-proxy"
"Stop the mcpkit-proxy HTTP gateway, if running." t)
(register-definition-prefixes "mcpkit-proxy" '("mcpkit-proxy-"))

;;; End of scraped data

(provide 'mcpkit-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; mcpkit-autoloads.el ends here
