;;; magit-dash-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from magit-dash.el

(autoload 'magit-dash-open-registered-repo "magit-dash" "\
Prompt for a registered repository from `magit-dash-repo-list' and open it.
The picker displays repository names annotated with their paths and
cached dashboard stats." t)
(autoload 'magit-dash-clone-repo "magit-dash" "\
Clone REPO from URL (or prompt if unset) into REPO's destination path.
ON-COMPLETE is an optional callback called when cloning finishes.
Runs asynchronously and refreshes the dashboard on completion.

(fn REPO &optional URL ON-COMPLETE)" t)
(autoload 'magit-dash-clone-all-missing "magit-dash" "\
Clone all configured but missing repositories asynchronously." t)
(autoload 'magit-dash-bootstrap-repo "magit-dash" "\
Clone REPO from its configured upstream `:repo' path into its destination path.
REPO defaults to the repository at point or is selected interactively.
ON-COMPLETE is an optional callback invoked on completion.
Runs asynchronously and refreshes the dashboard on completion.

(fn &optional REPO ON-COMPLETE)" t)
(autoload 'magit-dash-bootstrap-marked "magit-dash" "\
Bootstrap marked missing repositories with an upstream `:repo' configured.
When `magit-dash--batch-all' is enabled, targets all visible missing
repositories with `:repo'.
Runs asynchronously and refreshes the dashboard on completion." t)
(autoload 'magit-dash-sync-repo "magit-dash" "\
Select a repository interactively and run its configured auto-sync operations." t)
(autoload 'magit-dash-drop-stashes "magit-dash" "\
Drop all stashes in a repository.
Uses the repository at point when called from a `magit-dash' buffer,
otherwise the git repository containing the current buffer (works from any
`magit' buffer or a file/`dired' buffer inside a repo), and finally prompts
among the registered repositories when neither applies." t)
(autoload 'magit-dash-save-project-buffers "magit-dash" "\
Save all project buffers for the repository.
Prefers using projectile if `projectile-mode' and falls back to `project.el'.
Uses the repository at point when called from a `magit-dash' buffer,
otherwise the git repository containing the current buffer, and finally
prompts among the registered repositories when neither applies." t)
(defalias 'magit-dash-projectile-save-project-buffers #'magit-dash-save-project-buffers)
(autoload 'magit-dash-open-other-window "magit-dash" "\
Open the repository dashboard buffer in another window.
Signals `user-error' when `magit-dash-repo-list' is empty.")
(autoload 'magit-dash-open "magit-dash" "\
Open the repository dashboard buffer in another window.
Signals `user-error' when `magit-dash-repo-list' is empty." t)
(register-definition-prefixes "magit-dash" '("magit-dash-" "with-magit-dash"))


;;; Generated autoloads from magit-dash-gh.el

(autoload 'magit-dash-gh-prune-merged-branches "magit-dash-gh" "\
Open a menu to prune local branches whose PRs are merged or closed.

Per-repo cache (candidates + marked list) lives on the unified global cache
keyed by repository toplevel. The menu loops until you select `exit
menu'. The menu offers:

  - exit menu
  - refresh
  - prune all branches (no prompt)
  - prune all branches (with prompt)
  - mark branch for pruning
  - prune marked branches (when any are marked)
  - prune: BRANCH [marked]   (one entry per candidate)" t)
(autoload 'magit-dash-gh-prune-prefetch "magit-dash-gh" "\
Seed the in-memory closed-PR cache from disk for the current repo.
Makes no GitHub API calls; safe to call on status load.
Skips silently when caching is disabled, not in a git repo, or the
in-memory cache is already populated.")
(autoload 'magit-dash-gh-auth-switch "magit-dash-gh" "\
Switch the active `gh' CLI account.
When more than two accounts are configured, prompt to select which to
switch to via `annotated-completing-read'. Otherwise switch directly
to the other configured account." t)
(autoload 'magit-dash-gh-menu "magit-dash-gh" "\
GitHub and Magit Dash operations.

(fn)" t)
(register-definition-prefixes "magit-dash-gh" '("magit-dash-gh-"))


;;; Generated autoloads from magit-dash-gh-actions.el

(autoload 'magit-dash-gh-actions-fetch-for-pr "magit-dash-gh-actions" "\
Fetch GitHub Actions CI logs for PR-NUMBER using REPO-DIR as the working directory.
PR-NUMBER is an integer.  REPO-DIR must be a local checkout of the repository
so that `gh' can resolve the remote when listing and downloading runs.

(fn PR-NUMBER REPO-DIR)")
(autoload 'magit-dash-gh-actions-fetch "magit-dash-gh-actions" "\
Download GitHub Actions CI logs for the current branch.
When RUN-ID is non-nil, fetch that specific run without prompting.
Otherwise list recent runs and prompt for a selection.

Creates an artifact directory under plans/ containing:
  run-info.json        — full run metadata
  run-logs.ghlog       — complete step logs (opens in `magit-dash-gh-actions-log-mode')
  run-failed-logs.ghlog — failed-step logs (when `magit-dash-gh-actions-include-failed-log')
  index.json           — collection summary

(fn &optional RUN-ID)" t)
(autoload 'magit-dash-gh-workflow-run "magit-dash-gh-actions" "\
Trigger a GitHub Actions WORKFLOW run for REPO-OR-PATH on branch REF.
When WORKFLOW is nil, fetches available active workflows and prompts
if more than one exists (or selects the only one).
REPO-OR-PATH defaults to the repository at point or `default-directory'.
REF defaults to the current branch (or `main').
INPUTS is an optional alist of (KEY . VALUE) strings passed as -f KEY=VALUE.
ON-COMPLETE is called with `ok' or `error' on finish.

(fn &optional WORKFLOW REPO-OR-PATH REF INPUTS ON-COMPLETE)" t)
(defalias 'magit-gh-workflow-run #'magit-dash-gh-workflow-run)
(defalias 'magit-dash-workflow-run #'magit-dash-gh-workflow-run)
(register-definition-prefixes "magit-dash-gh-actions" '("magit-dash-gh-actions-"))


;;; Generated autoloads from magit-dash-gh-ci.el

(autoload 'magit-dash-gh-ci-open-last-run "magit-dash-gh-ci" "\
Open the URL of the most recent CI run for REPO in the browser.
Does nothing when no CI status is cached for REPO.

(fn REPO)")
(autoload 'magit-dash-ci-dispatch-fix-operation "magit-dash-gh-ci" "\
Download the latest CI run's artifacts for REPO and dispatch a fix-CI prompt.
Uses REPO's cached :ci-status when present; otherwise fetches it first via
`magit-dash-gh-ci-fetch' before proceeding, so this can be called without a
prior manual CI-status fetch.  Signals `user-error' when REPO does not have
:include-ci set, or when no CI run is found for it even after fetching.

(fn REPO)")
(register-definition-prefixes "magit-dash-gh-ci" '("magit-dash-"))


;;; Generated autoloads from magit-dash-gh-pr.el

(autoload 'magit-dash-gh-pr-fetch "magit-dash-gh-pr" "\
Download comments and review threads for PR-NUMBER (or the current branch's PR).
When PR-NUMBER is nil, auto-detects the PR for the current branch.

Creates an artifact directory under plans/ containing:
  pr-info.json            — PR metadata and review decision
  pr-review-threads.json  — all review threads with resolved status
  pr-issue-comments.json  — top-level (non-review) comments
  index.json              — collection summary with per-thread creator/last-commentor

(fn &optional PR-NUMBER)" t)
(autoload 'magit-gh-pr-dash "magit-dash-gh-pr" "\
Open the GitHub pull request dashboard buffer.
Aggregates all open PRs by default across repositories." t)
(defalias 'magit-dash-gh-pr-dashboard-open #'magit-gh-pr-dash)
(defalias 'magit-gh-prs #'magit-gh-pr-dash)
(defalias 'magit-dash-gh-pr-dash #'magit-gh-pr-dash)
(register-definition-prefixes "magit-dash-gh-pr" '("magit-dash-gh-pr-"))


;;; Generated autoloads from magit-dash-open.el

(autoload 'magit-dash-open-repo "magit-dash-open" "\
Select a repository and open its magit status buffer.

Context-aware collection:
- In a magit-status buffer: scans from the parent of the current repo and
  merges `~/' at depth 1, so sibling repos and home-level repos appear together.
- In a directory that is itself a git repo: only the repo's worktrees and
  submodules are offered (use a prefix arg to override and scan subdirs).
- Otherwise: scans subdirectories of `default-directory'.

Live magit-status buffers are always included and marked \"[open]\"; selecting
one switches to it directly without reopening it.

With a prefix argument, prompt for ROOT and scan it normally regardless of
the above context rules.

(fn &optional ROOT)" t)
(register-definition-prefixes "magit-dash-open" '("magit-dash-open-"))


;;; Generated autoloads from magit-dash-status.el

(autoload 'magit-dash-status-refresh-all "magit-dash-status" "\
Force refresh all GitHub status information for the current repository." t)
(autoload 'magit-dash-dispatch "magit-dash-status" "\
Magit Dash operations and repository tools.

(fn)" t)
(autoload 'magit-dash-status-setup "magit-dash-status" "\
Install GitHub status headers, sections, and keybindings into Magit.")
(register-definition-prefixes "magit-dash-status" '("magit-"))


;;; Generated autoloads from magit-dash-submodules.el

(register-definition-prefixes "magit-dash-submodules" '("magit-dash-bump-"))


;;; Generated autoloads from magit-dash-timer.el

(register-definition-prefixes "magit-dash-timer" '("magit-dash-"))


;;; Generated autoloads from magit-dash-worktree.el

(autoload 'magit-dash-worktree-sync-symlinks "magit-dash-worktree" "\
Enforce worktree symlinks for the worktree at PATH (default repo at point or current buffer).
If invoked on a main worktree, syncs symlinks for all linked worktrees of that repository.

(fn &optional PATH)" t)
(autoload 'magit-dash-worktree-add "magit-dash-worktree" "\
Add a new worktree for the repository at point via magit." t)
(autoload 'magit-dash-worktree-delete "magit-dash-worktree" "\
Delete the worktree at point via magit.
Signals `user-error' when the current row is not a worktree." t)
(register-definition-prefixes "magit-dash-worktree" '("magit-dash-worktree-"))

;;; End of scraped data

(provide 'magit-dash-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; magit-dash-autoloads.el ends here
