;;; annotated-completing-read-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from annotated-completing-read.el

(autoload 'annotated-completing-read "annotated-completing-read" "\
Read a candidate from completion TABLE.
TABLE maps candidates to annotations or target values.
Alignment is automatic.

TABLE can be a hash table or an alist:

- A list-form alist uses the format: =((CANDIDATE ANNOTATION) ...)=.
- A dotted alist uses the format: =((CANDIDATE . ANNOTATION) ...)=.
- A triple-form alist uses the format: =((CANDIDATE ANNOTATION . TARGET) ...)=.
- An annotation can be =nil=.

PROMPT is the minibuffer prompt.  It defaults to ='=> '=.
A trailing space is appended if it is missing.

REQUIRE-MATCH forces the user to select an existing candidate.
If nil, the minibuffer accepts arbitrary input.

CATEGORY is a symbol for the completion category.
External packages like embark or marginalia use it to determine behavior.
Common values include `file', `buffer', `command', and `symbol'.

HISTORY is a symbol representing the history list.
It defaults to `this-command'.
Use a shared symbol to share history between commands.

GROUP-NAME determines candidate grouping.
It can be a function or a static string.

GROUP-DISPLAY formats the candidate text for display.
It is a function that takes a candidate string.
This option requires GROUP-NAME.

INITIAL-INPUT is an optional string to pre-fill in the minibuffer.

SORT-FN is a function to sort candidates before display.

DEFAULT is the fallback return value.
It is returned on empty input or quit.

OR-NIL silences quit and empty input by returning nil.
This option takes effect only when DEFAULT is nil.

A table entry can supply an optional TARGET.
This TARGET is returned instead of the candidate string.
It also affects selection via DEFAULT.
It allows packages like embark to act on the target directly.

MULTIPLE allows selecting multiple candidates.  It returns an ordered
list of selections.  Press `annotated-completing-read--multi-continue' to
accept a pick and continue.  Press
`annotated-completing-read--multi-finish-now' to finish immediately.
Pressing RET accepts the current input and finishes.  DEFAULT and OR-NIL
apply to the entire session.

MIN is the minimum number of required selections.

MAX is the maximum number of allowed selections.

Reaching MAX finishes the session automatically.
These options require MULTIPLE.

(fn TABLE &key (PROMPT \"=> \") REQUIRE-MATCH CATEGORY HISTORY GROUP-NAME GROUP-DISPLAY INITIAL-INPUT SORT-FN DEFAULT OR-NIL MULTIPLE MIN MAX)")
(autoload 'annotated-completing-read-directory "annotated-completing-read" "\
Select a directory using annotated completion.
CANDIDATES is an optional list of directory paths.
If nil, candidates are gathered from the current context.
PROMPT is the minibuffer prompt.  It defaults to \"directory:\".
REQUIRE-MATCH determines whether a match is required.
MULTIPLE enables selecting multiple directories.
MIN and MAX define selection limits for multiple selections.
Annotations show directory relationships or entry counts.

(fn &optional &key CANDIDATES PROMPT REQUIRE-MATCH MULTIPLE MIN MAX)")
(autoload 'annotated-completing-read-context-from-point "annotated-completing-read" "\
Select a candidate from the current editing context.

PROMPT is the minibuffer prompt.

SEED specifies explicit candidate strings.

INITIAL-INPUT is the initial minibuffer text.

HISTORY specifies the history list.

This function returns an empty string if no candidate is chosen.

(fn &optional &key PROMPT SEED INITIAL-INPUT HISTORY)")
(autoload 'annotated-completing-read-setup-history "annotated-completing-read" "\
Enable savehist and desktop history integration for `annotated-completing-read'.")
(register-definition-prefixes "annotated-completing-read" '("annotated-completing-read-"))

;;; End of scraped data

(provide 'annotated-completing-read-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; annotated-completing-read-autoloads.el ends here
