;;; consult-gh-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from consult-gh.el

(autoload 'consult-gh-repo-view-mode "consult-gh" "\
Minor-mode for viewing GitHub repositories.

This is a minor mode.  If called interactively, toggle the
`consult-gh-repo-view mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `consult-gh-repo-view-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'consult-gh-file-view-mode "consult-gh" "\
Minor-mode for viewing GitHub files.

This is a minor mode.  If called interactively, toggle the
`consult-gh-file-view mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `consult-gh-file-view-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'consult-gh-issue-view-mode "consult-gh" "\
Minor-mode for viewing GitHub issues.

This is a minor mode.  If called interactively, toggle the
`consult-gh-issue-view mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `consult-gh-issue-view-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'consult-gh-pr-view-mode "consult-gh" "\
Minor-mode for viewing GitHub pull request.

This is a minor mode.  If called interactively, toggle the
`consult-gh-pr-view mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `consult-gh-pr-view-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'consult-gh-release-view-mode "consult-gh" "\
Minor-mode for viewing GitHub repositories.

This is a minor mode.  If called interactively, toggle the
`consult-gh-release-view mode' mode.  If the prefix argument is
positive, enable the mode, and if it is zero or negative, disable the
mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `consult-gh-release-view-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'consult-gh-workflow-view-mode "consult-gh" "\
Minor-mode for viewing GitHub workflows.

This is a minor mode.  If called interactively, toggle the
`consult-gh-workflow-view mode' mode.  If the prefix argument is
positive, enable the mode, and if it is zero or negative, disable the
mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `consult-gh-workflow-view-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'consult-gh-run-view-mode "consult-gh" "\
Minor-mode for viewing GitHub action runs.

This is a minor mode.  If called interactively, toggle the
`consult-gh-run-view mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `consult-gh-run-view-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'consult-gh-misc-view-mode "consult-gh" "\
Minor-mode for viewing miscellanous consult-gh buffers.

This is a minor mode.  If called interactively, toggle the
`consult-gh-misc-view mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `consult-gh-misc-view-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'consult-gh-topics-edit-capf-mode "consult-gh" "\
Minor-mode for completion at point in `consult-gh-topics-edit-comment-mode'.

Helps with autocompleting usernames, issue numbers, etc.

This is a minor mode.  If called interactively, toggle the
`consult-gh-topics-edit-capf mode' mode.  If the prefix argument is
positive, enable the mode, and if it is zero or negative, disable the
mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `consult-gh-topics-edit-capf-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'consult-gh-topics-edit-mode "consult-gh" "\
Minor-mode for editable consult-gh topics.

This is a minor mode.  If called interactively, toggle the
`consult-gh-topics-edit mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `consult-gh-topics-edit-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'consult-gh-commit-message-mode "consult-gh" "\
Minor-mode for editing commit messages in consult-gh.

This is a minor mode.  If called interactively, toggle the
`consult-gh-commit-message mode' mode.  If the prefix argument is
positive, enable the mode, and if it is zero or negative, disable the
mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `consult-gh-commit-message-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'consult-gh-commit-view-mode "consult-gh" "\
Minor-mode for viewing GitHub commits.

This is a minor mode.  If called interactively, toggle the
`consult-gh-commit-view mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `consult-gh-commit-view-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'consult-gh-upload-files-mode "consult-gh" "\
Minor-mode for uploading files in consult-gh.

This is a minor mode.  If called interactively, toggle the
`Consult-Gh-Upload-Files mode' mode.  If the prefix argument is
positive, enable the mode, and if it is zero or negative, disable the
mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `consult-gh-upload-files-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'consult-gh-with-host "consult-gh" "\
Run BODY after setting environment var “GH_HOST” to HOST.

(fn HOST &rest BODY)" nil t)
(autoload 'consult-gh-auth-switch "consult-gh" "\
Switch between authenticated accounts.

If the optional arguments, HOST and USER are non-nil, use them for
authenticaiton otherwise query the user to select an account.
If PROMPT is non-nil, use it as the query prompt.

(fn &optional HOST USER PROMPT)" t)
(autoload 'consult-gh-repo-list "consult-gh" "\
Interactive command to list repos of users/organizations asynchronously.

This is an interactive wrapper function around `consult-gh--async-repo-list'.
It queries the user to enter the name of a GitHub organization/username
in the minibuffer, then fetches a list of repositories for the entered
username and present them as a minibuffer completion table for selection.
The list of candidates in the completion table are dynamically updated
as the user changes the entry.

Upon selection of a candidate:
 - if NOACTION is non-nil  candidate is returned
 - if NOACTION is nil      candidate is passed to `consult-gh-repo-action'.

Additional command line arguments can be passed in the minibuffer entry
by typing `--` followed by command line arguments.
For example the user can enter the following in the minibuffer:
armindarvish -- -L 100
the async process will run the command “gh repo list armindarvish -L 100”,
which sets the limit for the maximum number of results to 100.

User selection is tracked in `consult-gh--known-orgs-list' for quick access
in the future (added to future history list) in future calls.

INITIAL is an optional arg for the initial input in the minibuffer.
(passed as INITITAL to `consult-gh--async-repo-list').

When PROMPT is non-nil, use it as the query prompt.

MIN-INPUT is passed to `consult-gh--async-repo-list'.

For more details on consult--async functionalities,
see `consult-grep' and the official manual of consult, here:
URL `https://github.com/minad/consult'.

(fn &optional INITIAL NOACTION PROMPT MIN-INPUT)" t)
(autoload 'consult-gh-search-repos "consult-gh" "\
Interactively search GitHub repositories.

This is an interactive wrapper function around
`consult-gh--async-search-repos'.  It queries the user to enter the name of
a GitHub organization/username in the minibuffer, then fetches a list
of repositories for the entered username.  The list of candidates in the
completion table are dynamically updated as the user changes the input.

Upon selection of a candidate either
 - if NOACTION is non-nil  candidate is returned
 - if NOACTION is nil      candidate is passed to `consult-gh-repo-action'

Additional commandline arguments can be passed in the minibuffer input
by typing `--` followed by command line arguments.
For example the user can enter the following in the minibuffer:
consult-gh -- -L 100
and the async process will run “gh search repos -L 100”,
which sets the limit for the maximum number of results to 100.

User selection is tracked in `consult-gh--known-orgs-list' for quick access
in the future (added to future history list) in future calls.

INITIAL is an optional arg for the initial input in the minibuffer.
(passed as INITITAL to `consult-gh--async-repo-list').

When PROMPT is non-nil, use it as the query prompt.

For more details on consult--async functionalities,
see `consult-grep' and the official manual of consult, here:
URL `https://github.com/minad/consult'.

(fn &optional INITIAL NOACTION PROMPT MIN-INPUT)" t)
(autoload 'consult-gh-user-repos "consult-gh" "\
List all repos for USER.

This includes repos of orgs of USER.  It uses
`consult-gh--get-current-user-orgs' to get all
orgs of USER.

If NOACTION is non-nil, return the candidate without running action.

(fn &optional USER NOACTION)" t)
(autoload 'consult-gh-favorite-repos "consult-gh" "\
List repositories of orgs in `consult-gh-favorite-orgs-list'.

Passes `consult-gh-favorite-orgs-list' to `consult-gh-orgs',
a useful command for quickly fetching a list of personal GitHub Repositories
or any other favorite accounts whose repositories are frequently visited." t)
(autoload 'consult-gh-repo-fork "consult-gh" "\
Interactively fork REPOS.

It runs the command “gh fork repo ...” to fork a repository
using the internal function `consult-gh--repo-fork'

If REPOS not supplied, interactively asks user to pick REPOS.

(fn &optional REPOS)" t)
(autoload 'consult-gh-repo-clone "consult-gh" "\
Interactively clone REPOS to TARGETDIR.

It runs the command “gh clone repo ...” to clone a repository
using the internal function `consult-gh--repo-clone'.

If REPOS or TARGETDIR are not supplied, interactively asks user
to pick them.

EXTRA-ARGS are passed to “git clone”.  With prefix arg, user is qeried to
edit/enter EXTRA-ARGS.

(fn &optional REPOS TARGETDIR EXTRA-ARGS)" t)
(autoload 'consult-gh-repo-delete "consult-gh" "\
Interactively delete REPO.

It runs the command “gh repo delete ...” to delete a repository
using the internal function `consult-gh--repo-delete'.

If REPOS are not supplied, interactively asks user to pick them from
`consult-gh-user-repos'.

When NOCONFIRM is non-nil, do not ask for confirmation

(fn &optional REPO NOCONFIRM)" t)
(autoload 'consult-gh-repo-rename "consult-gh" "\
Interactively rename REPO to NEW-NAME.

It runs the command “gh repo rename --repo REPO ...” to rename a
repository using the internal function `consult-gh--repo-rename'.

If REPOS are not supplied, interactively asks user to pick them from
`consult-gh-user-repos'.

When NOCONFIRM is non-nil, do not ask for confirmation

(fn &optional REPO NEW-NAME NOCONFIRM)" t)
(autoload 'consult-gh-repo-edit-settings "consult-gh" "\
Edit the REPO.

REPO must be a propertized text describing a repo similar to one
returned by `consult-gh-repo-list'.

This mimicks the same interactive repo editing from “gh repo edit” in
the terminal.
For more details refer to the manual with “gh repo edit --help”.

(fn &optional REPO)" t)
(autoload 'consult-gh-repo-edit-readme "consult-gh" "\
Edit the README of REPO.

REPO must be a propertized text describing a repo similar to one
returned by `consult-gh-repo-list'.

(fn &optional REPO)" t)
(autoload 'consult-gh-issue-list "consult-gh" "\
Interactively list issues of a GitHub repository.

This is an interactive wrapper function around `consult-gh--async-issue-list'.
With prefix ARG, first search for a repo using `consult-gh-search-repos',
then list issues of that selected repo with `consult-gh--async-issue-list'.

It queries the user to enter the full name of a GitHub repository in the
minibuffer (expected format is “OWNER/REPO”), then fetches the list of
issues of that repository and present them as a minibuffer completion
table for selection.  The list of candidates in the completion table are
dynamically updated as the user changes the minibuffer input.

Upon selection of a candidate either
 - if NOACTION is non-nil candidate is returned.
 - if NOACTION is nil     candidate is passed to `consult-gh-issue-action'.

Additional command line arguments can be passed in the minibuffer input
by typing `--` followed by command line arguments.
For example the user can enter the following in the minibuffer:
armindarvish/consult-gh -- -L 100
and the async process will run
“gh issue list --repo armindarvish/consult-gh -L 100”, which sets the limit
for the maximum number of results to 100.

User selection is tracked in `consult-gh--known-repos-list' for quick
access in the future (added to future history list) in future calls.

INITIAL is an optional arg for the initial input in the minibuffer.
(passed as INITITAL to `consult-gh--async-issue-list').

If PROMPT is non-nil, use it as the query prompt.

MIN-INPUT is passed to `consult-gh--async-issue-list'

For more details on consult--async functionalities, see `consult-grep'
and the official manual of consult, here:
URL `https://github.com/minad/consult'

(fn &optional INITIAL NOACTION PROMPT MIN-INPUT)" t)
(autoload 'consult-gh-search-issues "consult-gh" "\
Interactively search GitHub issues of REPO.

This is an interactive wrapper function around
`consult-gh--async-search-issues'.  With prefix ARG, first search for a
repo using `consult-gh-search-repos', then search issues of only that
selected repo.

It queries the user for a search term in the minibuffer, then fetches the
list of possible GitHub issue for the entered query and presents them as a
minibuffer completion table for selection.  The list of candidates in the
completion table are dynamically updated as the user changes the entry.

Upon selection of a candidate either
 - if NOACTION is non-nil  candidate is returned
 - if NOACTION is nil      candidate is passed to `consult-gh-issue-action'

Additional command line arguments can be passed in the minibuffer input
by typing `--` followed by command line arguments.
For example the user can enter the following in the minibuffer:
consult-gh -- -L 100
and the async process will run “gh search issues consult-gh -L 100”,
which sets the limit for the maximum number of results to 100.

INITIAL is an optional arg for the initial input in the minibuffer
(passed as INITITAL to `consult-gh--async-repo-list').

If PROMPT is non-nil, use it as the query prompt.

MIN-INPUT is passed to `consult-gh--async-search-issues'.

For more details on consult--async functionalities, see `consult-grep'
and the official manual of consult, here:
URL `https://github.com/minad/consult'.

(fn &optional INITIAL REPO NOACTION PROMPT MIN-INPUT)" t)
(autoload 'consult-gh-issue-create "consult-gh" "\
Create a new issue with TITLE and BODY for REPO.

This mimicks the same interactive issue creation from “gh issue create” in
the terminal.
For more details refer to the manual with “gh issue create --help”.

(fn &optional REPO TITLE BODY)" t)
(autoload 'consult-gh-issue-edit "consult-gh" "\
Edit the ISSUE.

ISSUE must be a propertized text describing an issue similar to one
returned by `consult-gh-issue-list'.

This mimicks the same interactive issue creation from “gh issue edit” in
the terminal.
For more details refer to the manual with “gh issue edit --help”.

(fn &optional ISSUE)" t)
(autoload 'consult-gh-issue-close "consult-gh" "\
Close the ISSUE with an optional REASON and/or COMMENT.

This mimicks the same function as running “gh issue close” in the terminal.
For more details refer to the manual with “gh issue close --help”.

(fn &optional ISSUE REASON COMMENT)" t)
(autoload 'consult-gh-issue-reopen "consult-gh" "\
Reopen the ISSUE with an optional COMMENT.

This mimicks the same function as running “gh issue reopen” in the terminal.
For more details refer to the manual with “gh issue reopen --help”.

(fn &optional ISSUE COMMENT)" t)
(autoload 'consult-gh-issue-pin "consult-gh" "\
Pin the ISSUE.

This mimicks the same function as running “gh issue pin” in the terminal.
For more details refer to the manual with “gh issue pin --help”.

(fn &optional ISSUE)" t)
(autoload 'consult-gh-issue-unpin "consult-gh" "\
Unpin the ISSUE.

This mimicks the same function as running “gh issue unpin” in the terminal.
For more details refer to the manual with “gh issue unpin --help”.

(fn &optional ISSUE)" t)
(autoload 'consult-gh-issue-lock "consult-gh" "\
Lock the ISSUE with and optional REASON.

This mimicks the same function as running “gh issue lock” in the terminal.
For more details refer to the manual with “gh issue lock --help”.

(fn &optional ISSUE REASON)" t)
(autoload 'consult-gh-issue-unlock "consult-gh" "\
Unlock the ISSUE.

This mimicks the same function as running “gh issue unlock” in the terminal.
For more details refer to the manual with “gh issue unlock --help”.

(fn &optional ISSUE)" t)
(autoload 'consult-gh-issue-transfer "consult-gh" "\
Transfer the ISSUE to TARGET-REPO.

This mimicks the same function as running “gh issue transfer” in the terminal.
For more details refer to the manual with “gh issue transfer --help”.

(fn &optional ISSUE TARGET-REPO)" t)
(autoload 'consult-gh-issue-delete "consult-gh" "\
Delete the ISSUE.

When the optional argument, NO-CONFIRM, is non-nil, do not ask for
confirmation.
This mimicks the same function as running “gh issue delete” in the terminal.
For more details refer to the manual with “gh issue delete --help”.

(fn &optional ISSUE NO-CONFIRM)" t)
(autoload 'consult-gh-issue-develop "consult-gh" "\
Manage linked branches for an ISSUE.

The optional argument BASE is a base branch to develop off of.
The optional argument BRANCH-REPO is the repo's full name where a branch
should be created (if not in the same repo).

This mimicks the same function as running “gh issue develop” in the terminal.
For more details refer to the manual with “gh issue develop --help”.

(fn &optional ISSUE BASE BRANCH-REPO)" t)
(autoload 'consult-gh-pr-list "consult-gh" "\
Interactively list pull requests of a GitHub repository.

This is an interactive wrapper function around `consult-gh--async-pr-list'.
With prefix ARG, first search for a repo using `consult-gh-search-repos',
then list prs of that selected repo with `consult-gh--async-pr-list'.

It queries the user to enter the full name of a GitHub repository in
the minibuffer (expected format is “OWNER/REPO”), then fetches the list
of pull requests for that repository and presents them as a minibuffer
completion table for selection.  The list of candidates in the completion
table are dynamically updated as the user changes the entry.

Upon selection of a candidate either
 - if NOACTION is non-nil candidate is returned
 - if NOACTION is nil     candidate is passed to `consult-gh-pr-action'

Additional command line arguments can be passed in the minibuffer input
by typing `--` followed by command line arguments.
For example the user can enter the following in the minibuffer:
armindarvish/consult-gh -- -L 100
and the async process will run
“gh pr list --repo armindarvish/consult-gh -L 100”,
which sets the limit for the maximum number of results to 100.

User selection is tracked in `consult-gh--known-repos-list' for quick access
in the future (added to future history list) in future calls.

INITIAL is an optional arg for the initial input in the minibuffer
(passed as INITITAL to `consult-gh--async-issue-list').

If PROMPT is non-nil, use it as the query prompt.

For more details on consult--async functionalities, see `consult-grep'
and the official manual of consult, here:
URL `https://github.com/minad/consult'.

(fn &optional INITIAL NOACTION PROMPT MIN-INPUT)" t)
(autoload 'consult-gh-search-prs "consult-gh" "\
Interactively search GitHub pull requests of REPO.

This is an interactive wrapper function around
`consult-gh--async-search-prs'.  With prefix ARG, first search for a repo
using `consult-gh-search-repos', then search prs of only that selected repo.

It queries the user for a search term in the minibuffer, then fetches
the list of possible GitHub pr candidates for the entered query
and presents them as a minibuffer completion table for selection.
The list of candidates in the completion table are dynamically updated as
the user changes the input.

Upon selection of a candidate either
 - if NOACTION is non-nil candidate is returned
 - if NOACTION is nil     candidate is passed to `consult-gh-pr-action'

Additional command line arguments can be passed in the minibuffer input
by typing `--` followed by command line arguments.
For example the user can enter the following in the minibuffer:
consult-gh -- -L 100
and the async process will run “gh search prs consult-gh -L 100”,
which sets the limit for the maximum number of results to 100.

INITIAL is an optional arg for the initial input in the minibuffer
(passed as INITITAL to `consult-gh--async-repo-list').

If PROMPT is non-nil, use it as the query prompt.

MIN-INPUT is passed to `consult-gh--async-search-prs'

For more details on consult--async functionalities, see `consult-grep'
and the official manual of consult, here:
URL `https://github.com/minad/consult'.

(fn &optional INITIAL REPO NOACTION PROMPT MIN-INPUT)" t)
(autoload 'consult-gh-pr-edit "consult-gh" "\
Edit the PR.

This mimicks the same function as running “gh pr edit” in the terminal.
For more details refer to the manual with “gh pr edit --help”.

(fn &optional PR)" t)
(autoload 'consult-gh-pr-merge "consult-gh" "\
Merge the PR.

This mimicks the same function as running “gh pr merge” in the terminal.
For more details refer to the manual with “gh pr merge --help”.

PR is a propertized string describing a pull request.  For example, PR can
be the text stored in the buffer-local variable `consult-gh--topic' in a
buffer created by `consult-gh--pr-view'.

(fn &optional PR)" t)
(autoload 'consult-gh-pr-review "consult-gh" "\
Interactively create a new review on pull request, PR.

PR is a string with properties that identify a github pull requests.
For an example, see the buffer-local variable `consult-gh--topic' in the
buffer generated by `consult-gh-pr-create'.
PR defaults to `consult-gh--topic' and if that is nil also, the user is
asked to chose it interactively.

(fn &optional PR)" '(consult-gh-pr-view-mode))
(autoload 'consult-gh-pr-close "consult-gh" "\
Close the PR with an optional COMMENT.

If the optional argument DELETE-BRANCH is non-nil, deletes
the local and remote branch after close.

This mimicks the same function as running “gh pr close” in the terminal.
For more details refer to the manual with “gh pr close --help”.

(fn &optional PR COMMENT DELETE-BRANCH)" t)
(autoload 'consult-gh-pr-reopen "consult-gh" "\
Reopen the PR with an optional COMMENT.

This mimicks the same function as running “gh pr reopen” in the terminal.
For more details refer to the manual with “gh pr reopen --help”.

(fn &optional PR COMMENT)" t)
(autoload 'consult-gh-pr-lock "consult-gh" "\
Lock the PR with and optional REASON.

This mimicks the same function as running “gh pr lock” in the terminal.
For more details refer to the manual with “gh pr lock --help”.

(fn &optional PR REASON)" t)
(autoload 'consult-gh-pr-unlock "consult-gh" "\
Unlock the PR.

This mimicks the same function as running “gh pr unlock” in the terminal.
For more details refer to the manual with “gh pr unlock --help”.

(fn &optional PR)" t)
(autoload 'consult-gh-pr-mark-ready "consult-gh" "\
Mark the PR as ready for review.

This mimicks the same function as running “gh pr ready” in the terminal.
For more details refer to the manual with “gh pr ready --help”.

(fn &optional PR)" t)
(autoload 'consult-gh-pr-mark-draft "consult-gh" "\
Mark the PR as draft.

This mimicks the same function as running “gh pr ready” with the switch
“--undo” in the terminal.  For more details refer to the manual with
“gh pr ready --help”.

(fn &optional PR)" t)
(autoload 'consult-gh-search-code "consult-gh" "\
Interactively search GitHub codes.

This is an interactive wrapper function around
`consult-gh--async-search-code'.  With prefix ARG, first search for a repo
using `consult-gh-search-repos', then search for code only on that
selected repo.

If REPO is non-nil search for code in REPO.

It queries the user for a search term in the minibuffer, then fetches
the list of possible GitHub code candidates for the entered query and
presents them as a minibuffer completion table for selection.
The list of candidates in the completion table are dynamically updated
as the user changes the input.

Upon selection of a candidate either
 - if NOACTION is non-nil candidate is returned
 - if NOACTION is nil     candidate is passed to `consult-gh-pr-action'

Additional command line arguments can be passed in the minibuffer input
by typing `--` followed by command line arguments.
For example the user can enter the following in the minibuffer:
react -- -L 100
and the async process will run “gh search code react -L 100”,
which sets the limit for the maximum number of results to 100.

INITIAL is an optional arg for the initial input in the minibuffer
(passed as INITITAL to `consult-gh--async-search-code').

If PROMPT is non-nil, use it as the query prompt.

For more details on consult--async functionalities, see `consult-grep'
and the official manual of consult, here:
URL `https://github.com/minad/consult'.

(fn &optional INITIAL REPO NOACTION PROMPT MIN-INPUT)" t)
(autoload 'consult-gh-find-file "consult-gh" "\
Interactively find files of REPO in REF.

Query the user for name of a REPO, expected format is “OWNER/REPO”
(e.g., armindarvish/consult-gh), and a REF in REPO.  Then presents
the file contents of the REPO and REF for selection.

Upon selection of a candidate either
 - if NOACTION is non-nil candidate is returned
 - if NOACTION is nil     candidate is passed to `consult-gh-file-action'

Description of Arguments:
  REPO          a string; repository's full name
                (e.g., armindarvish/consult-gh)
  REF           a string; branch name, tag name or commit sha
  PATH          a string; when non-nil search is done relative to PATH
  INITIAL       a string; used as initial input in searching files
                (gets passed to `consult--read').
  NOACTION      a boolean; if non-nil, only retrun the file object
                and do not call `consult-gh-file-action'.

(fn &optional REPO REF PATH NOACTION INITIAL)" t)
(autoload 'consult-gh-edit-file "consult-gh" "\
Edit FILE and commit to GitHub.

FILE must be a string with properties describing a file similar to the
local variable `consult-gh--topic' in  a buffer created by
`consult-gh-find-file'.

When COMMIT-BUFFER is non-nil, use it for commiting the edits.

(fn &optional FILE COMMIT-BUFFER)" t)
(autoload 'consult-gh-push-file "consult-gh" "\
Make a commit to push FILE change to GitHub." '(consult-gh-file-view-mode))
(autoload 'consult-gh-create-file "consult-gh" "\
Create FILE.

Create a new buffer to edit file.  When the buffer is saved, the user
is asked if they want to push the file to GitHub.

FILE is a string with properties that describe repo, ref,
and path of file.  For example see the buffer-local-variable
`consult-gh--topic' in a buffer created by `consult-gh-file-view'.

If CONTENT is non-nil insert it in the file buffer.

(fn &optional FILE CONTENT)" t)
(autoload 'consult-gh-delete-file "consult-gh" "\
Delete FILE.

FILE is a string with properties that describes repo, ref, and the
path of each file to delete.  For example see the buffer-local-variable
`consult-gh--topic' in a buffer created by
`consult-gh-file-view'.

(fn &optional FILE)" t)
(autoload 'consult-gh-upload-files "consult-gh" "\
Upload FILES to github.

TOPIC is a string with properties that describes repo, ref,
and the path for uploading files.  For example see the
buffer-local-variable `consult-gh--topic' in a buffer created by
`consult-gh-file-view'.

(fn &optional FILES TOPIC)" t)
(autoload 'consult-gh-rename-file "consult-gh" "\
Rename FILE.

FILE is a string with properties that describes repo, ref, and the
path of the file to delete.  For example see the buffer-local-variable
`consult-gh--topic' in a buffer created by
`consult-gh-file-view'.

(fn &optional FILE)" t)
(autoload 'consult-gh-save-file "consult-gh" "\
Interactively  save FILE in TARGETDIR.

Description of Arguments:
  FILE       a string with properties; the file to save
             for example see the local variable `consult-gh--topic'
             in  a buffer created by `consult-gh-find-file'.
  TARGETDIR  a string; the path of the folder where the files should
             be saved in.

(fn &optional FILE TARGETDIR)" t)
(autoload 'consult-gh-notifications "consult-gh" "\
Search GitHub for User's work on GitHub.

This is an interactive wrapper function around
`consult-gh--dashboard'.

Upon selection of a candidate either
 - if NOACTION is non-nil  candidate is returned
 - if NOACTION is nil      candidate is passed to `consult-gh-issue-action'

INITIAL is an optional arg for the initial input in the minibuffer.

If PROMPT is non-nil, use it as the query prompt.

(fn &optional INITIAL NOACTION PROMPT)" t)
(autoload 'consult-gh-dashboard "consult-gh" "\
Search GitHub for current user's work.

This is an interactive wrapper function around `consult-gh--dashboard'.

Upon selection of a candidate either
 - if NOACTION is non-nil  candidate is returned
 - if NOACTION is nil      candidate is passed to
                           `consult-gh-dashboard-action'

INITIAL is an optional arg for the initial input in the minibuffer.

If PROMPT is non-nil, use it as the query prompt.

This command runs `consult--multi' with sources listed in
`consult-gh-dashboard-items-sources' to find all the relevant (e.g.
assigned, authored, mentions, involves, ...) issues and
pull requests to the current user (i.e.
`consult-gh--get-current-username').  `consult-gh-dashboard-items-sources'
can be customized to add more sources (i.e. define other searches as
relevant).

Furthermore, additional commandline arguments can be passed in the
minibuffer input by typing “--” followed by command line arguments.
For example the user can enter the following in the minibuffer:

consult-gh -- -L 5

and the async process for each source in
`consult-gh-dashboard-items-sources' will take the extra argument (e.g.
will run “gh search issues --author @me consult-gh -L 5”), which searches
the issues for the term “consult-gh” and sets the limit for the maximum
number of results to 5.

For more details on consult--async functionalities, see `consult-grep' and
the official manual of consult, here:
URL `https://github.com/minad/consult'.

(fn &optional INITIAL NOACTION PROMPT)" t)
(autoload 'consult-gh-release-list "consult-gh" "\
Interactively list issues of a GitHub repository.

This is an interactive wrapper function around `consult-gh--release-issue-list'.
With prefix ARG, first search for a repo using `consult-gh-search-repos',
then list issues of that selected repo with `consult-gh--async-release-list'.

It queries the user to enter the full name of a GitHub repository in the
minibuffer (expected format is “OWNER/REPO”), then fetches the list of
releases of that repository and present them as a minibuffer completion
table for selection.  The list of candidates in the completion table are
dynamically updated as the user changes the minibuffer input.

Upon selection of a candidate either
 - if NOACTION is non-nil candidate is returned.
 - if NOACTION is nil     candidate is passed to
   `consult-gh-release-action'.

Additional command line arguments can be passed in the minibuffer input
by typing `--` followed by command line arguments.
For example the user can enter the following in the minibuffer:
armindarvish/consult-gh -- -L 100
and the async process will run
“gh release list --repo armindarvish/consult-gh -L 100”, which sets the limit
for the maximum number of results to 100.

User selection is tracked in `consult-gh--known-repos-list' for quick
access in the future (added to future history list) in future calls.

INITIAL is an optional arg for the initial input in the minibuffer.
(passed as INITITAL to `consult-gh--async-release-list').

If PROMPT is non-nil, use it as the query prompt.

MIN-INPUT is passed to `consult-gh--async-release-list'

For more details on consult--async functionalities, see `consult-grep'
and the official manual of consult, here:
URL `https://github.com/minad/consult'

(fn &optional INITIAL NOACTION PROMPT MIN-INPUT)" t)
(autoload 'consult-gh-release-create "consult-gh" "\
Create a new release with TAGNAME, TITLE, and BODY for REPO.

TARGET is the branch to target for release
This mimicks the same interactive issue creation from “gh release create” in
the terminal.
For more details refer to the manual with “gh release create --help”.

(fn &optional REPO TAGNAME TITLE BODY TARGET)" t)
(autoload 'consult-gh-release-delete "consult-gh" "\
Interactively delete RELEASE of REPO.

It runs the command “gh release delete ...” to delete a release
using the internal function `consult-gh--release-delete'.

When NOCONFIRM is non-nil, do not ask for confirmation

(fn &optional REPO RELEASE NOCONFIRM)" t)
(autoload 'consult-gh-release-edit "consult-gh" "\
Edit the RELEASE.

This mimicks the same function as running “gh release edit” in the terminal.
For more details refer to the manual with “gh release edit --help”.

(fn &optional RELEASE)" t)
(autoload 'consult-gh-release-mark-draft "consult-gh" "\
Mark RELEASE as draft.

(fn &optional RELEASE)" t)
(autoload 'consult-gh-release-toggle-prerelease "consult-gh" "\
(Un)mark RELEASE as pre-release.

(fn &optional RELEASE)" t)
(autoload 'consult-gh-release-mark-latest "consult-gh" "\
Mark RELEASE as latest.

(fn &optional RELEASE)" t)
(autoload 'consult-gh-release-publish "consult-gh" "\
Publish RELEASE.

(fn &optional RELEASE)" t)
(autoload 'consult-gh-release-download "consult-gh" "\
Download the release with TAGNAME from REPO.

This mimicks the same function as running
“gh release download TGNAME --repo REPO” in the terminal.

For more details refer to the manual with “gh release download --help”.

(fn &optional REPO TAGNAME)" t)
(autoload 'consult-gh-workflow-list "consult-gh" "\
Interactively list workflow actions of a GitHub repository.

This is an interactive wrapper function around
`consult-gh--async-workflow-list'.  With prefix ARG, first
search for a repo using `consult-gh-search-repos', then list workflows
of that selected repo with `consult-gh--async-workflow-list'.

It queries the user to enter the full name of a GitHub repository in the
minibuffer (expected format is “OWNER/REPO”), then fetches the list of
workflows of that repository and present them as a minibuffer completion
table for selection.  The list of candidates in the completion table are
dynamically updated as the user changes the minibuffer input.

Upon selection of a candidate either
 - if NOACTION is non-nil candidate is returned.
 - if NOACTION is nil     candidate is passed to
   `consult-gh-workflow-action'.

Additional command line arguments can be passed in the minibuffer input
by typing `--` followed by command line arguments.
For example the user can enter the following in the minibuffer:
armindarvish/consult-gh -- -L 100
and the async process will run
“gh workflow list --repo armindarvish/consult-gh -L 100”, which sets the limit
for the maximum number of results to 100.

User selection is tracked in `consult-gh--known-repos-list' for quick
access in the future (added to future history list) in future calls.

INITIAL is an optional arg for the initial input in the minibuffer.
(passed as INITITAL to `consult-gh--async-workflow-list').

If PROMPT is non-nil, use it as the query prompt.

MIN-INPUT is passed to `consult-gh--async-workflow-list'

For more details on consult--async functionalities, see `consult-grep'
and the official manual of consult, here:
URL `https://github.com/minad/consult'

(fn &optional INITIAL NOACTION PROMPT MIN-INPUT)" t)
(autoload 'consult-gh-workflow-change-yaml-ref "consult-gh" "\
Show the yaml file of workflow from a different ref.

can be used in `consult-gh-workflow-view-mode' to see the yaml file
of a GitHub action from a different branc or tagname." '(consult-gh-workflow-view-mode))
(autoload 'consult-gh-workflow-enable "consult-gh" "\
Enable a WORKFLOW.

WORKFLOW must be a propertized text describing a workflow similar to one
returned by `consult-gh-workflow-list'.

(fn &optional WORKFLOW)" t)
(autoload 'consult-gh-workflow-disable "consult-gh" "\
Disable a WORKFLOW.

WORKFLOW must be a propertized text describing a workflow similar to one
returned by `consult-gh-workflow-list'.

(fn &optional WORKFLOW)" t)
(autoload 'consult-gh-workflow-run "consult-gh" "\
Run a WORKFLOW in REF.

WORKFLOW must be a propertized text describing a workflow similar to
one returned by `consult-gh-workflow-list'.  REF is the branch or
tagname that contains the version of WORKFLOW to run.

(fn &optional WORKFLOW REF)" t)
(autoload 'consult-gh-workflow-edit-yaml "consult-gh" "\
Edit the yaml file of a WORKFLOW in REF.

WORKFLOW must be a propertized text describing a workflow similar to
one returned by `consult-gh-workflow-list'.  REF is the branch,
tagname or commit sha that contains the version of WORKFLOW to edit.

(fn &optional WORKFLOW REF)" t)
(autoload 'consult-gh-workflow-create "consult-gh" "\
Create a new workflow in REPO and BRANCH.

(fn &optional REPO BRANCH)" t)
(autoload 'consult-gh-workflow-edit "consult-gh" "\
Edit the WORKFLOW.

WORKFLOW must be a propertized text describing a workflow similar to
one returned by `consult-gh-workflow-list'.  REF is the branch,
tagname or commit sha that contains the version of WORKFLOW to edit.

(fn &optional WORKFLOW)" t)
(autoload 'consult-gh-run-list "consult-gh" "\
Interactively list action run instances of a GitHub repository.

This is an interactive wrapper function around `consult-gh--async-run-list'.
With prefix ARG, first search for a repo using `consult-gh-search-repos',
then list runs of that selected repo with `consult-gh--async-run-list'.

It queries the user to enter the full name of a GitHub repository in the
minibuffer (expected format is “OWNER/REPO”), then fetches the list of
action runs of that repository and present them as a minibuffer completion
table for selection.  The list of candidates in the completion table are
dynamically updated as the user changes the minibuffer input.

Upon selection of a candidate either
 - if NOACTION is non-nil candidate is returned.
 - if NOACTION is nil     candidate is passed to
   `consult-gh-run-action'.

Additional command line arguments can be passed in the minibuffer input
by typing `--` followed by command line arguments.
For example the user can enter the following in the minibuffer:
armindarvish/consult-gh -- -L 100
and the async process will run
“gh run list --repo armindarvish/consult-gh -L 100”, which sets the limit
for the maximum number of results to 100.

User selection is tracked in `consult-gh--known-repos-list' for quick
access in the future (added to future history list) in future calls.

INITIAL is an optional arg for the initial input in the minibuffer.
(passed as INITITAL to `consult-gh--async-run-list').

If PROMPT is non-nil, use it as the query prompt.

MIN-INPUT is passed to `consult-gh--async-run-list'

For more details on consult--async functionalities, see `consult-grep'
and the official manual of consult, here:
URL `https://github.com/minad/consult'

(fn &optional INITIAL NOACTION PROMPT MIN-INPUT WORKFLOW)" t)
(autoload 'consult-gh-run-view "consult-gh" "\
View run with RUN-ID of WORKFLOW in REPO in an Emacs buffer.

(fn &optional REPO RUN-ID WORKFLOW)" t)
(autoload 'consult-gh-run-rerun "consult-gh" "\
Rerun RUN.

RUN is a string with properties that identifies a run.  For an
example, see the buffer-local variable `consult-gh--topic' in the
buffer generated by `consult-gh--run-view'.  RUN defaults to
`consult-gh--topic', and if that is nil or not from a run, then the
user is asked to chose a run interactively.

If JOB-ID is non-nil, rerun the specific job with JOB-ID.

(fn &optional RUN JOB-ID)" t)
(autoload 'consult-gh-branch-create "consult-gh" "\
Create a new branch in REPO.

REF is the reference for creating a new branch.
BRANCH-NAME is the name of the new branch.
If SYNC is non-nil, process is run synchronously.

This is wrapper around `consult-gh--branch-create'.

(fn &optional REPO REF BRANCH-NAME SYNC)" t)
(autoload 'consult-gh-branch-delete "consult-gh" "\
Delete a BRANCH in REPO.

BRANCH is the name of branch to delete.
If SYNC is non-nil, process is run synchronously.

This is wrapper around `consult-gh--branch-delete'.

(fn &optional REPO BRANCH SYNC)" t)
(autoload 'consult-gh-topics-comment-create "consult-gh" "\
Interactively create a new comment on TOPIC.

TOPIC is a string with properties that identify a topic to comment on.
For and example, see the buffer-local variable `consult-gh--topic' in the
buffer generated by `consult-gh--pr-view' or `consult-gh--issue-view'.
TOPIC defaults to `consult-gh--topic', and if that is also nil,
then the user is asked to chose the TOPIC interactively.

(fn &optional TOPIC)" t)
(autoload 'consult-gh-topics-cancel "consult-gh" "\
Cancel the current topic or comment." '(consult-gh-topics-edit-mode))
(autoload 'consult-gh-topics-submit "consult-gh" "\
Submit TOPIC.

TOPIC is a string with properties that identify a consult-gh topic such as
a comment, issue, pull request, pull request review, etc.
For an example, see the buffer-local variable `consult-gh--topic' in the
buffer generated by commands such as `consult-gh-pr-create',
`consult-gh-issue-create', `consult-gh--pr-view', `consult-gh--issue-view',
`consult-gh-pr-review', or `consult-gh-topics-comment-create'.
TOPIC defaults to `consult-gh--topic', and if that is also nil,
then the user is asked to chose the TOPIC interactively.

(fn &optional TOPIC)" '(consult-gh-topics-edit-mode))
(autoload 'consult-gh-topics-open-in-browser "consult-gh" "\
Open the TOPIC of the current buffer in the browser.

TOPIC is a text with properties that identify a consult-gh topic such as
a comment, issue, pull request, pull request review, etc.
For an example, see the buffer-local variable `consult-gh--topic' in the
buffer generated by commands such as `consult-gh-pr-create',
`consult-gh-issue-create' `consult-gh--pr-view', `consult-gh--issue-view',
`consult-gh-pr-review', or `consult-gh-topics-comment-create'.
TOPIC defaults to `consult-gh--topic'.

This function uses `consult-gh-browse-url-func' for opening a url in the
browser.

(fn &optional TOPIC)" '(consult-gh-pr-view-mode consult-gh-issue-view-mode consult-gh-workflow-view-mode consult-gh-commit-view-mode consult-gh-misc-view-mode))
(autoload 'consult-gh-commit-save-message "consult-gh" "\
Save COMMIT-MESSAGE to `log-edit-comment-ring'.

COMMIT-MESSAGE defaults to
`consult-gh--commit-get-buffer-message'.

Adapted from magit:
URL `https://github.com/magit/magit/blob/731642756f504c8a56d3775960b7af0a93c618bb/lisp/git-commit.el#L796'

(fn &optional COMMIT-MESSAGE)" '(consult-gh-commit-message-mode))
(autoload 'consult-gh-commit-prev-message "consult-gh" "\
Cycle backward through message history, after saving current message.
With a numeric prefix ARG, go back ARG messages.

Adapted from magit:
URL `https://github.com/magit/magit/blob/731642756f504c8a56d3775960b7af0a93c618bb/lisp/git-commit.el#L740'

(fn ARG)" '(consult-gh-commit-message-mode))
(autoload 'consult-gh-commit-next-message "consult-gh" "\
Cycle forward through message history, after saving current message.
With a numeric prefix ARG, go forward ARG messages.

Adapted from magit:
URL `
https://github.com/magit/magit/blob/731642756f504c8a56d3775960b7af0a93c618bb/lisp/git-commit.el#L768'

(fn ARG)" '(consult-gh-commit-message-mode))
(autoload 'consult-gh-commit-view-diff "consult-gh" "\
View diff for COMMIT.

When NOSELECT is non-nil, do not switch to buffer
COMMIT is a string with properties that identify a commit.
For an example see the buffer-local variable `consult-gh--topic' in the
buffer generated by `consult-gh--commit-create'.

(fn &optional COMMIT NOSELECT)" '(consult-gh-commit-message-mode))
(autoload 'consult-gh-commit-list "consult-gh" "\
Interactively list GitHub commits of REPO and REF.

REF is name of a branch or tag in REPO.
This is an interactive wrapper function around
`consult-gh--commit-list'.

It queries the user to select a commit from list of commits for
REPO and REF.

Upon selection of a candidate either
 - if NOACTION is non-nil  candidate is returned
 - if NOACTION is nil      candidate is passed to `consult-gh-commit-action'

INITIAL is an optional arg for the initial input in the minibuffer
(passed as INITITAL to `consult-gh---commit-list').

If PROMPT is non-nil, use it as the query prompt.

(fn &optional REPO REF INITIAL NOACTION PROMPT)" t)
(autoload 'consult-gh-search-commits "consult-gh" "\
Interactively search GitHub commits of REPO.

This is an interactive wrapper function around
`consult-gh--async-search-commits'.

It queries the user for a search term in the minibuffer, then fetches the
list of possible GitHub commits for the entered query and presents them as a
minibuffer completion table for selection.  The list of candidates in the
completion table are dynamically updated as the user changes the entry.

Upon selection of a candidate either
 - if NOACTION is non-nil  candidate is returned
 - if NOACTION is nil      candidate is passed to `consult-gh-commit-action'

Additional command line arguments can be passed in the minibuffer input
by typing `--` followed by command line arguments.
For example the user can enter the following in the minibuffer:
consult-gh -- -L 100
and the async process will run “gh search commits bug fix --repo REPO -L 100”,
which sets the limit for the maximum number of results to 100.

INITIAL is an optional arg for the initial input in the minibuffer
(passed as INITITAL to `consult-gh--async-search-commits').

If PROMPT is non-nil, use it as the query prompt.

MIN-INPUT is passed to `consult-gh--async-search-commits'.

For more details on consult--async functionalities, see `consult-grep'
and the official manual of consult, here:
URL `https://github.com/minad/consult'.

(fn &optional REPO INITIAL NOACTION PROMPT MIN-INPUT)" t)
(autoload 'consult-gh-commit-view-comments "consult-gh" "\
Insert comments on COMMIT in the current buffer.

(fn &optional COMMIT)" '(consult-gh-commit-view-mode))
(autoload 'consult-gh-commit-browse-files "consult-gh" "\
Browse files in REPO at sommit SHA.

Description of Arguments:
  REPO          a string; repository's full name
                (e.g., armindarvish/consult-gh)
  SHA           a string; commit sha
  PATH          a string; when non-nil search is done relative to PATH
  INITIAL       a string; used as initial input in searching files
                (gets passed to `consult--read').
  NOACTION      a boolean; if non-nil, only retrun the file object
                and do not call `consult-gh-file-action'.

(fn &optional REPO SHA PATH NOACTION INITIAL)" t)
(autoload 'consult-gh-ctrl-c-ctrl-c "consult-gh" "\
Submit topic or invoke `org-ctrl-c-ctrl-c' in `org-mode'." t)
(autoload 'consult-gh-enable-default-keybindings "consult-gh" "\
Enable default keybindings for all minor modes in consult-gh." t)
(autoload 'consult-gh-disable-default-keybindings "consult-gh" "\
Disable default keybindings for minor modes in consult-gh." t)
(autoload 'consult-gh-kill-preview-buffers "consult-gh" "\
Kill all open preview buffers stored in `consult-gh--preview-buffers-list'.

It asks for confirmation if the buffer is modified
and removes the buffers that are killed from the list." t)
(autoload 'consult-gh-kill-open-file-buffers "consult-gh" "\
Kill all open file buffers stored in `consult-gh--open-files-buffers'.

It asks for confirmation if the buffer is modified
and removes the buffers that are killed from the list." t)
(autoload 'consult-gh-refresh-view "consult-gh" "\
Refresh the buffer viewing a consult-gh topic." '(consult-gh-repo-view-mode consult-gh-issue-view-mode consult-gh-pr-view-mode consult-gh-release-view-mode consult-gh-workflow-view-mode consult-gh-run-view-mode consult-gh-file-view-mode consult-gh-misc-view-mode))
(autoload 'consult-gh "consult-gh" "\
Convinient wrapper function for favorite interactive command.

Calls the function in `consult-gh-default-interactive-command'
and passes ARGS to it.

(fn &rest ARGS)" t)
(autoload 'consult-gh-dired "consult-gh" "\
Open consult-gh REPO contents in REF at PATH in a dired-like BUFFER.

Description of Arguments:

  REPO      a string; full name of a repository.
  PATH      a string; path of file in repo to copy.
  REF       a string; the name of a branch or tag in REPO.
  BUFFER    a buffer; the bufffer to open contents in.
  NO-SELECT a boolean; when non-nil do not switch to buffer.
  REVERT    a boolean; when non-nil pull the data from GitHub.

(fn &optional REPO PATH REF BUFFER NO-SELECT REVERT)" t)
(register-definition-prefixes "consult-gh" '("consult-gh-"))


;;; Generated autoloads from consult-gh-transient.el

(register-definition-prefixes "consult-gh-transient" '("consult-gh-transient-read-variable"))

;;; End of scraped data

(provide 'consult-gh-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; consult-gh-autoloads.el ends here
