;;; magit-gh-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from magit-gh.el

 (autoload 'magit-gh "magit-gh" nil t)
(register-definition-prefixes "magit-gh" '("magit-gh-"))


;;; Generated autoloads from magit-gh-repo.el

(autoload 'magit-gh-repo-view "magit-gh-repo" "\
Show information about a GitHub repository in a dedicated buffer.
With a prefix argument, prompt for a [OWNER/]REPO TARGET; otherwise
show the current repository.

(fn &optional TARGET)" t)
(autoload 'magit-gh-repo-browse "magit-gh-repo" "\
Open a GitHub repository in the browser.
With a prefix argument, prompt for a [OWNER/]REPO TARGET; otherwise
open the current repository.

(fn &optional TARGET)" t)
 (autoload 'magit-gh-repo-list "magit-gh-repo" nil t)
 (autoload 'magit-gh-repo-fork "magit-gh-repo" nil t)
 (autoload 'magit-gh-repo-create "magit-gh-repo" nil t)
(autoload 'magit-gh-repo-sync "magit-gh-repo" "\
Sync a repository with its upstream using `gh repo sync'.
Prompts to choose between two distinct operations:

  - Sync local clone from upstream: fast-forward the local clone's
    default branch from its parent.  Touches nothing on GitHub.

  - Sync remote fork on GitHub: update the fork's default branch on
    GitHub from its parent via the API.  Requires push access (and,
    for upstream workflow changes, the `workflow' token scope)." t)
(register-definition-prefixes "magit-gh-repo" '("magit-gh-"))


;;; Generated autoloads from magit-gh-utils.el

(register-definition-prefixes "magit-gh-utils" '("magit-gh--"))

;;; End of scraped data

(provide 'magit-gh-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; magit-gh-autoloads.el ends here
