;;; denote-convert-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from denote-convert.el

(autoload 'denote-convert-file-prompt "denote-convert"
"Prompt for a Denote note file with completion.
PROMPT defaults to \"Convert note: \".  DEFAULT-FILE pre-selects a candidate.

(fn &optional PROMPT DEFAULT-FILE)")
(autoload 'denote-convert-import-from-datetree "denote-convert"
"Import org datetree entries from FILE as individual Denote notes.
With optional FROM-DATE and TO-DATE (YYYY-MM-DD strings), restricts
import to that inclusive date range.  Interactively, prompts for the
file and whether to apply a date restriction.

(fn FILE &optional FROM-DATE TO-DATE)" t)
(autoload 'denote-convert-file-type "denote-convert"
"Migrate FILE's front matter and extension to NEW-FILE-TYPE.
Rewrites only the front matter block (title, keywords, signature,
identifier, date) in NEW-FILE-TYPE's syntax and renames the file to
match NEW-FILE-TYPE's extension.  The note body is left untouched.

(fn FILE NEW-FILE-TYPE)" t)
(register-definition-prefixes "denote-convert" '("denote-convert-"))

;;; End of scraped data

(provide 'denote-convert-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; denote-convert-autoloads.el ends here
