;;; agent-shell-notifications-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from agent-shell-notifications.el

(autoload 'agent-shell-notifications-mode "agent-shell-notifications" "\
Toggle libnotify notifications for the current agent-shell buffer.

This is a minor mode.  If called interactively, toggle the
`Agent-Shell-Notifications mode' mode.  If the prefix argument is
positive, enable the mode, and if it is zero or negative, disable the
mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `agent-shell-notifications-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'agent-shell-notifications-viewport-edit-mode "agent-shell-notifications" "\
Toggle notifications hooks for an agent-shell viewport edit buffer.

Add to `agent-shell-viewport-edit-mode-hook' to cancel idle timers and
close notifications when the viewport edit window is selected.

This is a minor mode.  If called interactively, toggle the
`Agent-Shell-Notifications-Viewport-Edit mode' mode.  If the prefix
argument is positive, enable the mode, and if it is zero or negative,
disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `agent-shell-notifications-viewport-edit-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'agent-shell-notifications-viewport-view-mode "agent-shell-notifications" "\
Toggle notifications hooks for an agent-shell viewport view buffer.

Add to `agent-shell-viewport-view-mode-hook' to cancel idle timers and
close notifications when the viewport view window is selected or a reply is sent.

This is a minor mode.  If called interactively, toggle the
`Agent-Shell-Notifications-Viewport-View mode' mode.  If the prefix
argument is positive, enable the mode, and if it is zero or negative,
disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `agent-shell-notifications-viewport-view-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'agent-shell-notifications-set-provider "agent-shell-notifications" "\
Load PROVIDER and validate that it sets the required functions.
PROVIDER is a symbol naming the feature to require.  The feature
must set `agent-shell-notifications-send-function' and
`agent-shell-notifications-close-function'.  When PROVIDER is nil,
skips loading and validation (the functions must be set manually).
Interactively, reads a provider symbol from the minibuffer.

(fn PROVIDER)" t)
(register-definition-prefixes "agent-shell-notifications" '("agent-shell-notifications-"))


;;; Generated autoloads from agent-shell-notifications-knockknock.el

(register-definition-prefixes "agent-shell-notifications-knockknock" '("agent-shell-notifications--"))


;;; Generated autoloads from agent-shell-notifications-libnotify.el

(register-definition-prefixes "agent-shell-notifications-libnotify" '("agent-shell-notifications--"))

;;; End of scraped data

(provide 'agent-shell-notifications-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; agent-shell-notifications-autoloads.el ends here
