;;; elpaish-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from elpaish.el

(autoload 'elpaish-register-package "elpaish" "\
Register package NAME with REPOSITORY-PATH (local directory or Git URL).
BRANCH defaults to `elpaish-default-branch' and FILES to \\='(\"*.el\").
SOURCE-DIRECTORY-PATH (or SOURCE-DIR) is the subdirectory within
REPOSITORY-PATH holding the package (default \".\"), for monorepos or
nested folders.
TEST-DIRECTORY-PATH (or TEST-DIR) is an optional custom test directory path.
EXCLUDE-FILES (or EXCLUDE) is an optional list of file patterns to exclude.
PREFLIGHT-SKIP is t (or \\='t) to skip all checks, or a list of check
symbols to bypass during preflight.
DISABLED-STREAMS (or SUPPRESS-STREAMS) is a list of suppressed stream symbols.
DOC (or DOCS-URL) is an optional URL or path to documentation.
SUMMARY, URL, KEYWORDS, and REQUIRES provide package metadata.

(fn NAME REPOSITORY-PATH &key BRANCH (FILES \\='(\"*.el\")) EXCLUDE-FILES EXCLUDE SOURCE-DIRECTORY-PATH TEST-DIRECTORY-PATH SOURCE-DIR TEST-DIR PREFLIGHT-SKIP EXTERNAL EXTERNAL-P SUMMARY URL DOC KEYWORDS REQUIRES DISABLED-STREAMS SUPPRESS-STREAMS DOCS-URL &allow-other-keys)")
(autoload 'elpaish-dependency-valid-p "elpaish" "\
Return non-nil if package dependency DEP is builtin, in MELPA, or in `elpaish-registry'.

(fn DEP)")
(autoload 'elpaish-check-recipe-dependencies "elpaish" "\
Check that all dependencies of RECIPE are builtin, in MELPA, in ELPAish, or self-provided.
Returns a list of invalid dependency symbols if any are invalid, or nil if all are valid.

(fn RECIPE)")
(autoload 'elpaish-validate-all-dependencies "elpaish" "\
Validate that all dependencies of all registered packages are builtin, in MELPA, or in ELPAish.
Returns an alist of (package . invalid-deps) for any packages with invalid dependencies." t)
(autoload 'elpaish-sign-file-headless "elpaish" "\
Sign FILE headlessly generating detached signature for KEY-ID.
Passphrase is provided non-interactively via PASSPHRASE argument,
`elpaish-gpg-passphrase', or `ELPAISH_GPG_PASSPHRASE' environment variable.
Never triggers interactive terminal or GUI pinentry dialogs.
OUTPUT-FILE defaults to FILE.sig.  Return the signature path, or nil.

(fn FILE &key KEY-ID PASSPHRASE OUTPUT-FILE)")
(autoload 'elpaish-init-signing-from-env "elpaish" "\
Initialize GPG signing from `ELPAISH_SIGNING_KEY' environment variable.
Imports key armor, configures loopback pinentry, detects secret key ID,
and enables signing.  Return the detected signing key ID or nil.")
(autoload 'elpaish-rotate-keys "elpaish" "\
Rotate GPG signing subkey [S] for MASTER-KEY-ID and export to OUTPUT-DIR.
Syncs with GitHub secrets on REPO-SLUG.

(fn &key MASTER-KEY-ID REPO-SLUG (OUTPUT-DIR elpaish-output-dir))")
(autoload 'elpaish-revoke-key "elpaish" "\
Publish revocation certificate for KEY-ID to `elpaish.rev.asc' in OUTPUT-DIR.

(fn KEY-ID &optional OUTPUT-DIR)" t)
(autoload 'elpaish-build-recompile "elpaish" "\
Re-run `elpaish-build-all' from the build compilation buffer.

(fn &optional IGNORE-AUTO NOCONFIRM)" t)
(autoload 'elpaish-build-mode "elpaish" "\
Major mode for ELPAish package build and compilation logs.
\\{elpaish-build-mode-map}

(fn)" t)
(autoload 'elpaish-build-all "elpaish" "\
Build registered packages, generate indexes, and sign archives.
MODE can be `all', `snapshot', `stable', or `staging'.
Defaults to `elpaish-release-mode'.  OUTPUT-DIRECTORY-PATH defaults to
`elpaish-output-dir'.  Every registered package is rebuilt unconditionally
on every call; see `elpaish-build-package'.

(fn &optional MODE OUTPUT-DIRECTORY-PATH)" t)
(autoload 'elpaish-build-single "elpaish" "\
Interactively build and sign a single package RECIPE-OR-NAME for STREAM.
OUTPUT-DIRECTORY-PATH overrides destination directory.

(fn RECIPE-OR-NAME &optional STREAM OUTPUT-DIRECTORY-PATH)" t)
(autoload 'elpaish-preflight-single "elpaish" "\
Run preflight quality gates on a single package RECIPE-OR-NAME.

(fn RECIPE-OR-NAME)" t)
(autoload 'elpaish-view-build-log "elpaish" "\
Switch to the ELPAish build compilation log buffer." t)
(autoload 'elpaish-serve-local "elpaish" "\
Start local HTTP server serving OUTPUT-DIR (defaults to public/) at PORT.
PORT defaults to `elpaish-preview-server-port'.

(fn &optional PORT OUTPUT-DIR)" t)
(autoload 'elpaish-stop-server "elpaish" "\
Stop local preview HTTP server if active." t)
(autoload 'elpaish-start-auto-build "elpaish" "\
Start scheduled background rebuilds of the ELPA repository.
INTERVAL can be seconds or a time string (e.g. \"1 hour\").
If IDLE is non-nil, run rebuilds when Emacs is idle for INTERVAL.

(fn INTERVAL &optional IDLE)" t)
(autoload 'elpaish-stop-auto-build "elpaish" "\
Stop the periodic background rebuild timer if active." t)
(autoload 'elpaish-status-refresh "elpaish" "\
Refresh the package registry status table." t)
(autoload 'elpaish-status-build-at-point "elpaish" "\
Build the package at point across all release streams." t)
(autoload 'elpaish-status-preflight-at-point "elpaish" "\
Execute preflight check for package at point." t)
(autoload 'elpaish-status-preflight-all "elpaish" "\
Execute preflight check suite for all registered packages." t)
(autoload 'elpaish-status "elpaish" "\
Open the ELPAish Builder management buffer." t)
(autoload 'elpaish-run-checks "elpaish" "\
Execute package quality check suite for current repository or DIR.

(fn &optional DIR)" t)
(autoload 'elpaish-view-check-log "elpaish" "\
Switch to the ELPAish check compilation log buffer for DIR.

(fn &optional DIR)" t)
(autoload 'elpaish-menu "elpaish" "\
Transient dispatch menu for ELPAish package repository management.

(fn)" t)
(register-definition-prefixes "elpaish" '("elpaish-"))


;;; Generated autoloads from elpaish-check.el

(autoload 'elpaish-check-recompile "elpaish-check" "\
Recompile and re-run package quality check suite from the compilation buffer.

(fn &optional IGNORE-AUTO NOCONFIRM)" t)
(autoload 'elpaish-check-mode "elpaish-check" "\
Major mode for ELPAish package quality check and preflight logs.
\\{elpaish-check-mode-map}

(fn)" t)
(autoload 'elpaish-check-package "elpaish-check" "\
Execute preflight quality check suite for package located at DIR.
MAIN-FILE explicitly overrides main file detection.
TEST-DIR explicitly specifies directory containing ERT test files.
SKIP-CHECKS is a list of check symbols to bypass, or t to skip all.
Supported check symbols: `parens', `checkdoc', `package-lint',
`byte-compile', `ert'.
VERBOSE is toggles extra output.
EXTRA-LOAD-PATH is a list of directories added to `load-path' during
byte-compilation and tests.

(fn &optional DIR &key MAIN-FILE TEST-DIR SKIP-CHECKS VERBOSE EXTRA-LOAD-PATH)")
(autoload 'elpaish-check-all "elpaish-check" "\
Execute preflight quality check suite for DIR (defaults to `default-directory').
Pipes all output into `function:elpaish-check-buffer-name' compilation buffer.

(fn &optional DIR)" t)
(autoload 'elpaish-check-project-has-el-files-p "elpaish-check" "\
Return non-nil when DIR or its project root has Emacs Lisp (.el) files.

(fn &optional DIR)")
(autoload 'elpaish-check-setup-compile-command "elpaish-check" "\
Set buffer-local `compile-command' to run `elpaish-run-checks' for DIR.
Only applies when the current buffer or DIR belongs to a project with .el files.

(fn &optional DIR)" t)
(autoload 'elpaish-check-maybe-setup-builder "elpaish-check" "\
Configure `compile-command' to run `elpaish-run-checks' when opening .el files.")
(autoload 'elpaish-check-enable-builder "elpaish-check" "\
Enable `elpaish-run-checks' as the default build command for projects with .el files." t)
(register-definition-prefixes "elpaish-check" '("elpaish-check-"))


;;; Generated autoloads from elpaish-css.el

(register-definition-prefixes "elpaish-css" '("elpaish-"))


;;; Generated autoloads from elpaish-install.el

(autoload 'elpaish-install-add-bootstrap-packages "elpaish-install" "\
Append unique package symbols from PKGS to `elpaish-install-bootstrap-packages'.
PKGS can be package symbols or lists of package symbols.

(fn &rest PKGS)" t)
(autoload 'elpaish-install-ensure-package-dependencies "elpaish-install" "\
Extract package dependencies from DIR-OR-RECIPE and install any missing ones.
DIR-OR-RECIPE can be a directory path string or an `elpaish-recipe' struct.

(fn DIR-OR-RECIPE)")
(autoload 'elpaish-install-packages-async "elpaish-install" "\
Install PKGS asynchronously out-of-process using a sprite pool if available.
If sprite is not available, falls back to a background timer.
Calls CALLBACK when installation finishes.

(fn PKGS &key REFRESH POOL-SIZE CALLBACK)")
(autoload 'elpaish-install-upgrade-packages-async "elpaish-install" "\
Upgrade PKGS asynchronously out-of-process using a sprite pool if available.
If sprite is not available, falls back to a background timer.
Calls CALLBACK when upgrade finishes.

(fn PKGS &key POOL-SIZE CALLBACK)")
(autoload 'elpaish-install-packages "elpaish-install" "\
Install a group of packages with continue-on-error semantics.
ARGS can contain package symbols, lists of symbols, or keyword options:
  :refresh T    - Call `package-refresh-contents' before installing.
  :async T      - Perform installation asynchronously (uses sprite pool if available).
  :pool-size N  - Number of sprite workers to use for async parallel installation.
  :callback FN  - Function to call when async installation finishes.

When no packages are specified in ARGS, defaults to `elpaish-install-bootstrap-packages'.

(fn &rest ARGS)" t)
(autoload 'elpaish-install-upgrade-packages "elpaish-install" "\
Upgrade a group of packages with continue-on-error semantics.
Runs `package-refresh-contents' before checking for upgrades.
It is not an error if nothing is upgradable.

ARGS can contain package symbols, lists of symbols, or keyword options:
  :async T      - Perform upgrading asynchronously (uses sprite pool if available).
  :pool-size N  - Number of sprite workers to use for async parallel upgrade.
  :callback FN  - Function to call when async upgrade finishes.

When no packages are specified in ARGS, defaults to `elpaish-install-bootstrap-packages'.

(fn &rest ARGS)" t)
(register-definition-prefixes "elpaish-install" '("elpaish-install-"))


;;; Generated autoloads from elpaish-keyring.el

(autoload 'elpaish-keyring-setup "elpaish-keyring" "\
Configure `package-archives' to include ELPAish repository for STREAM.
STREAM defaults to \\='snapshot.  BASE-URL defaults to `elpaish-base-url'.

(fn &optional STREAM BASE-URL)" t)
(register-definition-prefixes "elpaish-keyring" '("elpaish-keyring--canonical-stream"))


;;; Generated autoloads from elpaish-recipes.el

(autoload 'elpaish-recipe-name-from-url "elpaish-recipes" "\
Derive bare package name from remote URL (e.g. \"xtdlib\" from \".../xtdlib.el.git\").

(fn URL)")
(autoload 'elpaish-recipe-path "elpaish-recipes" "\
Return the first existing local checkout of NAME-OR-URL, or REMOTE-URL.
If REMOTE-URL is omitted, NAME-OR-URL is treated as the remote URL, and the
bare directory name is derived automatically from the URL to avoid stuttering.

Searches `elpaish-recipe-local-search-dirs', then \"external/NAME\" under
`user-emacs-directory' and under `default-directory'.

(fn NAME-OR-URL &optional REMOTE-URL)")
(autoload 'elpaish-load-packages "elpaish-recipes" "\
Load package recipe definitions from FILES (defaults to `elpaish-packages-files').
FILES can be a single file/glob or a list of files/globs.
Returns the number of registered recipes.

(fn &optional FILES)" t)
(autoload 'elpaish-discover-recipes "elpaish-recipes" "\
Scan ROOT for monorepo subpackages and register a recipe for each.
Looks for immediate subdirectories containing a `<dir-name>.el' file with a
package header, and registers each with the appropriate `:source-dir'.
BRANCH defaults to `elpaish-default-branch'. FILES overrides the default
wildcard `(\"*.el\")' pattern used for every discovered package, so
multi-file packages are picked up automatically at build time without
enumerating every file here.

(fn ROOT &key BRANCH FILES)" t)
(register-definition-prefixes "elpaish-recipes" '("elpaish-"))


;;; Generated autoloads from elpaish-signing-keys.el

(autoload 'elpaish-verify-signing-key "elpaish-signing-keys" "\
Verify the ELPAish CI signing subkey for KEY-ID (or auto-detect it).
Prints a pass/fail report for each check and returns non-nil overall.

(fn &optional KEY-ID)" t)
(autoload 'elpaish-generate-master-key "elpaish-signing-keys" "\
Generate an offline Ed25519 certification-only [C] primary key for IDENTITY.
IDENTITY is a UID string, e.g. \"ELPAish Package Signing <elpa@example.com>\".
Returns the new primary key's fingerprint.

The master key SHOULD be passphrase-protected (unlike the signing subkey —
see `elpaish-add-signing-subkey'). When PASSPHRASE is omitted and this is
called interactively, you are prompted for one with confirmation via
`read-passwd'; pass an explicit empty string only if you deliberately want
an unprotected master.

(fn IDENTITY &optional PASSPHRASE)" t)
(autoload 'elpaish-add-signing-subkey "elpaish-signing-keys" "\
Add a passphrase-less Ed25519 signing subkey [S] to MASTER-FPR.
EXPIRY defaults to `elpaish-signing-key-default-expiry'. Returns the new
subkey's fingerprint.

Tries the fully headless path first: an empty passphrase in loopback mode,
which GnuPG stores as a genuinely unprotected key when MASTER-FPR has no
existing protection to unlock (verified against a scratch keyring) — no
prompts at all in that case. If MASTER-FPR already has a passphrase, that
fast path fails, so this falls back to routing the two DISTINCT prompts
(master unlock, then the new subkey's own — leave that one empty) through
Emacs's minibuffer via `elpaish-generate--ensure-emacs-pinentry'.

(fn MASTER-FPR &optional EXPIRY)" t)
(autoload 'elpaish-set-key-passphrase "elpaish-signing-keys" "\
Add, change, or remove password protection on KEY-ID.
Interactively prompts for the new passphrase — leave it empty to remove
protection entirely.

Tries the fully headless path first: this only works when KEY-ID currently
has no protection, or already has exactly NEW-PASSPHRASE. If KEY-ID has a
DIFFERENT existing passphrase, GnuPG needs that real one to unlock and the
desired NEW-PASSPHRASE for the result — two distinct values it cannot both
take from a single `--passphrase-fd' — so this falls back to routing the
CURRENT-passphrase prompt and the NEW-passphrase prompt(s) through Emacs's
minibuffer via `elpaish-generate--ensure-emacs-pinentry'.

(fn KEY-ID &optional NEW-PASSPHRASE)" t)
(autoload 'elpaish-copy-revocation-cert "elpaish-signing-keys" "\
Copy MASTER-FPR's auto-generated revocation cert into OUTPUT-DIR.
GnuPG writes one automatically at key-creation time under
homedir/openpgp-revocs.d/<FPR>.rev — `--gen-revoke' cannot run in batch mode
at all (confirmed: \"gpg: can't do this in batch mode\"), so this reuses that
file instead of trying to script the interactive command.

(fn MASTER-FPR &optional OUTPUT-DIR)" t)
(autoload 'elpaish-export-key-material "elpaish-signing-keys" "\
Export all ceremony artifacts for MASTER-FPR into OUTPUT-DIR.
Writes master.key.asc (full secret backup — keep offline), signing-<year>.key
(secret subkeys only — this is what goes to `ELPAISH_SIGNING_KEY'),
elpaish-keyring.gpg (binary public keyring), and elpaish.pub.asc (armored
public key).

(fn MASTER-FPR &optional OUTPUT-DIR)" t)
(autoload 'elpaish-run-key-ceremony "elpaish-signing-keys" "\
Run the full ELPAish key ceremony for IDENTITY end to end.
Generates the master key (prompts for its passphrase interactively — keep
one), adds a passphrase-less EXPIRY (default `elpaish-signing-key-default-expiry')
signing subkey, copies
the auto-generated revocation cert, exports all artifacts to OUTPUT-DIR
(default `elpaish-key-output-dir'), and runs `elpaish-verify-signing-key'.
This mints real key material — confirm you mean to run it.

(fn IDENTITY &optional OUTPUT-DIR EXPIRY)" t)
(register-definition-prefixes "elpaish-signing-keys" '("elpaish-"))


;;; Generated autoloads from elpaish-website.el

(autoload 'elpaish-generate-stream-index "elpaish-website" "\
Generate static `index.html' package catalog for STREAM in OUTPUT-DIR.
TITLE overrides the default page title derived from STREAM.

(fn &optional STREAM OUTPUT-DIR TITLE)")
(autoload 'elpaish-generate-about-page "elpaish-website" "\
Generate static `about.html' page in OUTPUT-DIR.

(fn &optional OUTPUT-DIR)")
(autoload 'elpaish-generate-top-index "elpaish-website" "\
Generate top-level static `index.html' landing page and about page in OUTPUT-DIR.

(fn &optional OUTPUT-DIR)")
(autoload 'elpaish-build-website "elpaish-website" "\
Regenerate all static HTML pages (landing page, about page, and stream catalogs).
Does not rebuild package archives or re-derive git versions.
OUTPUT-DIRECTORY-PATH defaults to `elpaish-output-dir'.

(fn &optional OUTPUT-DIRECTORY-PATH)" t)
(register-definition-prefixes "elpaish-website" '("elpaish-website-"))

;;; End of scraped data

(provide 'elpaish-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; elpaish-autoloads.el ends here
