;;; gen-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from gen.el

(defvar cl-struct-gen-tags)
(with-suppressed-warnings ((lexical infinite exhausted peeked iter cl-tag-slot)) (eval-and-compile (define-inline gen-p (x) (declare (side-effect-free error-free) (pure t) (noinline nil)) (inline-letevals (x) (inline-quote (and (memq (type-of (\, x)) cl-struct-gen-tags) t)))) (define-symbol-prop 'gen 'cl-deftype-satisfies 'gen-p)) (define-inline gen-iter (x) "Access slot \"iter\" of `gen' struct X.
The raw generator.el closure iterator.


(fn gen-iter X)" (declare (side-effect-free t) (noinline nil)) (inline-letevals (x) (inline-quote (progn (or (gen-p (\, x)) (signal 'wrong-type-argument (list 'gen (\, x)))) (aref (\, x) 1))))) (function-put 'gen-iter 'document-generalized-variable t) (define-inline gen-peeked (x) "Access slot \"peeked\" of `gen' struct X.
A cons (VALUE . t) when a value has been peeked, else nil.


(fn gen-peeked X)" (declare (side-effect-free t) (noinline nil)) (inline-letevals (x) (inline-quote (progn (or (gen-p (\, x)) (signal 'wrong-type-argument (list 'gen (\, x)))) (aref (\, x) 2))))) (function-put 'gen-peeked 'document-generalized-variable t) (define-inline gen-exhausted (x) "Access slot \"exhausted\" of `gen' struct X.
Non-nil when the iterator has signaled `iter-end-of-sequence'.


(fn gen-exhausted X)" (declare (side-effect-free t) (noinline nil)) (inline-letevals (x) (inline-quote (progn (or (gen-p (\, x)) (signal 'wrong-type-argument (list 'gen (\, x)))) (aref (\, x) 3))))) (function-put 'gen-exhausted 'document-generalized-variable t) (define-inline gen-infinite (x) "Access slot \"infinite\" of `gen' struct X.
Non-nil when the generator is known to be infinite.


(fn gen-infinite X)" (declare (side-effect-free t) (noinline nil)) (inline-letevals (x) (inline-quote (progn (or (gen-p (\, x)) (signal 'wrong-type-argument (list 'gen (\, x)))) (aref (\, x) 4))))) (function-put 'gen-infinite 'document-generalized-variable t) (cl-defsubst gen--make (&cl-defs (nil (cl-tag-slot) (iter nil :documentation "The raw generator.el closure iterator.") (peeked nil :documentation "A cons (VALUE . t) when a value has been peeked, else nil.") (exhausted nil :documentation "Non-nil when the iterator has signaled `iter-end-of-sequence'.") (infinite nil :documentation "Non-nil when the generator is known to be infinite.")) &key iter peeked exhausted infinite) "Constructor for objects of type `gen'." (declare (side-effect-free t)) (record 'gen iter peeked exhausted infinite)))
(autoload 'gen-wrap "gen"
"Wrap ITER-OR-GEN in a `gen' struct for `seq.el' compatibility.
If ITER-OR-GEN is already a `gen', return it unchanged (updating
its infinite flag if INFINITE is non-nil).
If ITER-OR-GEN is a raw `generator.el' iterator closure or function, wrap it.
When INFINITE is non-nil, marks the generator as infinite so draining operations
can issue a warning before attempting full consumption.

Note on infinite generators: lazy operations (`seq-map', `seq-filter',
`seq-take', `seq-take-while', `seq-drop', `seq-drop-while', etc.) are safe
on infinite generators.  Draining operations (`seq-length', `seq-reverse',
`seq-sort', `seq-into', etc.) will consume forever unless bounded.

(fn ITER-OR-GEN &optional INFINITE)")
(register-definition-prefixes "gen" '("gen--"))

;;; End of scraped data

(provide 'gen-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; gen-autoloads.el ends here
