;;; vui-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from vui.el

(register-definition-prefixes "vui" '("vui-"))


;;; Generated autoloads from vui-components.el

(autoload 'vui-collapsible "vui-components" "\
Create a collapsible section.

ARGS can start with keyword options, followed by children.

Options:
  :title STRING - header text (required)
  :expanded BOOL - controlled mode state
  :on-toggle FN - called with new state on toggle
  :initially-expanded BOOL - initial state for uncontrolled mode
  :title-face FACE - face for header
  :expanded-indicator STRING - shown when expanded (default \"▼\")
  :collapsed-indicator STRING - shown when collapsed (default \"▶\")
  :indent N - content indentation (default 2)
  :key KEY - for reconciliation

Usage:
  (vui-collapsible :title \"Section\" child1 child2)
  (vui-collapsible :title \"FAQ\" :initially-expanded t content...)

(fn &rest ARGS)")
(autoload 'vui-typed-field "vui-components" "\
Create a typed input field with parsing and validation.

PROPS is a plist accepting:
  :type       - Type for parsing: \\='integer, \\='natnum, \\='float,
                \\='number, \\='file, \\='directory, \\='symbol, \\='sexp
  :value      - Typed value (will be stringified for display)
  :min/:max   - Numeric constraints
  :must-exist - Non-nil means file/directory must exist
  :extensions - List of allowed extensions for file type (e.g., \\='(\"el\" \"org\"))
  :validate   - (lambda (typed-value) error-string-or-nil)
  :on-change  - (lambda (typed-value)) called only when valid
  :on-submit  - (lambda (typed-value)) called only when valid on RET
  :on-error   - (lambda (error-msg raw-input)) on parse/validation failure
  :show-error - t or \\='below for below, \\='inline for same line
  :size       - Field width
  :secret     - Password mode
  :key        - Field key
  :required   - Non-nil means empty is invalid

Examples:
  (vui-typed-field :type \\='integer :value 42 :min 0 :max 100
                   :on-change (lambda (n) (message \"Got: %d\" n)))
  (vui-typed-field :type \\='file :extensions \\='(\"el\" \"org\") :show-error t)

(fn &rest PROPS)")
(autoload 'vui-integer-field "vui-components" "\
Create an integer input field.
PROPS accepts all `vui-typed-field' props.  Sets :type to `integer'.

(fn &rest PROPS)")
(autoload 'vui-natnum-field "vui-components" "\
Create a non-negative integer input field.
PROPS accepts all `vui-typed-field' props.  Sets :type to `natnum'.

(fn &rest PROPS)")
(autoload 'vui-float-field "vui-components" "\
Create a float input field.
PROPS accepts all `vui-typed-field' props.  Sets :type to `float'.

(fn &rest PROPS)")
(autoload 'vui-number-field "vui-components" "\
Create a numeric input field (accepts integers or floats).
PROPS accepts all `vui-typed-field' props.  Sets :type to `number'.

(fn &rest PROPS)")
(autoload 'vui-file-field "vui-components" "\
Create a file path input field.
PROPS accepts all `vui-typed-field' props.  Sets :type to `file'.

(fn &rest PROPS)")
(autoload 'vui-directory-field "vui-components" "\
Create a directory path input field.
PROPS accepts all `vui-typed-field' props.  Sets :type to `directory'.

(fn &rest PROPS)")
(autoload 'vui-symbol-field "vui-components" "\
Create a symbol input field.
PROPS accepts all `vui-typed-field' props.  Sets :type to `symbol'.

(fn &rest PROPS)")
(autoload 'vui-sexp-field "vui-components" "\
Create a Lisp expression input field.
PROPS accepts all `vui-typed-field' props.  Sets :type to `sexp'.

(fn &rest PROPS)")
(register-definition-prefixes "vui-components" '("vui-"))

;;; End of scraped data

(provide 'vui-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; vui-autoloads.el ends here
