;;; helm-tree-sitter-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from helm-tree-sitter.el

(autoload 'helm-tree-sitter-or-imenu "helm-tree-sitter" "\
Helm interface for tree-sitter.
If tree-sitter is enabled and we
know how to deal with major mode, we'll use `helm-tree-sitter'.
Otherwise we'll default to `helm-imenu'." t)
(autoload 'helm-tree-sitter "helm-tree-sitter" "\
Helm interface for tree-sitter." t)


;;; Generated autoloads from helm-tree-sitter-c.el

(register-definition-prefixes "helm-tree-sitter-c" '("helm-tree-sitter-c-"))


;;; Generated autoloads from helm-tree-sitter-core.el

(register-definition-prefixes "helm-tree-sitter-core" '("helm-tree-sitter-"))


;;; Generated autoloads from helm-tree-sitter-cpp.el

(register-definition-prefixes "helm-tree-sitter-cpp" '("helm-tree-sitter-cpp-"))


;;; Generated autoloads from helm-tree-sitter-debug.el

(autoload 'helm-tree-sitter-debug "helm-tree-sitter-debug" "\
Helm interface for tree-sitter with all elements shown." t)
(register-definition-prefixes "helm-tree-sitter-debug" '("helm-tree-sitter-debug-elem"))


;;; Generated autoloads from helm-tree-sitter-default.el

(register-definition-prefixes "helm-tree-sitter-default" '("helm-tree-sitter-default-fn"))


;;; Generated autoloads from helm-tree-sitter-python.el

(register-definition-prefixes "helm-tree-sitter-python" '("helm-tree-sitter-python-"))


;;; Generated autoloads from helm-tree-sitter-rust.el

(register-definition-prefixes "helm-tree-sitter-rust" '("helm-tree-sitter-rust-"))


;;; Generated autoloads from helm-tree-sitter-utils.el

(register-definition-prefixes "helm-tree-sitter-utils" '("helm-tree-sitter-utils-"))

;;; End of scraped data

(provide 'helm-tree-sitter-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-tree-sitter-autoloads.el ends here
