;;; telega-bot-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from telega-bot.el

(autoload 'make-telega-bot "telega-bot" "\
Create a new `telega-bot' and register it in `telega-bot-registry'.

(fn &key (NAME \"Telega Bot\") TOKEN FALLBACK ACTIVE)")
(autoload 'telega-bot-register-handler "telega-bot" "\
Register handler NAME for BOT-OR-NAME.

(fn NAME BOT-OR-NAME &rest SPEC &key (OPERATION :command) PATTERN STATE ARGS &allow-other-keys)" nil t)
(function-put 'telega-bot-register-handler 'lisp-indent-function 2)
(autoload 'telega-bot-activate "telega-bot" "\
Activate bot by instance or name and attach global update hook.

(fn BOT-OR-NAME)")
(autoload 'telega-bot-deactivate "telega-bot" "\
Deactivate bot by instance or name and detach global update hook if registry is empty.

(fn BOT-OR-NAME)")
(register-definition-prefixes "telega-bot" '("telega-bot-"))


;;; Generated autoloads from telega-bot-alert.el

(autoload 'telega-bot-alert-register-target "telega-bot-alert" "\
Register a telega-bot alert target NAME delivering to BOT/CHAT-ID/THREAD-ID.

(fn &key NAME BOT CHAT-ID THREAD-ID)")
(autoload 'telega-bot-alert "telega-bot-alert" "\
Send MESSAGE as a telega-bot alert, optionally restricted to TARGETS.

(fn MESSAGE &key TITLE SEVERITY CATEGORY TARGETS)")
(register-definition-prefixes "telega-bot-alert" '("telega-bot-alert-"))

;;; End of scraped data

(provide 'telega-bot-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; telega-bot-autoloads.el ends here
