;;; elpaish-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from elpaish.el

(autoload 'elpaish-register-package "elpaish" "\
Register package NAME with REPOSITORY-PATH (local directory path or remote Git URL).
BRANCH defaults to `elpaish-default-branch' and FILES defaults to \\='(\"*.el\").
SOURCE-DIRECTORY-PATH is the subdirectory within REPOSITORY-PATH holding the package
(default \".\"), for packages that live inside a monorepo or nested \"lisp/\" folder.
TEST-DIRECTORY-PATH is an optional custom test directory path.
DISABLED-STREAMS is a list of stream symbols where this package is suppressed.
DOC is an optional URL or path to documentation.
SUMMARY, URL, KEYWORDS, and REQUIRES provide package metadata.

(fn NAME REPOSITORY-PATH &key BRANCH (FILES \\='(\"*.el\")) SOURCE-DIRECTORY-PATH TEST-DIRECTORY-PATH SOURCE-DIR TEST-DIR PREFLIGHT-SKIP SUMMARY URL DOC KEYWORDS REQUIRES DISABLED-STREAMS SUPPRESS-STREAMS DOCS-URL)")
(autoload 'elpaish-sign-file-headless "elpaish" "\
Sign FILE headlessly generating detached signature for encrypted or unencrypted keys.
Passphrase is provided non-interactively via PASSPHRASE argument,
`elpaish-gpg-passphrase', or `ELPAISH_GPG_PASSPHRASE' environment variable.
Never triggers interactive terminal or GUI pinentry dialogs.
OUTPUT-FILE defaults to FILE.sig. Returns the path to the generated signature, or nil.

(fn FILE &key KEY-ID PASSPHRASE OUTPUT-FILE)")
(autoload 'elpaish-init-signing-from-env "elpaish" "\
Initialize GPG signing configuration from `ELPAISH_SIGNING_KEY' environment variable.
Imports key armor, configures loopback pinentry, detects secret key ID, and enables signing.
Returns the detected signing key ID or nil.")
(autoload 'elpaish-rotate-keys "elpaish" "\
Rotate GPG signing subkey [S], sync with GitHub secrets, and export updated keyring.
MASTER-KEY-ID defaults to the primary certification key.
REPO-SLUG defaults to `elpaish-github-repo-slug'.

(fn &key MASTER-KEY-ID REPO-SLUG (OUTPUT-DIR elpaish-output-dir))" t)
(autoload 'elpaish-revoke-key "elpaish" "\
Publish revocation certificate for KEY-ID to `elpaish.rev.asc' in OUTPUT-DIR.

(fn KEY-ID &optional OUTPUT-DIR)" t)
(autoload 'elpaish-build-recompile "elpaish" "\
Re-run `elpaish-build-all' from the build compilation buffer.

(fn &optional IGNORE-AUTO NOCONFIRM)" t)
(autoload 'elpaish-build-mode "elpaish" "\
Major mode for ELPAish package build and compilation logs.
\\{elpaish-build-mode-map}

(fn)" t)
(autoload 'elpaish-build-all "elpaish" "\
Build registered packages, generate indexes, and sign archives.
MODE can be `all', `snapshot', `stable', or `staging'.
Defaults to `elpaish-release-mode'. OUTPUT-DIRECTORY-PATH defaults to `elpaish-output-dir'.
Every registered package is rebuilt unconditionally on every call; see
`elpaish-build-package'.

(fn &optional MODE OUTPUT-DIRECTORY-PATH)" t)
(autoload 'elpaish-build-single "elpaish" "\
Interactively build and sign a single package RECIPE-OR-NAME for STREAM.

(fn RECIPE-OR-NAME &optional STREAM OUTPUT-DIRECTORY-PATH)" t)
(autoload 'elpaish-preflight-single "elpaish" "\
Run preflight quality gates on a single package RECIPE-OR-NAME.

(fn RECIPE-OR-NAME)" t)
(autoload 'elpaish-view-build-log "elpaish" "\
Switch to the ELPAish build compilation log buffer." t)
(defconst elpaish--mime-types '((".html" . "text/html; charset=utf-8") (".el" . "text/plain; charset=utf-8") (".sig" . "application/pgp-signature") (".asc" . "application/pgp-keys") (".gpg" . "application/pgp-keys") (".tar" . "application/x-tar")) "\
File suffix to MIME content-type mapping for `elpaish--http-mime-type'.")
(autoload 'elpaish-serve-local "elpaish" "\
Start a local HTTP server serving the generated `public/' directory at PORT.
PORT defaults to `elpaish-preview-server-port'.

(fn &optional PORT OUTPUT-DIR)" t)
(autoload 'elpaish-stop-server "elpaish" "\
Stop local preview HTTP server if active." t)
(autoload 'elpaish-start-auto-build "elpaish" "\
Start scheduled background rebuilds of the ELPA repository.
INTERVAL can be seconds or a time string (e.g. \"1 hour\").
If IDLE is non-nil, run rebuilds when Emacs is idle for INTERVAL.

(fn INTERVAL &optional IDLE)" t)
(autoload 'elpaish-stop-auto-build "elpaish" "\
Stop the periodic background rebuild timer if active." t)
(autoload 'elpaish-status-refresh "elpaish" "\
Refresh the package registry status table." t)
(autoload 'elpaish-status-build-at-point "elpaish" "\
Build the package at point across all release streams." t)
(autoload 'elpaish-status-preflight-at-point "elpaish" "\
Run preflight checks for package at point." t)
(autoload 'elpaish-status-preflight-all "elpaish" "\
Run preflight checks for all registered packages." t)
(autoload 'elpaish-status "elpaish" "\
Open the ELPAish Builder management buffer." t)
(autoload 'elpaish-run-checks "elpaish" "\
Run package quality checks for current repository." t)
(autoload 'elpaish-menu "elpaish" "\
Transient dispatch menu for ELPAish package repository management.

(fn)" t)
(register-definition-prefixes "elpaish" '("elpaish-"))


;;; Generated autoloads from elpaish-check.el

(autoload 'elpaish-check-package "elpaish-check" "\
Run preflight quality checks for package located at DIR.
MAIN-FILE explicitly overrides main file detection.
TEST-DIR explicitly specifies directory containing ERT test files.
SKIP-CHECKS is a list of check symbols to bypass, or t to skip all.
Supported check symbols: `parens', `checkdoc', `package-lint', `byte-compile', `ert'.
EXTRA-LOAD-PATH is a list of directories added to `load-path' during byte-compilation and tests.
VERBOSE prints progress messages to `message` buffer.

(fn &optional DIR &key MAIN-FILE TEST-DIR SKIP-CHECKS VERBOSE EXTRA-LOAD-PATH)")
(autoload 'elpaish-check-all "elpaish-check" "\
Run preflight quality checks for current repository." t)
(register-definition-prefixes "elpaish-check" '("acr-run-all-checks" "elpaish-check--" "run-checks-"))


;;; Generated autoloads from elpaish-css.el

(register-definition-prefixes "elpaish-css" '("elpaish-"))


;;; Generated autoloads from elpaish-keyring.el

(autoload 'elpaish-keyring-setup "elpaish-keyring" "\
Configure `package-archives' to include ELPAish archive STREAM.
STREAM can be `snapshot' (default), `stable', or `staging'.

(fn &optional STREAM)" t)
(autoload 'elpaish-keyring-install-key "elpaish-keyring" "\
Import the ELPAish GPG public key into the user GPG keyring / package trust database." t)
(register-definition-prefixes "elpaish-keyring" '("elpaish-base-url"))


;;; Generated autoloads from elpaish-recipes.el

(autoload 'elpaish-load-packages "elpaish-recipes" "\
Load package recipe definitions from FILES (defaults to `elpaish-packages-files').
FILES can be a single file/glob or a list of files/globs.
Returns the number of registered recipes.

(fn &optional FILES)" t)
(defalias 'elpaish-recipes-register-all 'elpaish-load-packages "\
Load all package recipes from the active `packages.el' file.")
(autoload 'elpaish-discover-recipes "elpaish-recipes" "\
Scan ROOT for monorepo subpackages and register a recipe for each.
Looks for immediate subdirectories containing a `<dir-name>.el' file with a
package header, and registers each with the appropriate `:source-dir'.
BRANCH defaults to `elpaish-default-branch'. FILES overrides the default
wildcard `(\"*.el\")' pattern used for every discovered package, so
multi-file packages are picked up automatically at build time without
enumerating every file here.

(fn ROOT &key BRANCH FILES)" t)
(register-definition-prefixes "elpaish-recipes" '("elpaish-"))


;;; Generated autoloads from elpaish-signing-keys.el

(autoload 'elpaish-verify-signing-key "elpaish-signing-keys" "\
Verify the ELPAish CI signing subkey for KEY-ID (or auto-detect it).
Prints a pass/fail report for each check and returns non-nil overall.

(fn &optional KEY-ID)" t)
(autoload 'elpaish-generate-master-key "elpaish-signing-keys" "\
Generate an offline Ed25519 certification-only [C] primary key for IDENTITY.
IDENTITY is a UID string, e.g. \"ELPAish Package Signing <elpa@example.com>\".
Returns the new primary key's fingerprint.

The master key SHOULD be passphrase-protected (unlike the signing subkey —
see `elpaish-add-signing-subkey'). When PASSPHRASE is omitted and this is
called interactively, you are prompted for one with confirmation via
`read-passwd'; pass an explicit empty string only if you deliberately want
an unprotected master.

(fn IDENTITY &optional PASSPHRASE)" t)
(autoload 'elpaish-add-signing-subkey "elpaish-signing-keys" "\
Add a passphrase-less Ed25519 signing subkey [S] to MASTER-FPR.
EXPIRY defaults to `elpaish-signing-key-default-expiry'. Returns the new
subkey's fingerprint.

Tries the fully headless path first: an empty passphrase in loopback mode,
which GnuPG stores as a genuinely unprotected key when MASTER-FPR has no
existing protection to unlock (verified against a scratch keyring) — no
prompts at all in that case. If MASTER-FPR already has a passphrase, that
fast path fails, so this falls back to routing the two DISTINCT prompts
(master unlock, then the new subkey's own — leave that one empty) through
Emacs's minibuffer via `elpaish-generate--ensure-emacs-pinentry'.

(fn MASTER-FPR &optional EXPIRY)" t)
(autoload 'elpaish-set-key-passphrase "elpaish-signing-keys" "\
Add, change, or remove password protection on KEY-ID.
Interactively prompts for the new passphrase — leave it empty to remove
protection entirely.

Tries the fully headless path first: this only works when KEY-ID currently
has no protection, or already has exactly NEW-PASSPHRASE. If KEY-ID has a
DIFFERENT existing passphrase, GnuPG needs that real one to unlock and the
desired NEW-PASSPHRASE for the result — two distinct values it cannot both
take from a single `--passphrase-fd' — so this falls back to routing the
CURRENT-passphrase prompt and the NEW-passphrase prompt(s) through Emacs's
minibuffer via `elpaish-generate--ensure-emacs-pinentry'.

(fn KEY-ID &optional NEW-PASSPHRASE)" t)
(autoload 'elpaish-copy-revocation-cert "elpaish-signing-keys" "\
Copy MASTER-FPR's auto-generated revocation cert into OUTPUT-DIR.
GnuPG writes one automatically at key-creation time under
homedir/openpgp-revocs.d/<FPR>.rev — `--gen-revoke' cannot run in batch mode
at all (confirmed: \"gpg: can't do this in batch mode\"), so this reuses that
file instead of trying to script the interactive command.

(fn MASTER-FPR &optional OUTPUT-DIR)" t)
(autoload 'elpaish-export-key-material "elpaish-signing-keys" "\
Export all ceremony artifacts for MASTER-FPR into OUTPUT-DIR.
Writes master.key.asc (full secret backup — keep offline), signing-<year>.key
(secret subkeys only — this is what goes to `ELPAISH_SIGNING_KEY'),
elpaish-keyring.gpg (binary public keyring), and elpaish.pub.asc (armored
public key).

(fn MASTER-FPR &optional OUTPUT-DIR)" t)
(autoload 'elpaish-run-key-ceremony "elpaish-signing-keys" "\
Run the full ELPAish key ceremony for IDENTITY end to end.
Generates the master key (prompts for its passphrase interactively — keep
one), adds a passphrase-less EXPIRY (default `elpaish-signing-key-default-expiry')
signing subkey, copies
the auto-generated revocation cert, exports all artifacts to OUTPUT-DIR
(default `elpaish-key-output-dir'), and runs `elpaish-verify-signing-key'.
This mints real key material — confirm you mean to run it.

(fn IDENTITY &optional OUTPUT-DIR EXPIRY)" t)
(register-definition-prefixes "elpaish-signing-keys" '("elpaish-"))


;;; Generated autoloads from elpaish-website.el

(autoload 'elpaish-generate-stream-index "elpaish-website" "\
Generate static `index.html' package catalog for STREAM in OUTPUT-DIR.
TITLE overrides the default page title derived from STREAM.

(fn &optional STREAM OUTPUT-DIR TITLE)")
(autoload 'elpaish-generate-about-page "elpaish-website" "\
Generate static `about.html' page in OUTPUT-DIR.

(fn &optional OUTPUT-DIR)")
(autoload 'elpaish-generate-top-index "elpaish-website" "\
Generate top-level static `index.html' landing page and about page in OUTPUT-DIR.

(fn &optional OUTPUT-DIR)")
(autoload 'elpaish-build-website "elpaish-website" "\
Regenerate all static HTML pages (landing page, about page, and stream catalogs).
Does not rebuild package archives or re-derive git versions.
OUTPUT-DIRECTORY-PATH defaults to `elpaish-output-dir'.

(fn &optional OUTPUT-DIRECTORY-PATH)" t)
(register-definition-prefixes "elpaish-website" '("elpaish-"))

;;; End of scraped data

(provide 'elpaish-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; elpaish-autoloads.el ends here
