;;; eglot-test-at-point-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from eglot-test-at-point.el

(autoload 'eglot-test-at-point-setup-go "eglot-test-at-point" "\
Configure test codelens vars for Go (gopls `test' lens).")
(autoload 'eglot-test-at-point-setup-rust "eglot-test-at-point" "\
Configure test codelens vars for Rust (rust-analyzer `runSingle' lens).")
(autoload 'eglot-test-at-point-setup-python "eglot-test-at-point" "\
Configure test discovery for Python via pylsp (+ python-lsp-ruff, pylsp-rope).
pylsp supports `textDocument/documentSymbol' but not test code lenses, so
`eglot-test-at-point-get-name-fn' is used instead of the codeLens path.
Discovers top-level `test_*' functions (kind 12) and `test_*' methods (kind 6)
inside `Test*' classes (kind 5).  Runs tests with `python -m pytest'.")
(autoload 'eglot-test-at-point "eglot-test-at-point" "\
Run the test at point in a dedicated compilation buffer.
Buffer is named *<project>-test-<directory>*.  Requires
`eglot-test-at-point-run-command-fn' and either `eglot-test-at-point-get-name-fn'
(direct discovery) or the `eglot-test-at-point-*' trio (code lens path)
to be set buffer-locally." t)
(autoload 'eglot-test-at-point-select "eglot-test-at-point" "\
Select a test from the current buffer and run it in a compilation buffer.
Buffer is named *<project>-test-<directory>*.  Requires
`eglot-test-at-point-list-fn' and `eglot-test-at-point-run-command-fn'
to be set buffer-locally." t)
(register-definition-prefixes "eglot-test-at-point" '("eglot-test-at-point-"))

;;; End of scraped data

(provide 'eglot-test-at-point-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; eglot-test-at-point-autoloads.el ends here
