;;; gptel-agent-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from gptel-agent.el

(autoload 'gptel-agent-read-file "gptel-agent" "\
Read a preset/agent from AGENT-FILE.

If TEMPLATES is non-nil, read the system-prompt with templates applied
to them.  TEMPLATES should be an alist of (VAR-NAME . VAR-VALUE) for
template expansion.  Template variables in the format {{VAR-NAME}} in
the markdown body will be replaced with VAR-VALUE.

If METADATA-ONLY is non-nil, only the header/metadata of the
preset/agent will be returned.  If TEMPLATES and METADATA-ONLY are
both non-nil, TEMPLATES will be ignored.

(fn AGENT-FILE &optional TEMPLATES METADATA-ONLY)")
(autoload 'gptel-agent-update "gptel-agent" "\
Update agents.")
(autoload 'gptel-agent "gptel-agent" "\
Start a `gptel-agent' session in the current project.

With optional prefix arg, query for PROJECT-DIR.  Load AGENT-PRESET in
this session, which defaults to the default `gptel-agent'.

(fn &optional PROJECT-DIR AGENT-PRESET)" t)
(register-definition-prefixes "gptel-agent" '("gptel-agent-"))


;;; Generated autoloads from gptel-agent-tools.el

(register-definition-prefixes "gptel-agent-tools" '("gptel-agent-"))


;;; Generated autoloads from gptel-agent-tools-introspection.el

(register-definition-prefixes "gptel-agent-tools-introspection" '("gptel-agent--introspect-"))

;;; End of scraped data

(provide 'gptel-agent-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; gptel-agent-autoloads.el ends here
