;;; tailscale-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from tailscale.el

(autoload 'tailscale-status "tailscale" "\
Display interactive Tailscale network status buffer." t)
(autoload 'tailscale-connect "tailscale" "\
Connect Tailscale daemon (`tailscale up')." t)
(autoload 'tailscale-disconnect "tailscale" "\
Disconnect Tailscale daemon (`tailscale down')." t)
(autoload 'tailscale-copy-ip "tailscale" "\
Select a Tailscale node interactively and copy its IP to the kill ring." t)
(autoload 'tailscale-file-send "tailscale" "\
Send FILE to TARGET-NODE via Taildrop (`tailscale file cp').

(fn FILE TARGET-NODE)" t)
(autoload 'tailscale-mode "tailscale" "\
Major mode for inspecting Tailscale network status.

(fn)" t)
(register-definition-prefixes "tailscale" '("tailscale-"))

;;; End of scraped data

(provide 'tailscale-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; tailscale-autoloads.el ends here
