;;; revbufs-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from revbufs.el

(autoload 'revbufs "revbufs" "\
Examines all open buffers and reverts any that are out of date.
If there are orphans or out of date buffers, this operation opens
the `*revbufs*' buffer reporting the outcome." t)
(register-definition-prefixes "revbufs" '("revbufs-"))

;;; End of scraped data

(provide 'revbufs-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; revbufs-autoloads.el ends here
