;;; denote-review-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from denote-review.el

(autoload 'denote-review-set-date "denote-review" "\
Set the reviewdate in the current buffer.
Replace an existing reviewdate." t)
(autoload 'denote-review-set-date-dired-marked-files "denote-review" "\
Insert a reviewdate in the marked files.
Set a reviewdate according the identifier in the filename,
when called with the Universal Argument use current date.
Does not overwrite existing reviewdates." t)
(autoload 'denote-review-display-list "denote-review" "\
Show buffer with reviewdates.
DENOTEPATH-AND-KEYWORD is a cons of a path and a keyword.
Filter by keyword.

(fn DENOTEPATH-AND-KEYWORD)" t)
(register-definition-prefixes "denote-review" '("denote-review-"))


;;; End of scraped data

(provide 'denote-review-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; denote-review-autoloads.el ends here
