;;; hitl-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from hitl.el

(autoload 'hitl-generate-id "hitl"
"Generate a unique question ID string.")
(autoload 'hitl--normalize-kind "hitl"
"Normalize KIND string, symbol or keyword to keyword symbol.

(fn KIND)")
(autoload 'hitl-ask "hitl"
"Register a new `hitl-question'.
PROMPT is the prompt string displayed to the user.
KIND specifies the input widget: `:boolean', `:confirm', `:single-choice',
`:multi-choice', `:text', `:file', or `:number'.
OPTIONS is a list of candidate strings or alist.
DEFAULT-VALUE is the preselected fallback value.
TARGET is an optional target identifier (buffer, shell name, or agent id).
DIRECTORY is an optional working directory string.
TIMEOUT is an optional lifespan in seconds.
CALLBACK is an optional function invoked with (RESPONSE QUESTION) upon answer.
METADATA is an optional plist of extra context.
ID optionally overrides the generated question ID.
Returns the created `hitl-question' struct.

(fn &key PROMPT (KIND :single-choice) OPTIONS DEFAULT-VALUE TARGET DIRECTORY TIMEOUT CALLBACK METADATA ID)")
(autoload 'hitl-get "hitl"
"Retrieve `hitl-question' by ID, or nil if not found.

(fn ID)")
(autoload 'hitl-list-pending "hitl"
"List all pending `hitl-question' structs in chronological order.
When TARGET-FILTER is non-nil, only questions matching TARGET-FILTER
are returned.

(fn &optional TARGET-FILTER)")
(autoload 'hitl-list-all "hitl"
"List all registered `hitl-question' structs in chronological order.")
(autoload 'hitl-answer "hitl"
"Mark question ID as answered with RESPONSE and invoke callback.
Returns the updated `hitl-question' struct.

(fn ID RESPONSE)")
(autoload 'hitl-cancel "hitl"
"Mark question ID as cancelled with optional REASON string.
Returns the updated `hitl-question' struct.

(fn ID &optional REASON)")
(autoload 'hitl-expire "hitl"
"Mark question ID as expired.
Returns the updated `hitl-question' struct.

(fn ID)")
(autoload 'hitl-check-expirations "hitl"
"Check and expire questions that have exceeded their timeout.")
(autoload 'hitl-clear-store "hitl"
"Clear all questions from the in-memory store.")
(register-definition-prefixes "hitl" '("hitl-"))


;;; Generated autoloads from hitl-cursor.el

(autoload 'hitl-cursor-next "hitl-cursor"
"Return the next pending `hitl-question' for CURSOR-ID and advance position.
If CURSOR-ID is nil, defaults to \"default\".
When TARGET-FILTER is non-nil, only questions matching TARGET-FILTER
are returned.  Advances the cursor position to the returned question.

(fn &optional CURSOR-ID TARGET-FILTER)")
(autoload 'hitl-cursor-peek "hitl-cursor"
"Inspect the next pending `hitl-question' for CURSOR-ID without advancing.
If CURSOR-ID is nil, defaults to \"default\".

(fn &optional CURSOR-ID TARGET-FILTER)")
(autoload 'hitl-cursor-reset "hitl-cursor"
"Reset cursor CURSOR-ID to the beginning.

(fn &optional CURSOR-ID)")
(autoload 'hitl-cursor-answer "hitl-cursor"
"Submit an answer RESPONSE for question ID via cursor protocol.
Returns the updated `hitl-question' struct.

(fn ID RESPONSE)")
(autoload 'hitl-question-to-plist "hitl-cursor"
"Serialize `hitl-question' struct Q to a property list.

(fn Q)")
(autoload 'hitl-question-from-plist "hitl-cursor"
"Deserialize PLIST to a `hitl-question' struct.

(fn PLIST)")
(autoload 'hitl-serialize-store "hitl-cursor"
"Serialize the entire question store into a list of plists.")
(autoload 'hitl-deserialize-store "hitl-cursor"
"Populate the question store from a list of question plists DATA.

(fn DATA)")
(autoload 'hitl-question-to-json "hitl-cursor"
"Serialize `hitl-question' struct Q to a JSON string.

(fn Q)")
(autoload 'hitl-question-from-json "hitl-cursor"
"Deserialize JSON-STRING to a `hitl-question' struct.

(fn JSON-STRING)")
(register-definition-prefixes "hitl-cursor" '("hitl--cursors"))


;;; Generated autoloads from hitl-mcp.el

(autoload 'hitl-mcp-register "hitl-mcp"
"Ensure `hitl-mcp-service' is registered in `mcpkit-registry' and return it." t)
(register-definition-prefixes "hitl-mcp" '("hitl-mcp-" "mcpkit-register-ask-tools"))


;;; Generated autoloads from hitl-prompt.el

(autoload 'hitl-prompt-question "hitl-prompt"
"Prompt the user interactively for `hitl-question' Q and return the response.

(fn Q)")
(autoload 'hitl-prompt "hitl-prompt"
"Interactively prompt user to answer a pending HITL question.
If QUESTION-ID is provided, answer that specific question;
otherwise select from all pending questions.

(fn &optional QUESTION-ID)" t)


;;; Generated autoloads from hitl-ui.el

(autoload 'hitl-ui-refresh "hitl-ui"
"Refresh the `*hitl-questions*' tabulated list buffer." t)
(autoload 'hitl-list "hitl-ui"
"Display the list of all HITL questions." t)
(defvar hitl-indicator-mode nil
"Non-nil if Hitl-Indicator mode is enabled.
See the `hitl-indicator-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `hitl-indicator-mode'.")
(custom-autoload 'hitl-indicator-mode "hitl-ui" nil)
(autoload 'hitl-indicator-mode "hitl-ui"
"Global minor mode to show pending HITL question count in the mode line.

This is a global minor mode.  If called interactively, toggle the
`Hitl-Indicator mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='hitl-indicator-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "hitl-ui" '("hitl-"))

;;; End of scraped data

(provide 'hitl-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; hitl-autoloads.el ends here
