;;; denote-dash-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from denote-dash.el

(autoload 'denote-dash "denote-dash"
"Open or switch to the *denote-dash* buffer." t)
(autoload 'denote-dash--close-note-buffer "denote-dash"
"Close Denote note buffer BUF, prompting to save if modified.
Returns a cons cell (SAVED-P . STALE-NAME).

(fn BUF)")
(autoload 'denote-dash-close-all-notes "denote-dash"
"Close every open Denote note buffer, prompting to save modified ones.
For a modified buffer whose file no longer exists on disk — for example
because a sequence operation renamed it out from under the buffer — the
user is informed and asked whether to save (which recreates the file) or
discard the changes." t)
(autoload 'denote-dash-save-and-kill-all-notes "denote-dash"
"Save every modified Denote note buffer, then kill all Denote note buffers.
Unlike `denote-dash-close-all-notes', this does not prompt per buffer:
modified buffers are saved unconditionally before every Denote buffer is
killed." t)
(autoload 'denote-dash-hierarchy-switch-or-view "denote-dash"
"Select a visible hierarchy view window, or open a new one.
When a window already displays a `denote-sequence-hierarchy-mode' buffer,
select it instead of opening a duplicate view via
`denote-sequence-view-hierarchy'." t)
(autoload 'denote-dash-hierarchy-view-by-note "denote-dash"
"View the sequence hierarchy scoped to a note chosen via ACR.
Prompts for a Denote note with `denote-dash-note-prompt' and uses its
sequence signature as the prefix for `denote-sequence-view-hierarchy',
rather than typing a raw sequence string.  With a prefix argument, also
prompt for DEPTH via `denote-sequence-depth-prompt'.

(fn &optional DEPTH)" t)
(autoload 'denote-dash-hierarchy-toggle-show-tags "denote-dash"
"Toggle display of tags in the current sequence hierarchy buffer." t)
(autoload 'denote-dash-hierarchy-filter "denote-dash"
"Filter hierarchy view to notes matching TAG.
TAG can be a tag string or a filter expression.

(fn TAG)" t)
(autoload 'denote-dash-hierarchy-exclude-tag "denote-dash"
"Exclude notes with TAG from the hierarchy view.

(fn TAG)" t)
(autoload 'denote-dash-hierarchy-clear-filter "denote-dash"
"Clear active tag filters in the current sequence hierarchy buffer." t)
(autoload 'denote-dash-review-display-list "denote-dash"
"Show buffer with reviewdates.
FILTER can be a timeframe symbol (`due', `past', `today', `week', `all'),
a cons of (PATH . KEYWORD-OR-TIMEFRAME), or nil.
By default (when FILTER is nil or called interactively without prefix arg),
filters to notes due for review (past, today, or in < 1 week).
With a prefix argument C-u when called interactively, prompts for a filter.

(fn &optional FILTER)" t)
(autoload 'denote-dash-open-view "denote-dash"
"Open saved view NAME in a dedicated `*denote-dash: NAME*' buffer.
When called interactively, prompts for an existing view from
`denote-dash-saved-views'.  Refreshes and manages the view in its
own buffer independently.

(fn &optional NAME)" t)
(autoload 'denote-dash-clone-view "denote-dash"
"Clone current view state into a new dedicated buffer `*denote-dash: NAME*'.
Saves view as NAME in `denote-dash-saved-views' and switches to buffer.

(fn &optional NAME)" t)
(autoload 'denote-dash-rename-file "denote-dash"
"Rename FILE per `denote-prompts', selecting FILE via `denote-dash-note-prompt'.
Same effect as `denote-rename-file', except FILE selection always uses the
annotated, context-defaulting prompt instead of that command's own fallback
to a plain `read-file-name', which is unusable from a `denote-dash' or
sequence-hierarchy buffer since neither visits a file.

(fn &optional FILE)" t)
(autoload 'denote-dash-retag-file "denote-dash"
"Change FILE's keywords, selecting FILE via `denote-dash-note-prompt'.
Same effect as `denote-rename-file-keywords', except FILE selection always
uses the annotated, context-defaulting prompt instead of that command's own
fallback to a plain `read-file-name'.

(fn &optional FILE)" t)
(autoload 'denote-dash-rename-file-using-front-matter "denote-dash"
"Rename FILE from its front matter, selecting FILE via `denote-dash-note-prompt'.
Same effect as `denote-rename-file-using-front-matter', except FILE
selection always uses the annotated, context-defaulting prompt.  That
command's own fallback is only Dired or `buffer-file-name' — outside
either, it errors instead of prompting at all.

(fn &optional FILE)" t)
(autoload 'denote-dash-hierarchy-actions-menu "denote-dash"
"Pick and run a rename/retag/sequence action on the hierarchy row at point.
Candidates come from `denote-dash--hierarchy-actions'; each is one of the
existing rename/retag/sequence commands. Refreshes the hierarchy view in
place afterward via `revert-buffer'." t)
(autoload 'denote-dash--denote-review-available-p "denote-dash"
"Return non-nil if `denote-review' is available.")
(autoload 'denote-dash-dispatch "denote-dash" nil t)
(register-definition-prefixes "denote-dash" '("ad:denote-dash--" "denote-dash-"))

;;; End of scraped data

(provide 'denote-dash-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; denote-dash-autoloads.el ends here
