;;; agent-shell-queue-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from agent-shell-menu.el

(autoload 'agent-shell-menu--switch-buffer "agent-shell-menu" "\
Switch to an agent-shell buffer with annotations.
Annotations include icon, status, title, cwd, and age.
Installed as `:override' advice on `agent-shell-switch-buffer' so the
enhanced picker is used under the original, upstream-compatible name
instead of introducing a second public entry point.  Respects
`agent-shell-prefer-viewport-interaction' like the original." t)
(autoload 'agent-shell-menu-select-session-mode "agent-shell-menu" "\
Select a session mode via `annotated-completing-read'.
Annotates each candidate with its description (the same text shown at
the start of an agent-shell session) and marks the active mode as
\"[current]\", instead of requiring the user to already know the
candidate list.  Unlike `agent-shell-cycle-session-mode' this prompts
instead of blindly advancing to the next mode.

Optionally, get notified of completion with ON-SUCCESS function.

(fn &optional ON-SUCCESS)" t)
(autoload 'agent-shell-menu-project-buffers "agent-shell-menu" "\
Return live agent-shell buffers sharing the current buffer's project directory.")
(autoload 'agent-shell-menu-switch-project-session "agent-shell-menu" "\
Switch to another agent-shell session in the same project directory." t)
(autoload 'agent-shell-menu-select-action "agent-shell-menu" "\
Pick a common agent-shell action and run it via `call-interactively'.
When a permission request is pending, permission responses are spliced
into the menu." t)
(autoload 'agent-shell-menu-resolve-permission "agent-shell-menu" "\
Resolve a pending permission prompt via `annotated-completing-read'." t)
(autoload 'agent-shell-menu-select-command "agent-shell-menu" "\
Insert one of the agent's advertised `/' commands at the prompt." t)
(autoload 'agent-shell-menu-send-file "agent-shell-menu" "\
Prompt for a file and send it to the current agent-shell session.
Uses `read-file-name' for file selection, integrating with Consult/Vertico." t)
(autoload 'agent-shell-menu-send-buffer "agent-shell-menu" "\
Pick a buffer and send its contents to the current agent-shell session.
File-visiting buffers are sent as @file references; others as raw text." t)
(autoload 'agent-shell-menu-select-collapse "agent-shell-menu" "\
Pick a collapse action via `annotated-completing-read'.
Offers bulk expand/collapse, per-category toggles, entries to flip the
three expand-by-default customization variables globally, and a
buffer-local variant that only changes the default for this session." t)
(autoload 'agent-shell-menu-session-info "agent-shell-menu" "\
Display a read-only ephemeral buffer with live session diagnostics.
Shows fragment count, agent uptime, queue options, queue depth, and
the underlying shell process uptime for the current agent-shell buffer." t)
(autoload 'agent-shell-menu-dispatch "agent-shell-menu" "\
agent-shell operations — navigate, act, send, queue, and session management.

(fn)" t)
(autoload 'agent-shell-queue-capture-menu "agent-shell-menu" "\
Enqueue and capture operations for the current agent-shell session.
Bound to \"e\" in `agent-shell-mode-map'; self-inserts at the idle prompt.

(fn)" t)
(register-definition-prefixes "agent-shell-menu" '("agent-shell-menu-"))


;;; Generated autoloads from agent-shell-queue.el

(autoload 'agent-shell-queue-capture "agent-shell-queue" "\
Open a capture buffer targeting BUF (nil adds to the unassigned queue).
When called interactively from an agent-shell buffer, targets that buffer.
With a prefix argument, opens an unassigned capture instead.

(fn &optional BUF)" t)
(autoload 'agent-shell-queue-enqueue "agent-shell-queue" "\
Queue PROMPT for BUF, optionally flagged for BACKGROUND execution.
Send immediately if BUF is idle and no DELAY-BEFORE is set, otherwise
store in the queue.  When called interactively, opens a capture buffer
for composing the prompt.  Optional DELAY-BEFORE and DELAY-AFTER specify
pre-dispatch and post-completion delays in seconds.

(fn PROMPT &optional BUF BACKGROUND DELAY-BEFORE DELAY-AFTER)" t)
(autoload 'agent-shell-queue-enqueue-clear "agent-shell-queue" "\
Enqueue a clear command for BUF.
Uses the resolved clear command for BUF as the prompt.

(fn &optional BUF)" t)
(autoload 'agent-shell-queue-capture-unassigned "agent-shell-queue" "\
Open a capture buffer to compose a prompt for the unassigned queue.
Unassigned items display in blue and can later be assigned to a shell via `t'." t)
(autoload 'agent-shell-queue-capture-from-region "agent-shell-queue" "\
Open a capture buffer pre-seeded with the active region text.
When no region is active, opens an empty capture.  BUF is the target
agent-shell buffer; nil adds to the unassigned queue.

(fn &optional BUF)" t)
(autoload 'agent-shell-queue-capture-from-context "agent-shell-queue" "\
Open a capture buffer pre-seeded with a string selected from context.
Candidates include thing-at-point, active region, current line, and
kill ring.  BUF is the target buffer; nil for unassigned queue.

(fn &optional BUF)" t)
(autoload 'agent-shell-queue-capture-from-clipboard "agent-shell-queue" "\
Open a capture buffer pre-seeded with the current clipboard contents.
BUF is the target agent-shell buffer; nil adds to the unassigned queue.

(fn &optional BUF)" t)
(autoload 'agent-shell-queue-add-directory "agent-shell-queue" "\
Add a new active item for PROMPT in directory queue DIR.  Save and refresh.

(fn PROMPT DIR &optional BACKGROUND DELAY-BEFORE DELAY-AFTER)" t)
(autoload 'agent-shell-queue-enqueue-directory "agent-shell-queue" "\
Open a capture buffer for directory queue DIR.

(fn DIR)" t)
(autoload 'agent-shell-queue-enqueue-emacs "agent-shell-queue" "\
Open an Emacs Lisp capture buffer to compose a form for BUF's queue.
The capture buffer is in `emacs-lisp-mode'.  Confirm with \\`C-c C-c',
cancel with \\`C-c C-k'.  When dispatched, the form is evaluated via
`eval'; errors are reported as messages and the item is marked done.
BUF may be nil to enqueue to the unassigned bucket.

(fn BUF)" t)
(autoload 'agent-shell-queue-enqueue-emacs-command "agent-shell-queue" "\
Enqueue an interactive COMMAND to run in Emacs for BUF's queue.
COMMAND is selected via `read-command' (completing-read over all commands).
When dispatched, the command is invoked with `call-interactively'.
BUF may be nil to enqueue to the unassigned bucket.

(fn COMMAND BUF)" t)
(autoload 'agent-shell-queue-enqueue-shell-eshell "agent-shell-queue" "\
Open a shell capture buffer to compose a command for eshell BUF.
The capture buffer is in `sh-mode'.  Confirm with \\`C-c C-c'.
BUF may be nil to enqueue to the unassigned bucket.

(fn BUF)" t)
(autoload 'agent-shell-queue-enqueue-shell-eat "agent-shell-queue" "\
Open a shell capture buffer to compose a command for eat BUF.
The capture buffer is in `sh-mode'.  Confirm with \\`C-c C-c'.
BUF may be nil to enqueue to the unassigned bucket.

(fn BUF)" t)
(autoload 'agent-shell-queue-pause "agent-shell-queue" "\
Pause dispatch for every known session (batch session-pause)." t)
(autoload 'agent-shell-queue-resume "agent-shell-queue" "\
Resume dispatch for every known session.
Alias for `agent-shell-queue-unpause-all-sessions'." t)
(autoload 'agent-shell-queue-flush "agent-shell-queue" "\
Force-save queue state to disk immediately." t)
(autoload 'agent-shell-queue-reload "agent-shell-queue" "\
Pause, flush, reload source code, and reload state from disk.
Stops the idle timer, drops all turn-complete subscriptions, reloads
`agent-shell-queue.el' from source, re-reads queue state from disk, and
reinstates subscriptions for buffers with active/running items.
Every known session is paused before reload — the session-paused list
survives the reload (it lives on `agent-shell-queue--queue', which `defvar'
does not reset) — so nothing dispatches until `agent-shell-queue-resume'
is called." t)
(autoload 'agent-shell-queue-clear-unparsable "agent-shell-queue" "\
Remove items whose struct fields cannot be read; print each to *Messages*.
Useful after a code reload that left in-memory structs with mismatched layouts.
When called interactively, prompts y/n/a for each candidate before removing it.
Affected buffer queues are paused and the queue state is saved." t)
(autoload 'agent-shell-queue-show-disk-state "agent-shell-queue" "\
Display the on-disk queue state file in a read-only popup buffer." t)
(autoload 'agent-shell-queue-buffer-open "agent-shell-queue" "\
Open (or refresh) the *agent-shell-queue* buffer." t)
(autoload 'agent-shell-queue-buffer-switch "agent-shell-queue" "\
Switch to the *agent-shell-queue* buffer in the current window." t)
(autoload 'agent-shell-queue-set-scope "agent-shell-queue" "\
Narrow the queue buffer view: choose global, a directory, or a specific buffer." t)
(autoload 'agent-shell-queue-scope-global "agent-shell-queue" "\
Reset the queue buffer to the global scope (show all items)." t)
(autoload 'agent-shell-queue-select-columns "agent-shell-queue" "\
Pick column display options via `annotated-completing-read'.
Offers bulk presets, per-column visibility toggles, and multi-line switch.
Changes take effect immediately via `agent-shell-queue-buffer-refresh'." t)
(autoload 'agent-shell-queue-buffer-inspect-item "agent-shell-queue" "\
Open a read-only raw-serialization view of the queue item at point.
Prompts for the serialization format (p=plist j=json y=yaml in the buffer)." t)
(autoload 'agent-shell-queue-item-view-inspect "agent-shell-queue" "\
Open a raw-serialization view of the item shown in this buffer.
Prompts for the serialization format (p=plist j=json y=yaml in the buffer)." t)
(autoload 'agent-shell-queue-export "agent-shell-queue" "\
Export items in the current scope to a read-only YAML buffer.
Multi-line prompt/response fields are formatted as literal block scalars." t)
(autoload 'agent-shell-queue-edit-task "agent-shell-queue" "\
Edit a queued item's prompt.
In `agent-shell-queue-mode' without SELECT (prefix argument): edit the item at
point immediately.  With SELECT, or when point carries no item, or when called
from outside `agent-shell-queue-mode': select via annotated-completing-read.
Candidates include all non-done, non-running items across all buffers.

(fn &optional SELECT)" t)
(autoload 'agent-shell-queue-raw-edit "agent-shell-queue" "\
Open the queue for direct YAML editing.
Every session not already paused is paused while the edit buffer is live.
Confirm changes with \\[agent-shell-queue-raw-edit-confirm];
cancel with \\[agent-shell-queue-raw-edit-cancel]." t)
(autoload 'agent-shell-queue-import "agent-shell-queue" "\
Import queue items from YAML.
With no prefix arg reads from clipboard; with prefix arg prompts for file.
For items whose ID exists, prompts to keep, replace, or assign new ID.

(fn &optional SOURCE)" t)
(autoload 'agent-shell-queue-fork-session "agent-shell-queue" "\
Fork the queue for SOURCE-BUF starting at FROM-ID into a new session.

Items at or after FROM-ID (by queue position among active/deferred/draft)
are moved to the new session.  When FROM-ID is nil, all eligible items
are moved.  The original session is paused during session creation.

OPTS is a plist with these keys:
  :fork-mode       Symbol `new' (default) or `fork'.
  :use-worktree    Non-nil — create a git worktree for the new session.
  :worktree-path   String — explicit worktree path (auto-generated when nil).
  :worktree-branch String — new branch name for the worktree.
  :capture-pending Non-nil — mark items at/after FROM-ID as `pending-fork'
                   in the original session instead of moving them, then
                   leave the session paused so new items can be inserted.

(fn SOURCE-BUF &optional FROM-ID OPTS)" t)
(autoload 'agent-shell-queue-release-pending-fork "agent-shell-queue" "\
Release all pending-fork items in BUF back to active status and resume dispatch.
BUF defaults to the current agent-shell session when called from one.

(fn &optional BUF)" t)
(autoload 'agent-shell-queue-insert-fork-before "agent-shell-queue" "\
Insert a fork task into BUF's queue immediately before ITEM-ID.
When ITEM-ID is nil, appends to the end of the queue.
When the fork task is dispatched (as an emacs item), it forks the queue
starting at the item that follows the fork task in the queue at dispatch time.
OPTS is the fork options plist (see `agent-shell-queue-fork-session').

(fn BUF &optional ITEM-ID OPTS)" t)
(autoload 'agent-shell-queue-insert-fork-after "agent-shell-queue" "\
Insert a fork task into BUF's queue immediately after ITEM-ID.
When ITEM-ID is nil, appends to the end of the queue.
When the fork task is dispatched, it forks the queue starting at the next
item after the fork task (determined dynamically at dispatch time).
OPTS is the fork options plist (see `agent-shell-queue-fork-session').

(fn BUF &optional ITEM-ID OPTS)" t)
(autoload 'agent-shell-queue-insert-pause "agent-shell-queue" "\
Insert a pause item into BUF's queue, optionally at 1-based POSITION.
If DURATION is specified (seconds), pause auto-resumes after DURATION.
When called interactively, prompts for target buffer (and duration with
prefix arg).

(fn &optional BUF POSITION DURATION)" t)
(autoload 'agent-shell-queue-insert-clear-context "agent-shell-queue" "\
Insert a context-drop item with PROMPT into BUF's queue.
When called interactively, prompts for target buffer and context text.

(fn PROMPT &optional BUF)" t)
(autoload 'agent-shell-queue-insert-wait "agent-shell-queue" "\
Insert a wait-until item into BUF's queue.
Prompts for a target date/time; uses `org-read-date' when available,
otherwise reads a string parseable by `date-to-time' (e.g. \"2026-05-16 14:30\").
When dispatched the item blocks the queue until the target time is reached,
then marks itself done and advances to the next item automatically.

(fn BUF)" t)
(autoload 'agent-shell-queue-buffer-fork "agent-shell-queue" "\
Fork the queue starting at the item at point into a new session.
Prompts interactively for fork options; uses annotated-completing-read when
called outside the queue buffer to build options without task-at-point context." t)
(autoload 'agent-shell-queue-buffer-insert-fork-before "agent-shell-queue" "\
Insert a fork queue item before the item at point.
Prompts for fork options interactively." t)
(autoload 'agent-shell-queue-buffer-insert-fork-after "agent-shell-queue" "\
Insert a fork queue item after the item at point.
Prompts for fork options interactively." t)
(autoload 'agent-shell-queue-disable-intercept-mode-all "agent-shell-queue" "\
Reset all live agent-shell buffers in queue-intercept mode to default." t)
(autoload 'agent-shell-queue-set-input-mode-default "agent-shell-queue" "\
Set `agent-shell-queue-input-mode-default' to MODE and sync sessions.
MODE is prompted interactively from the three valid options.
All live agent-shell buffers are immediately updated to the new default.

(fn MODE)" t)
(autoload 'agent-shell-queue-reset-all-input-modes "agent-shell-queue" "\
Reset all live agent-shell buffers to default input mode." t)
(autoload 'agent-shell-queue-toggle-intercept-default "agent-shell-queue" "\
Toggle queue-intercept as the default input mode and sync all sessions." t)
(autoload 'agent-shell-queue-toggle-only-default "agent-shell-queue" "\
Toggle queue-only as the default input mode and sync all sessions." t)
(autoload 'agent-shell-queue-ready-capture "agent-shell-queue" "\
Clear the ready overlay and open the queue enqueue dispatch menu.
Any keypress in queue-only mode at the idle prompt routes here, giving
access to all registered item kinds rather than prompt-only capture." t)
(autoload 'agent-shell-queue-only-mode "agent-shell-queue" "\
Route all agent-shell input through the queue; show <ready> when idle.

This is a minor mode.  If called interactively, toggle the
`Agent-Shell-Queue-Only mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `agent-shell-queue-only-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "agent-shell-queue" '("agent-shell-queue-" "savehist-additional-variables" "with-agent-shell-queue"))


;;; Generated autoloads from agent-shell-queue-db.el

(autoload 'agent-shell-queue-db-enable "agent-shell-queue-db" "\
Activate the SQLite persistence backend for agent-shell-queue.
When DB-FILE is non-nil, use it as the database path; otherwise the default
path under `user-emacs-directory' is used (see `agent-shell-queue-db-file').
Sets `agent-shell-queue-save-function', `agent-shell-queue-load-function',
and `agent-shell-queue-state-file-function' to SQLite-aware variants.
Saves the previous values so `agent-shell-queue-db-disable' can restore them.

(fn &optional DB-FILE)" t)
(autoload 'agent-shell-queue-db-disable "agent-shell-queue-db" "\
Deactivate the SQLite backend and revert to the previous persistence settings.
Closes the database connection." t)
(autoload 'agent-shell-queue-db-show-state "agent-shell-queue-db" "\
Display the SQLite database contents in a read-only popup buffer.
Shows per-bucket item counts and a tabular dump of all persisted rows." t)
(autoload 'agent-shell-queue-db-export "agent-shell-queue-db" "\
Export current queue items from SQLite to a YAML buffer.
Loads current state from the DB then delegates to `agent-shell-queue-export'." t)
(autoload 'agent-shell-queue-db-import "agent-shell-queue-db" "\
Import queue items from YAML into the SQLite database.
SOURCE follows the same convention as `agent-shell-queue-import':
nil or `clipboard' reads from the clipboard; `file' prompts for a file.
After importing, the DB is flushed immediately.

(fn &optional SOURCE)" t)
(register-definition-prefixes "agent-shell-queue-db" '("agent-shell-queue-db-"))


;;; Generated autoloads from agent-shell-queue-org.el

(autoload 'agent-shell-queue-org-refile-from-heading "agent-shell-queue-org" "\
Capture the current org heading's subtree text into the agent-shell-queue.
Opens a queue capture buffer pre-seeded with the heading content.
With prefix arg REMOVE-ORIGINAL, delete the original subtree immediately
after opening the capture buffer.

(fn &optional REMOVE-ORIGINAL)" t)
(register-definition-prefixes "agent-shell-queue-org" '("agent-shell-queue-org--"))


;;; Generated autoloads from agent-shell-queue-persistence.el

(autoload 'agent-shell-queue-show-write-log "agent-shell-queue-persistence" "\
Display the in-memory write log in a readable buffer." t)
(autoload 'agent-shell-queue-buffer-archive "agent-shell-queue-persistence" "\
Archive the item at point to the archive file and remove it from the queue.
Archiving must be enabled via `agent-shell-queue-archive-enabled'.
The destination path is provided by `agent-shell-queue-archive-file-function'." t)
(autoload 'agent-shell-queue-archive-done-n "agent-shell-queue-persistence" "\
Archive the N oldest done items across all queues.
Errors if archiving is not enabled.

(fn N)" t)
(autoload 'agent-shell-queue-archive-done-all "agent-shell-queue-persistence" "\
Archive all done items across all queues.
Errors if archiving is not enabled or no done items exist." t)
(autoload 'agent-shell-queue-toggle-archive "agent-shell-queue-persistence" "\
Toggle `agent-shell-queue-archive-enabled' and report the new state." t)
(autoload 'agent-shell-queue-load-archive "agent-shell-queue-persistence" "\
Import items from the JSONL archive file into the queue as active items.
FILE defaults to the path returned by `agent-shell-queue-archive-file-function';
when called interactively with a prefix argument, prompts for a file path.

(fn &optional FILE)" t)
(autoload 'agent-shell-queue-restore-from-backup "agent-shell-queue-persistence" "\
Restore queue items from a versioned backup via annotated-completing-read.
Lists backup files in the safe-save directory newest-first.  Only items whose
item-id is not already present in the live queue are added, so the operation
is safe to run against an active queue.  Saves and refreshes after merging." t)
(register-definition-prefixes "agent-shell-queue-persistence" '("agent-shell-queue-"))

;;; End of scraped data

(provide 'agent-shell-queue-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; agent-shell-queue-autoloads.el ends here
