;;; ollama-tailnet-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ollama-tailnet.el

(autoload 'ollama-tailnet-bind-hud-keys "ollama-tailnet" "\
Bind `ollama-tailnet' commands to `hud-robot-ollama-tailnet-map' if available.")


;;; Generated autoloads from ollama-tailnet-control.el

(autoload 'ollama-tailnet-service-restart "ollama-tailnet-control" "\
Restart systemd ollama.service on HOST-NAME.

(fn HOST-NAME)" t)
(autoload 'ollama-tailnet-service-status "ollama-tailnet-control" "\
Check systemd ollama.service status on HOST-NAME and display output.

(fn HOST-NAME)" t)
(autoload 'ollama-tailnet-pull-model "ollama-tailnet-control" "\
Pull MODEL-NAME on HOST-NAME with live progress reporting.

(fn HOST-NAME MODEL-NAME)" t)
(autoload 'ollama-tailnet-status "ollama-tailnet-control" "\
Display status summary buffer for all registered tailnet Ollama hosts." t)
(register-definition-prefixes "ollama-tailnet-control" '("ollama-tailnet--systemctl-cmd"))


;;; Generated autoloads from ollama-tailnet-gptel.el

(autoload 'ollama-tailnet-resolve-model "ollama-tailnet-gptel" "\
Resolve HOST-MODEL-SPEC string or symbol (e.g. \"derrida/default\", \"derrida/gemma4:32b\", or 'derrida/default)
to a cons cell `(HOST-STRUCT . MODEL-NAME)'.

If spec is a simple host name (e.g. \"derrida\"), model defaults to host's `default-model'.
If host is omitted or not registered, applies `ollama-tailnet-fallback-strategy'.

(fn HOST-MODEL-SPEC)")
(autoload 'ollama-tailnet-get-gptel-backend "ollama-tailnet-gptel" "\
Return a gptel backend struct corresponding to HOST-MODEL-SPEC.
HOST-MODEL-SPEC can be a string (e.g. \"derrida/default\") or symbol (e.g. 'derrida/default).

(fn HOST-MODEL-SPEC)")
(autoload 'ollama-tailnet-set-gptel-backend "ollama-tailnet-gptel" "\
Set `gptel-backend' and `gptel-model' for HOST-MODEL-SPEC.
If LOCAL is non-nil, set buffer-locally; otherwise set globally.

(fn HOST-MODEL-SPEC &optional LOCAL)" t)
(autoload 'ollama-tailnet-probe-host-default "ollama-tailnet-gptel" "\
Query remote Ollama /api/tags endpoint for HOST-NAME asynchronously.
Updates host models list and default-model if available.
Invokes CALLBACK with (HOST-STRUCT SUCCESS-P) when complete.

(fn HOST-NAME &optional CALLBACK)")
(register-definition-prefixes "ollama-tailnet-gptel" '("ollama-tailnet-"))


;;; Generated autoloads from ollama-tailnet-models.el

(autoload 'ollama-tailnet-search-model "ollama-tailnet-models" "\
ACR-search the public Ollama library and pull the selected model." t)
(autoload 'ollama-tailnet-models-mode "ollama-tailnet-models" "\
Major mode for browsing and managing Ollama models across tailnet hosts.

Columns: Host | Model | Size | Modified | Status
  Status: up to date / update avail / unknown (until checked via `c')

\\{ollama-tailnet-models-mode-map}

(fn)" t)
(autoload 'ollama-tailnet-models "ollama-tailnet-models" "\
Open the model dashboard across all registered tailnet hosts." t)
(register-definition-prefixes "ollama-tailnet-models" '("ollama-tailnet-"))


;;; Generated autoloads from ollama-tailnet-vars.el

(autoload 'ollama-tailnet-discover-hosts "ollama-tailnet-vars" "\
Dynamically discover and register all online Tailnet peer nodes running Ollama." t)
(autoload 'ollama-tailnet-register-host "ollama-tailnet-vars" "\
Register a tailnet node NAME (symbol or string) with PROPS plist.

Recognized PROPS:
`:host' or `:address' - Host string (e.g., \"derrida.tailnet-name.ts.net:11434\" or \"127.0.0.1:11434\")
`:default-model'     - String default model name (e.g., \"gemma4:27b\")
`:models'            - List of model strings (e.g., '(\"gemma4:27b\" \"gemma4:32b\"))
`:local-p'           - Boolean indicating if host is local (default: auto-detected)

(fn NAME &rest PROPS)")
(autoload 'ollama-tailnet-get-host "ollama-tailnet-vars" "\
Retrieve registered `ollama-tailnet-host' structure by NAME (symbol or string).

(fn NAME)")
(autoload 'ollama-tailnet-list-hosts "ollama-tailnet-vars" "\
Return a list of all registered `ollama-tailnet-host' structures.")
(autoload 'ollama-tailnet-setup-laptop-presets "ollama-tailnet-vars" "\
Register standard laptop and server profiles from `ollama-tailnet-preset-profiles'." t)
(register-definition-prefixes "ollama-tailnet-vars" '("ollama-tailnet-"))

;;; End of scraped data

(provide 'ollama-tailnet-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ollama-tailnet-autoloads.el ends here
