;;; gen-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from gen.el

(defvar cl-struct-gen-tags)
(with-suppressed-warnings ((lexical infinite exhausted peeked iter cl-tag-slot)) (eval-and-compile (cl-defsubst gen-p (cl-x) (declare (side-effect-free error-free) (pure t)) (and (memq (type-of cl-x) cl-struct-gen-tags) t)) (define-symbol-prop 'gen 'cl-deftype-satisfies 'gen-p)) (cl-defsubst gen-iter (cl-x) "Access slot \"iter\" of `gen' struct CL-X.
The raw generator.el closure iterator." (declare (side-effect-free t)) (progn (or (gen-p cl-x) (signal 'wrong-type-argument (list 'gen cl-x))) (aref cl-x 1))) (cl-defsubst gen-peeked (cl-x) "Access slot \"peeked\" of `gen' struct CL-X.
A cons (VALUE . t) when a value has been peeked, else nil." (declare (side-effect-free t)) (progn (or (gen-p cl-x) (signal 'wrong-type-argument (list 'gen cl-x))) (aref cl-x 2))) (cl-defsubst gen-exhausted (cl-x) "Access slot \"exhausted\" of `gen' struct CL-X.
Non-nil when the iterator has signaled `iter-end-of-sequence'." (declare (side-effect-free t)) (progn (or (gen-p cl-x) (signal 'wrong-type-argument (list 'gen cl-x))) (aref cl-x 3))) (cl-defsubst gen-infinite (cl-x) "Access slot \"infinite\" of `gen' struct CL-X.
Non-nil when the generator is known to be infinite." (declare (side-effect-free t)) (progn (or (gen-p cl-x) (signal 'wrong-type-argument (list 'gen cl-x))) (aref cl-x 4))) (cl-defsubst gen--make (&cl-defs (nil (cl-tag-slot) (iter nil :documentation "The raw generator.el closure iterator.") (peeked nil :documentation "A cons (VALUE . t) when a value has been peeked, else nil.") (exhausted nil :documentation "Non-nil when the iterator has signaled `iter-end-of-sequence'.") (infinite nil :documentation "Non-nil when the generator is known to be infinite.")) &key iter peeked exhausted infinite) "Constructor for objects of type `gen'." (declare (side-effect-free t)) (record 'gen iter peeked exhausted infinite)))
(autoload 'gen-wrap "gen" "\
Wrap ITER-OR-GEN in a `gen' struct for `seq.el' compatibility.
If ITER-OR-GEN is already a `gen', return it unchanged (updating
its infinite flag if INFINITE is non-nil).
If ITER-OR-GEN is a raw `generator.el' iterator closure or function, wrap it.
When INFINITE is non-nil, marks the generator as infinite so draining operations
can issue a warning before attempting full consumption.

Note on infinite generators: lazy operations (`seq-map', `seq-filter',
`seq-take', `seq-take-while', `seq-drop', `seq-drop-while', etc.) are safe
on infinite generators.  Draining operations (`seq-length', `seq-reverse',
`seq-sort', `seq-into', etc.) will consume forever unless bounded.

(fn ITER-OR-GEN &optional INFINITE)")
(register-definition-prefixes "gen" '("gen--"))

;;; End of scraped data

(provide 'gen-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; gen-autoloads.el ends here
