;;; company-emojify-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from company-emojify.el

(autoload 'company-emojify "company-emojify" "\
Company backend for Emojify.

Arguments COMMAND, ARG and IGNORED are standard arguments from `company-mode`.

(fn COMMAND &optional ARG &rest IGNORED)" t)
(register-definition-prefixes "company-emojify" '("company-emojify-"))

;;; End of scraped data

(provide 'company-emojify-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; company-emojify-autoloads.el ends here
