;;; denote-notion-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from denote-notion.el

(autoload 'denote-notion-push "denote-notion" "\
Push FILE (default the current buffer's file) to Notion as a page.
If FILE is not yet Notion-tracked, PARENT — a (TYPE . ID) cons, where TYPE
is one of the symbols `page', `database', or `data-source' — is required:
prompted interactively unless `denote-notion-default-parent' is set — and
a new page is created.  If FILE is already tracked, its Notion page is
updated, unless the remote page has changed since the last sync, in which
case a conflict is signaled; pass FORCE (or the prefix argument,
interactively) to overwrite anyway.

(fn &optional FILE PARENT FORCE)" t)
(autoload 'denote-notion-pull "denote-notion" "\
Pull a Notion page into a denote note, creating or refreshing as needed.

With PAGE-ID (an id, or a Notion URL): pull that specific page.  If
TARGET-FILE, the current buffer, or any other denote note already tracks
that page's id (see `denote-notion--find-tracked-file'), replace that
file's body and refresh its tracking fields in place.  Otherwise create a
new tracked denote note from the page's properties and body — so
re-running an import on a page you already have never creates a
duplicate note, even from a buffer other than the one already tracking it.

Without PAGE-ID: refresh TARGET-FILE (or the current buffer) using its
own already-tracked `notion_id', so \"pull this specific page\" and
\"re-pull whatever I'm already looking at\" are the same command.
Errors if there's no tracked file to fall back on.

Interactively, PAGE-ID is only prompted for when the current buffer isn't
already a tracked Notion note — otherwise this dwim-refreshes the current
buffer directly, with no prompt at all.

(fn &optional PAGE-ID TARGET-FILE)" t)
(register-definition-prefixes "denote-notion" '("denote-notion-"))

;;; End of scraped data

(provide 'denote-notion-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; denote-notion-autoloads.el ends here
