;;; elsqlite-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from elsqlite.el

(autoload 'elsqlite "elsqlite" "\
Open SQLite database DB-FILE in ELSQLite browser.

(fn DB-FILE)" t)
(defalias 'elsqlite-browser #'elsqlite)
(autoload 'elsqlite-enable-auto-open "elsqlite" "\
Enable automatic opening of SQLite files in ELSQLite.
Adds a hook to `find-file-hook' that opens .db, .sqlite, and .sqlite3
files in ELSQLite instead of as raw bytes." t)
(autoload 'elsqlite-disable-auto-open "elsqlite" "\
Disable automatic opening of SQLite files in ELSQLite." t)
(register-definition-prefixes "elsqlite" '("elsqlite-"))


;;; Generated autoloads from elsqlite-completion.el

(register-definition-prefixes "elsqlite-completion" '("elsqlite-completion-"))


;;; Generated autoloads from elsqlite-db.el

(register-definition-prefixes "elsqlite-db" '("elsqlite-db-"))


;;; Generated autoloads from elsqlite-sql.el

(register-definition-prefixes "elsqlite-sql" '("elsqlite-sql-"))


;;; Generated autoloads from elsqlite-table.el

(autoload 'elsqlite-evil-setup "elsqlite-table" "\
Set up Evil mode keybindings for ELSQLite.
Call this function in your config if you use Evil mode." t)
(register-definition-prefixes "elsqlite-table" '("elsqlite-"))

;;; End of scraped data

(provide 'elsqlite-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; elsqlite-autoloads.el ends here
