;;; denote-tree-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from denote-tree.el

(autoload 'denote-tree-hierarchy-toggle-fold-sequence "denote-tree"
"Toggle persistent folding of the sequence section at point.
Adds or removes the root sequence at point from
`denote-tree-hierarchy-fold-sequences' — remembered across sessions via
`savehist-mode', not a static default — and folds or unfolds the section
to match immediately." t)
(autoload 'denote-tree-hierarchy-clear-fold-sequences "denote-tree"
"Forget every sequence toggled to stay folded, then refresh the view." t)
(autoload 'denote-tree-note-prompt "denote-tree"
"Read a Denote note file via an annotated-completing-read UI.
Candidates cover FILES, or every note in `denote-directory-files' when nil.
PROMPT overrides the default prompt text.  DEFAULT-FILE, or
`denote-tree--file-at-point' when nil, pre-selects a candidate.

(fn &optional PROMPT DEFAULT-FILE FILES)")
(autoload 'denote-tree-lint-sequences "denote-tree"
"Show all Denote notes whose filename and frontmatter signatures are misaligned." t)
(autoload 'denote-tree-fix-sequence-frontmatter "denote-tree"
"Fix frontmatter signature to match filename for note at point or file.
Resolves target file via `denote-tree--file-at-point', so it works from
`denote-tree-mode', `denote-sequence-hierarchy-mode', Dired, or a visited
Denote buffer." t)
(autoload 'denote-tree-fix-all-sequence-frontmatter "denote-tree"
"Fix frontmatter for mismatched Denote notes, filename as truth." t)
(autoload 'denote-tree-flymake "denote-tree"
"Flymake backend for Denote sequence alignment diagnostics.
Reports a warning diagnostic when a visited note has mismatched
filename and frontmatter signatures.

(fn REPORT-FN &rest ARGS)")
(autoload 'denote-tree-setup-flymake "denote-tree"
"Enable Flymake integration for Denote sequence alignment in the current buffer." t)
(autoload 'denote-tree-repack-children "denote-tree"
"Compact direct children of PREFIX so their last segment has no gaps.
Renames each child's entire subtree (child and all descendants) so that
descendants stay consistent with their parent's new sequence.  Children
are ordered by sequence value (not lexicographically, so \"10\" sorts
after \"2\" rather than before it), and the whole batch of renames is
staged through temporary signatures together so that repacking multiple
children at once never merges two of them into the same destination.

Before touching any file, shows a preview buffer listing every rename
that would happen and asks for confirmation; declining leaves every file
untouched.  Works from `denote-tree-mode' or interactively.

(fn PREFIX)" t)
(autoload 'denote-tree-swap-with-parent "denote-tree"
"Swap the sequence of the note at point with its direct parent.
Both nodes must have files in the denote directory.  Uses a three-step
rename (child→tmp, parent→child-seq, tmp→parent-seq) to avoid collision,
then fixes frontmatter signatures on both files." t)
(autoload 'denote-tree-swap-with-previous "denote-tree"
"Swap the note at point, with its subtree, with its previous sibling.
Descendants of both nodes move along with their parent, so the whole
subtrees exchange positions.  See also `denote-tree-swap-with-parent'." t)
(autoload 'denote-tree-swap-with-next "denote-tree"
"Swap the note at point, with its subtree, with its next sibling.
Descendants of both nodes move along with their parent, so the whole
subtrees exchange positions.  See also `denote-tree-swap-with-parent'." t)
(autoload 'denote-tree-reparent "denote-tree"
"Re-parent CURRENT-FILE to be a child of FILE-WITH-SEQUENCE.
Wraps `denote-sequence-reparent'.  That command's own interactive spec
resolves CURRENT-FILE via `denote-sequence--get-current-file-for-renaming'
and then, purely to build the target prompt's label text, calls the same
private file-or-prompt helper a second time — doubling the raw \"Rename
FILE Denote-style\" prompt whenever neither Dired nor a visited buffer is
in scope, which is exactly the case from a `denote-dash' or
sequence-hierarchy buffer.  This resolves CURRENT-FILE once via
`denote-tree--target-file' and reuses it for the label instead.

FILE-WITH-SEQUENCE may be nil, meaning \"make CURRENT-FILE a new top-level
sequence instead of a child of anything\" — plain `denote-sequence-reparent'
has no such path; it can only reparent onto another file.  Interactively
this is offered as its own y-or-n-p question before the child-of prompt,
so promoting a note out of its hierarchy doesn't require reaching for
`denote-tree-renumber-recursive' and typing a sequence by hand.

Only offers the \"reparent recursively?\" question when CURRENT-FILE
actually has descendants; a leaf note is reparented directly with no
recursion question at all, since recursing over zero descendants is a
no-op.  When it does have descendants and RECURSIVE ends up non-nil, the
multi-file rename goes through `denote-tree--reparent-recursive-apply',
which previews and confirms before touching any file; see that function.

Suppresses `denote-rename-confirmations' for the duration: this is a single
logical operation, and per-file prompting (as `denote-rename-file' does by
default) would be unusable for any subtree beyond a couple of files.

(fn CURRENT-FILE FILE-WITH-SEQUENCE &optional RECURSIVE)" t)
(autoload 'denote-tree-reparent-recursive "denote-tree"
"Re-parent CURRENT-FILE and all descendants to be children of FILE-WITH-SEQUENCE.
FILE-WITH-SEQUENCE may be nil, meaning \"promote to a new top-level
sequence\"; see `denote-tree-reparent' for the full explanation.

Direct entry point for the recursive case; see `denote-tree-reparent' for
the interactive command that asks whether to recurse instead of requiring
a separate command.  Still previews and confirms via
`denote-tree--reparent-recursive-apply' whenever CURRENT-FILE has
descendants; only a genuinely single-file case is prompt-free.

(fn CURRENT-FILE FILE-WITH-SEQUENCE)" t)
(autoload 'denote-tree-renumber-recursive "denote-tree"
"Renumber CURRENT-FILE to NEW-SEQ, renumbering all descendants to match.
Like `denote-tree-reparent-recursive', but NEW-SEQ is the target sequence
itself rather than derived as a new child of another file's sequence — use
this to move a subtree to a specific sequence ID instead of appending it
under a parent.

Builds the plan via `denote-tree--recursive-reseq-plan' and applies it via
`denote-tree--recursive-reseq-confirm-and-apply' — previewing and
confirming whenever CURRENT-FILE has descendants, applying directly
without a prompt when it does not.

(fn CURRENT-FILE NEW-SEQ)" t)
(autoload 'denote-tree--following-siblings "denote-tree"
"Return direct siblings of SEQ-ID at or after SEQ-ID, in descending order.

(fn SEQ-ID)")
(autoload 'denote-tree-insert-sequence-note "denote-tree"
"Insert a new note at the current note's sequence position.
All following siblings are shifted forward by one to make room.
Works from `denote-tree-mode' (note at point), a Denote note buffer,
or prompts for a file." t)
(autoload 'denote-tree-retag-sequence "denote-tree"
"Add, remove, or replace a keyword across a sequence and all its descendants.
Resolves the target sequence from the note at point in `denote-tree-mode' or
`denote-sequence-hierarchy-mode', the current buffer file, or a prompt.

Only files actually affected by the chosen operation are renamed — see
`denote-tree--retag-apply' for the exact per-operation semantics; in
particular `replace' never adds the new keyword to a file that didn't
already carry the old one." t)
(register-definition-prefixes "denote-tree" '("denote-tree-"))

;;; End of scraped data

(provide 'denote-tree-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; denote-tree-autoloads.el ends here
