;;; xtdlib-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from xtd-dash.el

(register-definition-prefixes "xtd-dash" '("--" "-append" "-c" "-f" "-in-place" "-join" "-l" "-map" "-reverse" "-s" "-unwind" "larger" "option-set-p" "smaller"))


;;; Generated autoloads from xtd-f.el

(register-definition-prefixes "xtd-f" '("f-"))


;;; Generated autoloads from xtd-ht.el

(register-definition-prefixes "xtd-ht" '("ht-"))


;;; Generated autoloads from xtd-macro.el

(register-definition-prefixes "xtd-macro" '("build-symbol-name" "disabled" "make-run-hooks-function-for" "merge-predicate-functions" "pos-arg" "slow-op-" "with-" "xtd--resolve-hooks"))


;;; Generated autoloads from xtd-project.el

(autoload 'buffer-derived-mode-p "xtd-project" "\
Returns t when the major-mode of `buffer' is or is derived from `mode.'

(fn BUFFER MODE)")
(autoload 'mode-buffers-for-project "xtd-project" "\
Return buffers in the current project whose major mode derives from MODE.
MODE defaults to `major-mode' of the calling buffer. Uses `approximate-project-buffers'
to determine project membership.

(fn &optional &key (MODE major-mode))")
(autoload 'mode-buffers "xtd-project" "\
Return all live buffers whose major mode derives from MODE.
MODE defaults to `major-mode' of the calling buffer. Searches across all buffers,
not just the current project.

(fn &optional (MODE major-mode))")
(autoload 'approximate-project-root "xtd-project" "\
Return the current project root, falling back to `default-directory'.")
(autoload 'approximate-project-name "xtd-project" "\
Return the current project name, falling back to the directory basename.")
(autoload 'approximate-project-buffers "xtd-project" "\
Return buffers belonging to the current project.")
(register-definition-prefixes "xtd-project" '("compile-buffer-name"))


;;; Generated autoloads from xtd-s.el

(register-definition-prefixes "xtd-s" '("resolve-plural-form" "s-" "xtdlib--symbol-name-punctuation"))

;;; End of scraped data

(provide 'xtdlib-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; xtdlib-autoloads.el ends here
