;;; denote-explore-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from denote-explore.el

(autoload 'denote-explore-count-notes "denote-explore" "\
Count number of Denote notes and attachments.
A note is defined by `denote-file-types', anything else is an attachment.
Count only ATTACHMENTS by prefixing with universal argument.

(fn &optional ATTACHMENTS)" t)
(autoload 'denote-explore-count-keywords "denote-explore" "\
Count distinct Denote keywords." t)
(autoload 'denote-explore-barchart-timeline "denote-explore" "\
Draw a column chart with the number of notes per year." t)
(autoload 'denote-explore-random-note "denote-explore" "\
Jump to a random Denote file and optionally INCLUDE-ATTACHMENTS.
With universal argument the sample includes attachments.

(fn &optional INCLUDE-ATTACHMENTS)" t)
(autoload 'denote-explore-random-link "denote-explore" "\
Jump to a random linked from current buffer note.
With universal argument the sample includes links to ATTACHMENTS.

(fn &optional ATTACHMENTS)" t)
(autoload 'denote-explore-random-keyword "denote-explore" "\
Jump to a random note with selected keyword(s).

- Select one or more keywords from the active Denote buffer.
- Override the completion option by adding free text
- Use \"*\" to select all listed keywords.

Selecting multiple keywords requires `denote-sort-keywords' to be non-nil
or the target keywords are in the same order as the selection.

With universal argument the sample will INCLUDE-ATTACHMENTS.

(fn &optional INCLUDE-ATTACHMENTS)" t)
(autoload 'denote-explore-random-regex "denote-explore" "\
Jump to a random not matching a regular expression REGEX.
Use Universal Argument to INCLUDE-ATTACHMENTS

(fn REGEX &optional INCLUDE-ATTACHMENTS)" t)
(autoload 'denote-explore-duplicate-notes "denote-explore" "\
Identify duplicate Denote IDs and EXCLUDE-EXPORTS.

If EXCLUDE-EXPORTS is nil, check Denote IDs, otherwise use file names without
extension. Using the universal argument excludes exported Denote files from
duplicate detection.

Duplicate files are displayed in a temporary buffer with links to the
suspected duplicates.

(fn &optional EXCLUDE-EXPORTS)" t)
(autoload 'denote-explore-duplicate-notes-dired "denote-explore" "\
Identify duplicate Denote IDs or FILENAMES.

If FILENAMES is nil, check Denote IDs, otherwise use complete file names.
Using the FILENAMES option (or using the universal argument) excludes
exported Denote files from duplicate-detection.

Duplicate files are displayed `find-dired'.

(fn &optional FILENAMES)" t)
(autoload 'denote-explore-single-keywords "denote-explore" "\
Select a note or attachment with a keyword that is only used once." t)
(autoload 'denote-explore-zero-keywords "denote-explore" "\
Select a note or attachment without any keywords." t)
(autoload 'denote-explore-rename-keyword "denote-explore" "\
Rename or remove keyword(s) across the Denote collection.

Use an empty string as new keyword to remove the selection.

When selecting more than one existing keyword, all selected terms are renamed
to the new version or removed.

The filename is taken as the source of truth for attchments and the front matter
for notes.

All open Denote note buffers should be saved for this function to work reliably." t)
(autoload 'denote-explore-sync-metadata "denote-explore" "\
Synchronise filenames with the metadata for all Denote notes.

The front matter is the source of truth.
- Keywords are saved alphabetically.
- The identifier remains unchanged

All open Denote note buffers need to be saved before invoking this function." t)
(autoload 'denote-explore-missing-links "denote-explore" "\
Display a read-only Org buffer with missing Denote and file links.

Follow the links in the tables to review the suspect links." t)
(autoload 'denote-explore-barchart-keywords "denote-explore" "\
Create a barchart with the top N most used Denote keywords.

(fn N)" t)
(autoload 'denote-explore-barchart-filetypes "denote-explore" "\
Visualise the Denote file types for notes and/or attachments.
With universal argument only visualises ATTACHMENTS, which excludes file
types listed in `denote-file-type-extensions'.

(fn &optional ATTACHMENTS)" t)
(autoload 'denote-explore-barchart-degree "denote-explore" "\
Visualise the degree for each Denote file (total links and backlinks).
The universal argument includes TEXT-ONLY files in the analyis.

(fn &optional TEXT-ONLY)" t)
(autoload 'denote-explore-barchart-backlinks "denote-explore" "\
Visualise the number of backlinks for N nodes in the Denote network.

(fn N)" t)
(autoload 'denote-explore-isolated-files "denote-explore" "\
Identify Denote files without (back)links.
Using the universal argument excludes attachments (TEXT-ONLY).

Files which have keywords listed in
`denote-explore-isolated-ignore-keywords' will not be included.

(fn &optional TEXT-ONLY)" t)
(autoload 'denote-explore-network "denote-explore" "\
Generate a network of Denote files or keywords by selecting a type.

- Community: Network of notes matching a regular expression.
  Links to notes not matching the regular expression are pruned.
- Neighbourhood: Network of notes from a root at a given depth.
  Depth = 1 notes linked to root; depth 2: notes linked to linked notes, etc.
- Sequence: Hierarchy of signatures, split at the = symbol.
- Keywords: Network of keywords.  Each note with two or more keywords
  forms a complete graph, which are merged into a weighted undirected graph.

Refer to the manual for a more detailed explanation.

Using the universal argument excludes attachments from the analysis (TEXT-ONLY).

The code generates a nested association list that holds all relevant metadata
for the selected graph:

- Meta data e.g.: `((directed . t) (type . \"Keywords\"))'
- Association list of nodes and their degrees, e.g.:
  `(((id . \"20210104T194405\") (name . \"Platonic Solids\") (keywords \"math\"'
  `\"geometry\") (type . \"org\") (degree . 4)) ...)'.
  In the context of Denote, the degree of a node is the unweighted sum of links
  and backlinks from and to a note.
- Association list of edges and their weights, e.g.:
  `(((source . \"20220529T190246\") (target . \"20201229T143000\")'
  `(weight . 1)) ...)'.
  The weight of an edge indicates the number of time it occurs in the graph.

This list is passed on to an encoding function to generate the desired graph
format.  In the last step, a visualisation function displays the graph in the
external web browser, except for the GEXF format.

The parameters for the generated graph are stored in
`denote-explore-network-previous', which is used to renegerate the same graph
after making changes to notes with `denote-explore-network-regenerate'.

The `denote-explore-graph-types' variable stores the functions required to
generate and regenerate graphs.

The `denote-explore-network-graph-formats' variable contains a list of functions
to encode and display each graph format.

(fn &optional TEXT-ONLY)" t)
(autoload 'denote-explore-network-regenerate "denote-explore" "\
Recreate the most recent Denote graph with external software.
Universal argument excludes attachments from the analysis (TEXT-ONLY).

(fn &optional TEXT-ONLY)" t)
(autoload 'denote-explore-list-keywords "denote-explore" "\
List all Denote keywords with the number of notes that use each keyword.

This command:
- Scans `denote-directory` and collects per-note keywords.
- Builds a (KEYWORD . COUNT) table, where COUNT is the number of notes
  that include KEYWORD (one count per note, even if repeated in metadata).
- Sorts by COUNT descending, then KEYWORD ascending.
- When called with universal argument, the table is sorted ALPHABETICALLY
- When called interactively, displays a two-column table and appends
  a footer with the total number of distinct keywords and the sum of counts.

Returns a plist for programmatic use:
  (:table ALIST :keywords N-DISTINCT :notes SUM-OF-COUNTS).

(fn &optional ALPHABETICALLY)" t)
(register-definition-prefixes "denote-explore" '("denote-explore-"))


;;; End of scraped data

(provide 'denote-explore-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; denote-explore-autoloads.el ends here
