;;; ercn-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ercn.el

(autoload 'ercn-match "ercn" "\
Extracts information from the buffer and fires `ercn-notify-hook' if needed.")
(autoload 'ercn-fix-hook-order "ercn" "\
Notify before timestamps are added

(fn &rest _)")
(when (boundp 'erc-modules) (ercn--add-erc-module))
(eval-after-load 'erc '(progn (require 'ercn) (ercn--add-erc-module)))
(register-definition-prefixes "ercn" '("ercn-"))

;;; End of scraped data

(provide 'ercn-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ercn-autoloads.el ends here
