;;; org-docsgen-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from org-docsgen.el

(autoload 'org-docsgen-run "org-docsgen" "\
Generate org-mode API documentation and princ it to stdout.

EL-FILES is a list of .el paths to document; defaults to all non-test .el
files in the directory of the current buffer.

SCOPE controls which definitions are included:
  `exported'    -- all public symbols (no -- in name)
  `autoloaded'  -- only ;;;###autoload-annotated symbols
  `interactive' -- all interactive commands
  A list        -- explicit symbol names, emitted in order

INCLUDE-KINDS lists additional kinds beyond what SCOPE selects:
  `variables' -- defvar / defconst / defvar-local
  `customs'   -- defcustom

NAMESPACE is a string prefix (e.g. \"sprite\").  A `(defvar NAME nil)'
form whose NAME does not start with NAMESPACE is treated as a foreign
forward declaration and excluded.

SECTION-STYLE is `ruler' (default: long ;;;;... lines) or `triple-semi'
(;;; Section Name headers used by agent-shell-queue).

DOC-FILTER overrides `org-docsgen-doc-filter-function' for this run;
pass nil to emit docstring prose verbatim, unannotated.

(fn &key EL-FILES (SCOPE \\='exported) (INCLUDE-KINDS \\='(variables customs)) NAMESPACE (SECTION-STYLE \\='ruler) GROUP-BY (DOC-FILTER :default) (LINK-IMPL t) (LINK-STYLE \\='org))")
(autoload 'org-docsgen-regenerate-file "org-docsgen" "\
Regenerate the `org-docsgen-run' block in FILE and save it.
FILE may be any org file containing such a block -- a README, a file
under a docs/ directory, or anything else; there is nothing
README-specific about this command.
Interactively, defaults to the current buffer's file when it already
has a docsgen block, otherwise prompts with completion over `.org'
files found anywhere under `default-directory'.  Intended for use by
agent skills via emacsclient:
  emacsclient --eval \\='(org-docsgen-regenerate-file \"docs/api.org\")\\='

(fn FILE)" t)
(autoload 'org-docsgen-regenerate-directory "org-docsgen" "\
Regenerate every docsgen block among the `.org' files directly in DIR.
DIR defaults to `default-directory'.  Only files directly in DIR are
considered, not subdirectories -- use `org-docsgen-regenerate-file' with
its recursive completion, or call this once per directory, to cover a
whole tree.  Signals a `user-error' when DIR has no `.org' file with an
`org-docsgen-run' block.

(fn &optional DIR)" t)
(autoload 'org-docsgen-regenerate-dwim "org-docsgen" "\
Regenerate docsgen docs for the current context.
When the current buffer visits a file with an `org-docsgen-run' block,
regenerate that buffer in place.  Otherwise find and regenerate every
docsgen block among the `.org' files directly in `default-directory',
recursively under `default-directory' (e.g. docs/api.org), or falling
back to `approximate-project-root'." t)
(defalias 'org-docsgen-dwim #'org-docsgen-regenerate-dwim)
(register-definition-prefixes "org-docsgen" '("org-docsgen-"))

;;; End of scraped data

(provide 'org-docsgen-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; org-docsgen-autoloads.el ends here
