;;; denote-notion-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from denote-notion.el

(autoload 'denote-notion-push "denote-notion"
"Push FILE (default the current buffer's file) to Notion as a page.
If FILE is not yet Notion-tracked, PARENT — a (TYPE . ID) cons, where TYPE
is one of the symbols `page', `database', or `data-source' — is required:
prompted interactively unless `denote-notion-default-parent' is set — and
a new page is created.  If FILE is already tracked, its Notion page is
updated, unless the remote page has changed since the last sync, in which
case a conflict is signaled; pass FORCE (or the prefix argument,
interactively) to overwrite anyway.  Also reports (see
`denote-notion--report-dangling-links') any `denote:' links in FILE
that failed to resolve to a Notion page.

(fn &optional FILE PARENT FORCE)" t)
(autoload 'denote-notion-resolve-conflict "denote-notion"
"Interactively resolve FILE's `notion_conflict' via an ediff merge session.
FILE defaults to `denote-notion--file-at-point', erroring (matching
`denote-notion-push''s own style) when there is none.  FILE must already
be Notion-tracked and marked conflicted (see `denote-notion--tracked-p'
and `denote-notion--conflicted-p'); either condition missing is a
`user-error', not silently a no-op.

Builds three in-memory buffers (see
`denote-notion--build-conflict-buffers'): FILE's own current exportable
body, NOTION-ID's current remote body (fetched fresh, not from the
sync-state check that flagged the conflict), and the cached last-synced
ancestor body, if one exists.  When an ancestor exists, starts
`ediff-merge-buffers-with-ancestor' -- a genuine three-way merge that
auto-resolves every region only one side touched, dropping the user into
an interactive session only for the regions both sides touched
differently.  When no ancestor exists (a note tracked before the sync
cache existed, so no prior snapshot was recorded), falls back to a
plain two-way `ediff-buffers' comparing local against remote directly.

The merge's finish action is wired via a buffer-local addition to
`ediff-quit-hook' inside the ediff control buffer, added immediately
after the session starts -- `ediff-quit-hook' is otherwise a single
global hook list shared by every ediff session in the Emacs instance,
so a plain `add-hook' without the LOCAL argument would also fire (and
persist) across any other, unrelated ediff session.  The hook function
kills the three scratch buffers itself before ediff discards its own
control buffer, so nothing leaks past this one merge.

(fn &optional FILE)" t)
(autoload 'denote-notion-add-parent "denote-notion"
"Resolve URL to a Notion data source and add it to
`denote-notion-parent-registry'.
URL is a Notion database or data source URL, or a bare id -- see
`denote-notion--resolve-data-source', which does the actual resolution.
NAME is the entry's display name in the `denote-notion--acr-select-parent'
menu; when omitted it defaults to, and is interactively prompted for
with a default of, the data source's own Notion name.

Adds `(NAME . ((data-source . ID)))' to the front of the in-memory
`denote-notion-parent-registry', replacing any existing entry already
registered under NAME, and also copies that same form to the kill ring:
the registry itself is ordinarily populated by a `setq' in an init file
that this command neither reads nor writes, so the kill ring is what
carries the entry to wherever that `setq' lives for it to survive a
restart.

(fn URL &optional NAME)" t)
(autoload 'denote-notion-pull "denote-notion"
"Pull a Notion page into a denote note, creating or refreshing as needed.

With PAGE-ID (an id, or a Notion URL): pull that specific page.  If
TARGET-FILE, the current buffer, or any other denote note already tracks
that page's id (see `denote-notion--find-tracked-file'), replace that
file's body and refresh its tracking fields in place.  Otherwise create a
new tracked denote note from the page's properties and body — so
re-running an import on a page you already have never creates a
duplicate note, even from a buffer other than the one already tracking it.

Without PAGE-ID: refresh TARGET-FILE (or the current buffer) using its
own already-tracked `notion_id', so \"pull this specific page\" and
\"re-pull whatever I'm already looking at\" are the same command.
Errors if there's no tracked file to fall back on.

Interactively, PAGE-ID is only prompted for when the current buffer isn't
already a tracked Notion note — otherwise this dwim-refreshes the current
buffer directly, with no prompt at all.

(fn &optional PAGE-ID TARGET-FILE)" t)
(autoload 'denote-notion-dash-view-tracked "denote-notion"
"Open a `denote-dash' view of every Notion-tracked note.
Registers (or re-registers, overwriting) a `denote-dash-view' named
`denote-notion--dash-view-tracked-name' whose `grep-filter' matches any
file with a non-empty `notion_id' front-matter line -- the same
\"tracked\" test `denote-notion--tracked-p' applies, rewritten as a
content regexp (see `denote-notion--frontmatter-nonempty-value-regexp')
since that is all a `denote-dash' grep filter is.  Then opens the view
via `denote-dash-open-view'." t)
(autoload 'denote-notion-dash-view-conflicts "denote-notion"
"Open a `denote-dash' view of every note marked `notion_conflict'.
Registers (or re-registers, overwriting) a `denote-dash-view' named
`denote-notion--dash-view-conflicts-name' whose `grep-filter'
(`denote-notion--dash-conflict-grep-filter') matches exactly what
`denote-notion--conflicted-p' itself checks, so the view and the
predicate always agree on what \"conflicted\" means.  Then opens the
view via `denote-dash-open-view'.  Conflict resolution itself is
unrelated and unchanged -- see `denote-notion-resolve-conflict'; this
command only surfaces which notes need it." t)
(autoload 'denote-notion-dash-view-remote-updated "denote-notion"
"Open a backgrounded `denote-dash' view of notes updated on Notion.
Unlike `denote-notion-dash-view-tracked'/`-conflicts', \"updated
remotely\" cannot be decided from a note's own file content alone -- it
requires comparing each tracked note's live Notion `last_edited_time'
against its own stored `notion_edited', one network fetch per tracked
note.  That fetch is never allowed to block opening the view:

1. The view is registered and opened immediately, via the same
   `denote-notion--dash-register-view' / `denote-dash-open-view' pair
   the other two `denote-notion-dash-view-*' commands use, with whatever
   `notion_remote_dirty' marker state (see
   `denote-notion--remote-dirty-p') is already on disk from some earlier
   refresh.  Stale is fine, and expected -- that is the whole point of
   \"instant open\".
2. A fresh per-note async fetch
   (`denote-notion--refresh-remote-dirty-marker-async') is then kicked
   off for every currently Notion-tracked file, each one
   updating that note's own marker field in place as its fetch
   completes, then refreshing the view's buffer (looked up by name,
   guarded with `buffer-live-p' since the user may have killed it before
   a given fetch finishes) via `denote-dash-refresh', so entries update
   in the open buffer incrementally rather than all at once.

`notion_remote_dirty' is a dedicated, purely local bookkeeping field
introduced for this view alone -- chosen over an in-memory note-id ->
bool table so this view stays structurally identical to its two
siblings (register a `denote-dash-view' with a `grep-filter', open it).
It also persists across sessions the same way `denote-dash-saved-views'
does, so a later re-open still reflects the last background refresh's
results even before a fresh one runs again." t)
(autoload 'denote-notion-sync-all "denote-notion"
"Batch-sync every Notion-tracked note via a bounded async process pool.

Builds a lazy generator (see `gen-wrap') over every file under
`denote-directory-files' for which `denote-notion--tracked-p' is
non-nil, wrapping a plain `iter-make' that filters and yields one file at
a time -- never materializing or classifying the full list of tracked
notes up front, so e.g. note 400's `pages get' call is never made at all
if note 50's turns out to already need the user's attention and the rest
of the run is otherwise cut short.  `denote-notion--batch-run' then drives
that generator, keeping at most `denote-notion-batch-max-concurrent-processes'
notes' worth of `ntn' subprocesses in flight at once (see
`denote-notion--sync-all-process-note' for what each note's sync
actually does), rather than either blocking Emacs for the whole batch
serially (the problem this command exists to solve) or starting every
tracked note's subprocess at once regardless of count.

Reports a one-line `message' summary of counts across five buckets:
unchanged, pushed, pulled, conflicted, errored.  A plain `message' is
sufficient here, rather than a dedicated results buffer: nothing needs
random access to individual outcomes, only the aggregate counts, and
`denote-notion--debug-buffer-name' already accumulates every `ntn'
call's raw output (including failures) for anyone who needs to look
closer at exactly which note did what.

One note's failure -- a non-zero `ntn' exit, an unexpected error --never
halts the batch; it is simply counted as `errored' and the run continues
with every other note, unlike a single interactive
`denote-notion-push''s own failure, which signals and stops that one
call outright -- there is no minibuffer prompt watching a batch run for
a signal to usefully interrupt." t)
(register-definition-prefixes "denote-notion" '("denote-notion-"))

;;; End of scraped data

(provide 'denote-notion-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; denote-notion-autoloads.el ends here
