;;; arch-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from arch.el

(autoload 'arch-cache-drop "arch" "\
Clear all cached package info." t)
(autoload 'arch-cache-reload "arch" "\
Clear and repopulate the package info cache from pacman -Qi." t)
(autoload 'arch-sync "arch" "\
Sync package databases (`pacman --sync --refresh')." t)
(autoload 'arch-sync-force "arch" "\
Force re-download of all package databases (`pacman --sync --refresh --refresh')." t)
(autoload 'arch-upgrade-system "arch" "\
Upgrade installed packages without syncing databases (`pacman --sync --sysupgrade')." t)
(autoload 'arch-abs-install "arch" "\
Install or upgrade PKG-NAME from AUR source via `arch-aur-backend's abs-install-fn.

(fn PKG-NAME)" t)
(autoload 'arch-abs-rebuild "arch" "\
Rebuild PKG-NAME from its existing AUR source clone via `arch-aur-backend's abs-rebuild-fn.

(fn PKG-NAME)" t)
(autoload 'arch-search "arch" "\
Search all registered backends for QUERY and show info for the selection.
Results from all backends are merged and grouped by repo in the ACR interface.

(fn QUERY)" t)
(autoload 'arch-search-aur "arch" "\
Search the AUR only for QUERY and show info for the selection.
Requires `arch-aur-backend' to support AUR-only search.

(fn QUERY)" t)
(autoload 'arch-find-package "arch" "\
ACR-select from all sync-DB packages and open arch-info.
Annotation mirrors the package list columns: [repo]  Stat  (version)  description." t)
(autoload 'arch-show-info "arch" "\
Display detailed info for PKG-NAME in a read-only buffer.

(fn PKG-NAME)" t)
(autoload 'arch-kill-info-buffers "arch" "\
Kill all *arch-info<...>* package info buffers." t)
(autoload 'arch-kill-progress-buffers "arch" "\
Kill all *arch:<pkg>* and the shared worker install/build/upgrade progress buffers.
Buffers with a still-running process are left alone." t)
(autoload 'arch-kill-buffers "arch" "\
Kill all arch progress and info buffers.
See `arch-kill-progress-buffers' and `arch-kill-info-buffers'." t)
(autoload 'arch-switch-to-buffer "arch" "\
ACR-select and switch to an open arch buffer, grouped by list/info/compile." t)
(autoload 'arch-dispatch "arch" "\
Entry point for Arch Linux package management.

(fn)" t)
(autoload 'arch-list "arch" "\
Open the arch package list showing installed packages." t)
(autoload 'arch-install "arch" "\
Install PKG-NAME via the default backend, selecting via ACR when interactive.

(fn PKG-NAME)" t)
(autoload 'arch-remove "arch" "\
Remove PKG-NAME via the default backend, selecting via ACR when interactive.

(fn PKG-NAME)" t)
(autoload 'arch-upgrade "arch" "\
Upgrade PKG-NAME via the default backend, selecting via ACR when interactive.

(fn PKG-NAME)" t)
(autoload 'arch-upgrade-all "arch" "\
Upgrade all packages via the default (pacman) backend." t)
(autoload 'arch-upgrade-all-yay "arch" "\
Upgrade all pacman-managed packages via `arch-aur-backend'.
AUR/foreign packages are not upgraded; a warning is logged.  Rebuild those
individually via `arch-abs-install'." t)
(register-definition-prefixes "arch" '("arch-"))


;;; Generated autoloads from arch-elpa.el

(autoload 'arch-elpa-search "arch-elpa" "\
ACR-search all known elisp packages and show info for the selection." t)
(autoload 'arch-elpa-install "arch-elpa" "\
ACR-select and install an elisp package via `package-install'." t)
(autoload 'arch-elpa-list-upgrade-all "arch-elpa" "\
Upgrade all elisp packages with an available upgrade via `package-upgrade-all'." t)
(autoload 'arch-elpa-list "arch-elpa" "\
Open the arch-elpa package list." t)
(register-definition-prefixes "arch-elpa" '("arch-elpa-"))


;;; Generated autoloads from arch-sets.el

(autoload 'arch-sets-export-file "arch-sets" "\
Export explicitly-installed packages to FILE as a package-set YAML file.

(fn FILE)" t)
(autoload 'arch-sets-import-file "arch-sets" "\
Install every package listed in package-set FILE.
Entries are grouped by resolved backend and each group installed as a
single batch when the backend supports it.  Prefer `arch-sets-open-file'
to review install status before installing anything.

(fn FILE)" t)
(autoload 'arch-sets-open-file "arch-sets" "\
Load package-set FILE into `arch-set-mode', showing install status.
Never installs anything on its own; use `arch-set-install-at-point' or
`arch-set-install-missing' in the resulting buffer to do that.

(fn FILE)" t)
(register-definition-prefixes "arch-sets" '("arch-set"))

;;; End of scraped data

(provide 'arch-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; arch-autoloads.el ends here
