;;; rust-playground-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from rust-playground.el

(autoload 'rust-playground "rust-playground" "\
Run playground for Rust language in a new buffer." t)
(autoload 'rust-playground-rm "rust-playground" "\
Remove files of the current snippet together with directory of this snippet." t)
(register-definition-prefixes "rust-playground" '("in-rust-playground" "rust-playground-"))

;;; End of scraped data

(provide 'rust-playground-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; rust-playground-autoloads.el ends here
