;;; denote-sync-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from denote-sync.el

(autoload 'denote-sync-resolve-conflict "denote-sync"
"Interactively resolve FILE's conflict flag via an ediff merge session.
FILE defaults to `denote-sync--file-at-point'.
If BACKEND is nil and FILE is conflicted for multiple backends, prompt
the user to pick which backend conflict to resolve.

(fn &optional FILE BACKEND)" t)
(autoload 'denote-sync-push "denote-sync"
"Push FILE (default current buffer note) to remote.
If FILE is tracked, updates its remote document.
If FILE is untracked, PARENT is required (prompted if nil).
If BACKEND is nil:
- If FILE is tracked by 1 backend, uses it.
- If FILE is tracked by multiple backends, prompts to select backend.
- If FILE is untracked, uses registry selection or prompts for backend.

(fn &optional FILE PARENT FORCE BACKEND)" t)
(autoload 'denote-sync-pull "denote-sync"
"Pull a remote document into Denote, creating or refreshing as needed.
Without REMOTE-ID, refreshes TARGET-FILE (or current buffer file).
With REMOTE-ID (an id or URL):
- If already tracked by any note, refreshes that note.
- Otherwise imports a new note from the remote document.

(fn &optional REMOTE-ID TARGET-FILE BACKEND)" t)
(autoload 'denote-sync-all "denote-sync"
"Batch-sync every tracked note across all backends via a bounded async pool." t)
(autoload 'denote-sync-dash-view-tracked "denote-sync"
"Register and open a `denote-dash' saved view for notes tracked by BACKEND (or default).

(fn &optional BACKEND)" t)
(autoload 'denote-sync-dash-view-conflicts "denote-sync"
"Register and open a `denote-dash' saved view for conflicted notes under BACKEND (or default).

(fn &optional BACKEND)" t)
(autoload 'denote-sync-dash-view-remote-updated "denote-sync"
"Register and open a `denote-dash' saved view for remote-updated notes under BACKEND (or default).

(fn &optional BACKEND)" t)
(register-definition-prefixes "denote-sync" '("denote-sync-"))


;;; Generated autoloads from denote-sync-gdocs.el

(autoload 'denote-sync-gdocs-add-parent "denote-sync-gdocs"
"Add a Google Docs parent target to `denote-sync-parent-registry'.

(fn NAME ACCOUNT FOLDER-ID)" t)
(register-definition-prefixes "denote-sync-gdocs" '("denote-sync-gdocs-"))


;;; Generated autoloads from denote-sync-notion.el

(autoload 'denote-sync-notion-add-parent "denote-sync-notion"
"Resolve URL to a Notion data source and add it to `denote-sync-parent-registry'.

(fn URL &optional NAME)" t)
(register-definition-prefixes "denote-sync-notion" '("denote-"))

;;; End of scraped data

(provide 'denote-sync-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; denote-sync-autoloads.el ends here
