;;; denote-mcp-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from denote-mcp.el

(autoload 'denote-mcp-register "denote-mcp"
"Ensure `denote-mcp-service' is registered in `mcpkit-registry' and return it.
Kept for backward compatibility." t)
(register-definition-prefixes "denote-mcp" '("denote-mcp-"))

;;; End of scraped data

(provide 'denote-mcp-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; denote-mcp-autoloads.el ends here
