;;; agent-shell-workflow-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from agent-shell-workflow.el

(autoload 'agent-shell-workflow-dispatch "agent-shell-workflow"
"Instantiate the workflow ID and dispatch it.
ARGS is a plist supplying template values; missing required args
are read interactively.
TARGET overrides the spec's declared target (`:session-reuse',
`:session-new', `:queue', `:ask').
SUBMIT non-nil forces prompt submission regardless of spec default.
CONTEXT-DIR sets `default-directory' for pre-op execution.

(fn ID &key ARGS TARGET SUBMIT (CONTEXT-DIR default-directory) &allow-other-keys)")
(register-definition-prefixes "agent-shell-workflow" '("agent-shell-workflow-" "register-agent-shell-workflow"))


;;; Generated autoloads from agent-shell-workflow-library.el

(register-definition-prefixes "agent-shell-workflow-library" '("agent-shell-workflow-library-"))


;;; Generated autoloads from agent-shell-workflow-menu.el

(autoload 'agent-shell-workflow-select "agent-shell-workflow-menu"
"Pick a registered workflow via `annotated-completing-read' and dispatch it.
Candidates are annotated with their category and one-line doc.  With
CATEGORY non-nil, only workflows in that category are offered.

(fn &optional CATEGORY)" t)
 (autoload 'agent-shell-workflow-dispatch-menu "agent-shell-workflow-menu" nil t)
(register-definition-prefixes "agent-shell-workflow-menu" '("agent-shell-workflow--candidates"))

;;; End of scraped data

(provide 'agent-shell-workflow-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; agent-shell-workflow-autoloads.el ends here
